### ISSUE TITLE
Выбрать название библиотеки

### ISSUE THREAD

**Issue by SiebenSieben** [alfa-laboratory/core-components#10]
Пора выбрать название.

[![](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/core-components)](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/core-components/vote)
[![](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-components)](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-components/vote)
[![](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-ui)](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-ui/vote)
[![](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-core)](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-core/vote)
[![](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-atoms)](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-atoms/vote)
[![](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-ui-components)](https://api.gh-polls.com/poll/01DWRYY8ANJQ11X2WM5E3HT1BV/alfa-ui-components/vote)

**Comment by stepancar** [comment]
Имхо, атомик - мало кому понятная вещь.
alfa-core - вообще звучит как абстрактная абстракция
alfa-core-components?
arui-core-components?

**Comment by SiebenSieben** [comment]
Название не обязательно должно быть такое буквальное ) накидывай любые варианты

**Comment by YozhEzhi** [comment]
core-components - мой кандидат.

Никогда на выборы не ходил, но этот кандидат от народа.

**Comment by KNIAZEV1** [comment]
Я бы выбрал что-то похожее на **Alfa-UI**, звучит просто и лаконично.
alfa-atoms как-то абстрактно и не понятно сразу о чем речь
core-components слишком длинно

**Comment by etroynov** [comment]
у меня вопрос имеется ввиду @alfa/core или прям alfa-core?

**Comment by etroynov** [comment]
я за @alfa/components - т.к эти компоненты не совсем core

**Comment by YozhEzhi** [comment]
> я за @alfa/components - т.к эти компоненты не совсем core

Они не совсем кор, но будут использоваться другими либами как ядро\фундамент.

**Comment by etroynov** [comment]
> > я за @alfa/components - т.к эти компоненты не совсем core
> 
> Они не совсем кор, но будут использоваться другими либами как ядро\фундамент.

да но эти либы будут в локальной репе в github они не идут вроде. Как у Angular.

**Comment by SiebenSieben** [comment]
> у меня вопрос имеется ввиду @alfa/core или прям alfa-core?

Название репы и агрегирующего пакета, т.е. получается @alfa-laboratory/…

**Comment by SiebenSieben** [comment]
/polls  'core-components' 'alfa-components' 'alfa-ui' 'alfa-core' 'alfa-atoms' 'alfa-ui-components'

**Comment by SiebenSieben** [comment]
Добавил голосовалку )

**Comment by pavelozavr** [comment]
Кстати голосовалка не уникальные голоса считает, можно поднакрутить за любимый вариант
