### ISSUE TITLE
Как именовать кнобсы?

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#100]
Такое чувство что нет стандарта в именовании пропсов на кнобсах
<img width="721" alt="Screen Shot 2020-04-23 at 09 07 00" src="https://user-images.githubusercontent.com/2854910/80064969-f64f9300-8541-11ea-9401-606953c769f1.png">

**Comment by reme3d2y** [comment]
Я сейчас как раз занимаюсь сторибуком. В ближайшее время приведу его в порядок, опишу правила подготовки сторис и закину сюда

**Comment by reme3d2y** [comment]
https://github.com/alfa-laboratory/core-components/pull/104
