### ISSUE TITLE
У компонента Skeleton квадратные уголки 

### ISSUE THREAD

**Issue by ekabolotina** [alfa-laboratory/core-components#1052]
# Опишите проблему
Компонент `Skeleton` отображается с квадратными уголками, хотя в [примере](https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-skeleton--skeleton) имеет скруглённые уголки.

# Шаги для воспроизведения
Пример [можно посмотреть](https://codesandbox.io/s/suspicious-chaplygin-7qdcor?file=/src/App.js) в песочнице.

**Comment by reme3d2y** [comment]
@EGNKupava @blackraydev 
В файлике не подключены все нужные переменные. В идеале бы все остальные компоненты чекнуть

<img width="441" alt="image" src="https://user-images.githubusercontent.com/9968618/161126009-de0b7a26-087b-4664-ab16-4d6ce2771546.png">
