### ISSUE TITLE
Mobile версии компонентов и адаптивность

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#106]
Предлагаю обсудить вопрос о том, как готовить компоненты, которые могут отличаться как визуально, так и функционально на mobile/desktop и при разной ширине экрана. 
Например табы, селекты и пр.

Сейчас этот вопрос решен по-разному:
- В аките компоненты разделены на mobile/desktop
- В фижере — смесь @media и <Mq/>
- В некоторых других продуктах вообще нет адаптивности, насколько я понял
- В других ui-либах — это либо отдельные наборы компонентов([ant](https://mobile.ant.design/)), либо компоненты изначально mobile first.

Исходя их этого — для некоторых компонентов придется реализовывать три версии:
- mobile
- desktop
- responsive (css или js media-queries)

Очень не хочется дублировать код и поддерживать несколько отдельных версий. Хотелось бы решить эту задачу как можно более просто.

У кого какие идеи на этот счет? Поделитесь опытом)

**Comment by denisx** [comment]
Что такое "Статичные версии [должны быть без css или js медиа-выражений]"

**Comment by reme3d2y** [comment]
> Что такое "Статичные версии [должны быть без css или js медиа-выражений]"
обновил описание. Имел ввиду, что mobile и desktop версии скорее всего должны быть неадаптивными.

**Comment by aso1datov** [comment]
Мне нравится идея разделения на mobile/deskop, т.к. в ней я вижу следующие плюсы:
* не возникает случаев, когда приходится реализовывать renderMobile, renderDesktop, что добавляет доп. логику и костыли
* всякие вендор-специфичные штуки (Android/IOS) лежат также отдельно
* какие-то сложные интерфейсы в мобильных устройствах мы можем переложить на нативные (календари, селекты, и т.п.), тем самым разгрузив бандл от различных библиотек, которые реализуют это поведение на десктопе

Какие минусы я вижу:
* поддержка двух библиотек

**Comment by prosto-lapsha** [comment]
Мое мнение такое: приоритет отдается responsive (зачем делать два компонента, когда это неуместно, например для компонента текста).
Компоненты, которые сильно отличаются по реализации в зависимости от того desktop это или mobile, то тогда да, надо делать два компонента, например, sliderMobile и sliderDesktop, НО надо сделать и третий - slider/sliderAdaptive, который сам будет решать когда отдавать мобильный компонент, а когда десктопный

**Comment by etroynov** [comment]
Поддержу @aso1datov и скажу что однозначно должно быть 2 либы как например у antd:
desktop:
https://ant.design/

mobile:
https://mobile.ant.design/

Идея разбиения на 2 глупых компонента и одни умный который решает какой из 2 использовать, мне кажется неудачно т.к она начинает содержать кучу логики в зависемости от определенных фактов.

Стоит помнить что React сам по себе стоит дорого, приписывать еще сверху логику которая будет думать какой компонент использовать не целесообразно.

**Comment by reme3d2y** [comment]
Разбивать на две отдельный либы - имхо, неоправданное усложнение. Далеко не все компоненты будет иметь различия между desktop\mobile. 
Предлагаю оставить все в рамках одной либы, а использовать так:

```
// core-components/packages/switch/src/index.ts
export * from './Component';
export * from './mobile/Component';

// use
import { MobileSwitch } from '@alfalab/core-components-switch';
import { Switch } from '@alfalab/core-components-switch';
```

По поводу умного компонента - согласен. Лучше оставить решение за разработчиками конкретного проекта, когда какую версию компонента использовать.

Но все еще остается вопрос, что делать с адаптивностью. Когда нужно не просто переключить компонент между desktop\mobile, а настроить его с помощью @media.

**Comment by aso1datov** [comment]
@reme3d2y, можешь привести пример с адаптивностью, для наглядности, пожалуйста?

**Comment by denisx** [comment]
>import { MobileSwitch } from '@alfalab/core-components-switch';

только нужен дефолт экспорт, для loadable

**Comment by denisx** [comment]
Про адаптивность тоже не понял, это больше для виджетов, а не кор-компонентов. Но дождусь примера

**Comment by SiebenSieben** [comment]
У НИБа и множества других продуктов адаптивные интерфейсы.

Этим продуктам нужны адаптивные компоненты.

Компоненты arui-feather/arui-private для примера: Tabs, Sidebar, Modal, Notification, Tooltip, Heading, Toggle.

Где-то отличаются только стили (@media), где-то более существенные отличия вплоть до полного разделения renderMobile/renderDesktop (но это редко).

@etroynov мы ведь обсуждали это требование на встрече в ноябре )

В нашем случае разделение на две либы крайне неудобно.

Размер бандла для тех кому нужен только ComponentDesktop или ComponentMobile не увеличится.

**Comment by SiebenSieben** [comment]
Мобильные компоненты получат только мобильные стили, аналогично десктопные. Адаптивные получат все стили с @media.

**Comment by denisx** [comment]
можно разобрать пример с Tooltip и Heading - в чем там адаптивность? и какие границы перехода

**Comment by denisx** [comment]
так-то никто не мешает собирать несколько версий в десктопе и/или мобайле, раз уж прям надо. но точно не нужно пихать адаптивность туда, где она не нужна

**Comment by SiebenSieben** [comment]
> можно разобрать пример с Tooltip и Heading - в чем там адаптивность? и какие границы перехода

**Heading**
Например, H2 на десктопе 40px → на мобилке 22px (у НИБа сейчас так, там даже сложнее, есть промежуточный 30px)

**Tooltip**
Это пример, когда мобилка и десктоп могут полностью отличаться:
![tooltip](https://user-images.githubusercontent.com/109410/80515173-31125a80-898a-11ea-9f3d-1d486ab08794.png)

**Comment by denisx** [comment]
> Heading
 выглядит как нибу нужен отдельный экспорт со своими стилями, расширяющие базовый

**Comment by etroynov** [comment]
> Разбивать на две отдельный либы - имхо, неоправданное усложнение. Далеко не все компоненты будет иметь различия между desktop\mobile.
> Предлагаю оставить все в рамках одной либы, а использовать так:
> 
> ```
> // core-components/packages/switch/src/index.ts
> export * from './Component';
> export * from './mobile/Component';
> 
> // use
> import { MobileSwitch } from '@alfalab/core-components-switch';
> import { Switch } from '@alfalab/core-components-switch';
> ```
> 
> По поводу умного компонента - согласен. Лучше оставить решение за разработчиками конкретного проекта, когда какую версию компонента использовать.
> 
> Но все еще остается вопрос, что делать с адаптивностью. Когда нужно не просто переключить компонент между desktop\mobile, а настроить его с помощью @media.

Разбиение на разные либы решает множество проблем, а также упрощает работу с ними для разработчиков. При этом подходе происходит четкое разделение ответственности что исключает возможность разночтения.

хранение всех сущностей в одной библе нарушает основные принципы проектирования (SOLID, KISS) и порождает большое количество неявных моментов:
- когда нужно использовать то или это;
- как построить архитектуру;
- как именовать;
- и т.д;

С точки зрения поддержки это более сложный вариант, но с точки зрения использования это более понятный и чистый кейс.

p.s я считаю что при разработке библиотек максимальный упор должен быть на простоту и легкость использования,а не на простоту поддержки, т.к разрабатывают несколько человек а использовать будут все. Если библиотека будет сложной в использовании и не оптимальной то я предпочту ее не использовать.

**Comment by reme3d2y** [comment]
Чтобы не было недопониманий, говоря разные либы — мы имеем ввиду полностью независимые репы, или условную папку `mobile-packages`  внутри репы `core-components`?

**Comment by SiebenSieben** [comment]
@etroynov так ведь для пользователя никакой разницы не будет

**Comment by reme3d2y** [comment]
Сразу уточню, компоненты будут разделены на версии.
Если нужен только mobile\desktop компонент, то можно будет подключить только его, без лишнего кода, зависимостей и пр.

> когда нужно использовать то или это

Разделение либ не решает этот вопрос. Когда нужен мобильный компонент - берешь мобильный, когда десктопный - десктопный

> как построить архитектуру

Учитывая, что компоненты почти всегда будут иметь общие части, то намного проще организовать это внутри одной либы, чем создавать третью и выносить туда то, что не понадобится больше нигде.

> как именовать

ох уж этот нейминг :)

Насчет KISS - так простой и понятный вариант - это как раз не разделять все на разные либы, которые еще и будут связаны так или иначе.
А еще есть DRY. 

Объясни, пожалуйста, в чем конкретно будет сложность для пользователя?

Для пользователей либы фактически не будет никакой разницы между этими вариантами:
    
    ```jsx
    import { MobileSwitch } from '@alfalab/core-components-switch';
    // vs
    import { Switch } from '@alfalab/mobile-core-components-switch';
    ```

**Comment by SiebenSieben** [comment]
> но я не понял, причем тут десктоп с переходом в мобайл, когда это разные сборки.

У вас разные сборки, у других — одна сборка.
Для вас будет отдельно мобильный компонент, отдельно десктопный.

**Comment by denisx** [comment]
> У вас разные сборки, у других — одна сборка.

стоит подумать о переходе на раздельные сборки?

**Comment by SiebenSieben** [comment]
> стоит подумать о переходе на раздельные сборки?

Даже если кто-то задумается, все точно не перейдут )
Далеко не всегда это целесообразно.

**Comment by denisx** [comment]
нецелесообразно делать media, но делают же зачем-то

**Comment by SiebenSieben** [comment]
#175
