### ISSUE TITLE
Внедрить цвета из дизайн-токенов

### ISSUE THREAD

**Issue by SiebenSieben** [alfa-laboratory/core-components#11]
Цвета из фигмы экспортируются в [alfa-ui-primitives](https://github.com/alfa-laboratory/alfa-ui-primitives/blob/master/styles/colors.json).

Любой цвет в компонентах (color, background-color, border-color) должен использовать цвет из этого набора.

Нужно добавить зависимость и генерить файл со списком переменных:
```
:root {
    --color-dark-indigo: #0b1f35;
    --color-dark-indigo-60: rgba(11, 31, 53, 0.6);
    ...
}
```

**Comment by YozhEzhi** [comment]
@SiebenSieben А hex для чего?

**Comment by SiebenSieben** [comment]
@YozhEzhi

Соответствует тому, что увидишь в фигме.
А ещё hex чуть быстрее, чем rgba )

Но вообще это мелочь, конечно, потому что в фигме нужно смотреть на название.
Можно везде rgba.

**Comment by 7rulnik** [comment]
Вопрос: нужно ли генерить сам файл? Обычно можно подсунуть json в . сам postcss плагин

**Comment by YozhEzhi** [comment]
@7rulnik Мне кажется с файлом удобнее смотреть в цвета нежели в json.

**Comment by SiebenSieben** [comment]
Генерить несложно, будет нагляднее и удобнее.
