### ISSUE TITLE
Новый компонент CheckboxGroup

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#111]
#### Предлагаю добавить новый компонент `<CheckboxGroup />`

[Макет](https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=83%3A306)

#### API
| Свойство     |   Описание        |    Тип    | Значение по умолчанию | Обязательное |
|--------------|:-------------------:|:---------:|:---------------------:|-------------:|
| label | Заголовок группы | ReactNode | - | - |
| direction | Направление | 'horizontal' / 'vertical' | 'vertical' | - |
| type | Тип компонента | 'checkbox' / 'tag' | 'checkbox' | - |
| className | Дополнительный класс | string | - | - |
| error |  Текст ошибки |string | - | - |
| children | Дочерние элементы. Ожидаются компоненты `Checkbox` или `Tag` | ReactNode | - | да |
| onChange | Обработчик изменения значения 'checked' одного из дочерних компонентов | ChangeHandler (см. ниже) | - | - |
| disabled | Управление возможностью изменения состояния 'checked' дочерних компонентов CheckBox | boolean | - | - |
| dataTestId | Идентификатор для систем автоматизированного тестирования | string | - | - |

```tsx
onChange?: (
    event?: ChangeEvent | MouseEvent,
    payload?: {
        checked: boolean;
        name?: string;
    },
) => void;
```

#### Референсы:
Компонент в [arui-feather](https://digital.alfabank.ru/components/checkboxgroup)

#### Требования:
Может содержать в себе компоненты `Checkbox` и `Tag`

**Comment by etroynov** [comment]
каким требованиям должны соотвествовать компоненты что их можно было юзать внутри этого компонента? просты кнопки можно?

что значит изменение значения дочернего компонента? он разве не статичный?
