### ISSUE TITLE
Нам нужен линтинг переменных. Народ хардкодит

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#117]
Для arui-feather используется линтер который чекает что я использую переменные. Тут этого нет. -100 к devexp. 
Нам супер надо

**Comment by dmitrsavk** [comment]
Посмотрели этот линтер, решили что будем его развивать, сделаем пулл-реквест.
Будем форсировать использование core-components-vars.
Ждём обновлённую палитру цветов, после этого начнем допиливать `arui-cssvars`

**Comment by aso1datov** [comment]
Все ещё супер надо

**Comment by reme3d2y** [comment]
Скоро-скоро будет решение
