### ISSUE TITLE
Что с макетами?

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#12]
Что по поводу фигмы? Как будем хранить эти компоненты в фигме, как будем предоставлять ссылки? Мы в opensource - откроем фигму в паблик?

**Comment by SiebenSieben** [comment]
Компоненты в фигме хранят и обновляют дизайнеры :)
Ссылки есть, буду добавлять в issues, но в паблик пока не откроем.

**Comment by 7rulnik** [comment]
Мы могли бы просто заюзать https://github.com/pocka/storybook-addon-designs
Так что внутри банка была бы удобная ссылочка на макеты

**Comment by stepancar** [comment]
@7rulnik не работает с приватными проектами

**Comment by YozhEzhi** [comment]
У нас в akit оформляется ссылка в readme.md. Таким образом можно добавлять новые ссылки с новым дизайном, но оставлять старые. Типа:

- Макет v1
- Макет v2

**Comment by etroynov** [comment]
Будем делать readme т.к addon-designs не умеет работать с приватными репозиториями
