### ISSUE TITLE
Новый компонент Loader

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#122]
# Описание
Предлагаю добавить новый компонент `Loader`

<img width="454" alt="Снимок экрана 2020-05-18 в 15 08 33" src="https://user-images.githubusercontent.com/16844982/82211403-74bd0c00-9919-11ea-860e-2b447ca1c83b.png">

[Макеты](https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=1619%3A1163)

#### За основу предлагаю взять [компонент](http://git.moscow.alfaintra.net/projects/NEWCLICK/repos/newclick-components/browse/src/components/Spinner/Component.tsx) `Spinner` из `newclick-components`.

# API
| Свойство     |                Описание                |    Тип    | Значение по умолчанию | Обязательное |
|--------------|:--------------------------------------:|:---------:|:---------------------:|-------------:|
| className         |       Дополнительный класс     | string |           -           |          нет |
| dataTestId         |      Идентификатор для систем автоматизированного тестирования     | string |           -           |          нет |

**Comment by denisx** [comment]
чем отличается от <img src="loader.gif" ?

**Comment by dmitrsavk** [comment]
главное отличие - возможность навесить стили и поменять внешний вид: например, цвет точек. ну и браузеру не нужно грузить лишние ассеты. а гифки вроде могут немало весить.

**Comment by denisx** [comment]
немало может весить common-бандл, чтобы эта штука заработала :)

**Comment by etroynov** [comment]
думаю стоит добавить props speed

**Comment by SiebenSieben** [comment]
@etroynov delay это задержка до начала анимации или задержка перед отображением компонента?
