### ISSUE TITLE
Именование css-файлов

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#129]
При компиляции css-модулей мы генерируем класснеймы по следующему правилу:

```tsx
// hash берется от строки `${packageName}@${packageVersion}`
return `${packageName}__${className}_${hash}`;
```

Для примера, для класса `.label` компонента `button` будет сгенерирован такой класснейм:
`.button__label_ecft2`.

При таком подходе у нас возникает проблема, если в пакете несколько css-файлов с одинаковыми класснеймами. Например, в компоненте [Select](https://github.com/alfa-laboratory/core-components/pull/118) несколько файлов `index.module.css`, и в каждом файле присутствует класс `.component`.

В итоге возникает коллизия имен.

Для решения этой проблемы предлагаю:
1) Именовать css-файлы по содержанию, например `select.module.css`, `field.module.css`, etc
2) При генерации класснейма учитывать название файла, например так:
```tsx
return `${packageName}__${fileName}__${className}_${hash}`;
```
или так:
```tsx
// hash берется от строки `${packageName}@${packageVersion}@{fileName}`
return `${packageName}__${className}_${hash}`;
```
Во втором случае имена будут короче.

В любом случае, предлагаю именовать css-файлы по содержанию. Кто что думает по этому поводу?

**Comment by SiebenSieben** [comment]
Предлагаю сами компоненты также именовать по названию компонента

**Comment by stepancar** [comment]
@dmitrsavk react-dev-utils смотрит на название папки если встречает index файл

**Comment by stepancar** [comment]
https://github.com/alfa-laboratory/arui-scripts/issues/81

**Comment by denisx** [comment]
рекомендация такая, зачем кастомщина? что вы ей решаете?

<img width="428" alt="Screenshot 2020-05-26 at 17 02 06" src="https://user-images.githubusercontent.com/427776/82909950-a6198580-9f72-11ea-9597-b41852e6704d.png">

**Comment by dmitrsavk** [comment]
> @dmitrsavk react-dev-utils смотрит на название папки если встречает index файл
Спасибо, посмотрю

**Comment by dmitrsavk** [comment]
@denisx 
были проблемы с хэшом, например [hash:base64:5] давал одну и ту же строку, при небольших изменениях в файле. из-за этого были проблемы с коллизией имен при использовании двух версий одной и той же либы на проекте

**Comment by dmitrsavk** [comment]
@stepancar 
у вас же вроде бы была такая проблема?

**Comment by denisx** [comment]
ну 5 мало, в проде надо 8/10/12. у нас воообще кастомный сборщик - чтобы хорошо файлы жались. а длинну кеша собираемся валидировать плагином (минус объём, минус коллизии)

**Comment by dmitrsavk** [comment]
я все равно не понял, надо 8, 10 или 12? как это определить?

**Comment by denisx** [comment]
если 8 не хватит - бампайте выше

как смогу дать ссылку на наш код - сделаю это )

**Comment by dmitrsavk** [comment]
@denisx 
проверил сейчас результат сборки с `[hash:base64:12]`:
поменял одно css-правило в самом первом селекторе в файле, в итоге хэш не поменялся:
`._3SELUM0dKNW4`
`._3SELUM0dKNW4`

**Comment by dmitrsavk** [comment]
`react-dev-utils` не подошел, так как он завязан на вебпаке. Предлагаю такой вариант:

```tsx
// hash берется от строки `${packageName}@${packageVersion}@{folderName}`
return `${packageName}__${className}_${hash}`;
```

**Comment by denisx** [comment]
@dmitrsavk сложно без кода. но вероятно оно и не должно поменяться? надо точнее определиться с проблемой, пока выглядит что вы лечите не причину, а следствие

**Comment by dmitrsavk** [comment]
@denisx 
хэш должен меняться, потому что при использовании двух разных версий одной библиотеки могут перезатереться стили. такая проблема была у клика и НИБа, если не ошибаюсь

**Comment by denisx** [comment]
@dmitrsavk я не был так категоричен, и всё-таки углубился бы в проблему (если это важно). Сейчас ты рушишь долгосрочное кеширование.

**Comment by dmitrsavk** [comment]
@stepancar можешь, пожалуйста, еще раз озвучить вашу проблему с разными версиями библиотеки и стилями. и решает ли мой PR эту проблему

**Comment by stepancar** [comment]
@dmitrsavk Нет , не решает.

Проблема

грузятся стили лэйаута
стиль компонента библиотеки
.button {
     background: red
}

в лэйауте переопределение
.navButton {
    background: green;
}

далее загружается приложение в лэйаут и грузит свои стили

один из них

.button {
     background: red
}

получается стиль дважды применяется



мы решили эту проблему на уровне сборки layout приложения префиксированием всех стилей лэйаута, так же как это делают корпораты только короче

**Comment by SiebenSieben** [comment]
@stepancar

Получается, это разные проблемы.

В твоём примере проблема может возникнуть когда в лейауте и приложении используется одна версия компонента. При этом если в лейауте вы переопределили стили, то они вернуться к исходным стилями приложения. Вы это решаете префиксом, ок.

Но могла возникнуть проблема при использовании разных версий компонента, её и мы и решаем в #131.
