### ISSUE TITLE
Новый компонент Link

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#140]
# Описание
Предлагаю добавить новый компонент `Link`

<img width="1200" alt="Снимок экрана 2020-06-04 в 15 47 00" src="https://user-images.githubusercontent.com/16844982/83758404-b5878580-a67a-11ea-8f06-0ded7ceda312.png">

[Макеты](https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=719%3A1)

# API
| Свойство     |                Описание                |    Тип    | Значение по умолчанию | Обязательное |
|--------------|:--------------------------------------:|:---------:|:---------------------:|-------------:|
| href | Ссылка для перехода | string | - | нет |
| view | Вид ссылки | primary/secondary/color(или default?) | primary | нет |
| pseudo | Пунктирное подчеркивание | boolean | false | нет |
| className         |       Дополнительный класс     | string |           -           |          нет |
| dataTestId         |      Идентификатор для систем автоматизированного тестирования     | string |           -           |          нет |
| onClick | Обработчик клика | (e: React.MouseEvent) => void; | -  | нет |
| children | Дочерние элементы | ReactNode | - | Да

**Comment by stepancar** [comment]
У нас есть кнопка назад, которая ссылка но выглядит как кнопка. Мы сипользуем кнопку ghost и передаем туда href. Соответственно тут нет противоречия? Типа есть кропка, а есть кнопка ссылка и ест ссылка, верно?

**Comment by SiebenSieben** [comment]
Да, эти ссылки для других кейсов, в вашем случае подойдёт Button

**Comment by stepancar** [comment]
Стоит ли выделять отдельно href onClick children ?

Просто пропсы ссылки

**Comment by aso1datov** [comment]
Свойства `target` или `download` предполагаются?

**Comment by reme3d2y** [comment]
> Свойства `target` или `download` предполагаются?

доступны все свойства из AnchorHTMLAttributes<HTMLAnchorElement>

**Comment by aso1datov** [comment]
А можно сделать `href` необязательным параметром, как в стандарте? Бывают кейсы, когда дизайнеры хотят чтобы текст выглядел как ссылка и, к примеру, открывал модальное окно.

`Button view="link"` такой кейс не покроет.  Я понимаю, что можно поставить туда `#`, но все же хотелось бы этого не делать.

https://www.w3.org/TR/2016/REC-html51-20161101/textlevel-semantics.html#the-a-element

**Comment by dmitrsavk** [comment]
@aso1datov 
сделал опциональным
