### ISSUE TITLE
Компонент Tooltip не работает с иконкой

### ISSUE THREAD

**Issue by aso1datov** [alfa-laboratory/core-components#143]
# Опишите проблему
При попытке использовать в качестве children компонент иконки - не срабатывают эвенты, т.е. тултип не показывается при наведении/клике. Так же, теряется className (возможно и другие пропсы)

# Шаги для воспроизведения

```js
import { Tooltip } from '@alfalab/core-components/tooltip';
import { InformationCircleMIcon } from '@alfalab/icons-glyph';

styles.icon = { color: #fff };
```

```jsx
<Tooltip trigger='hover' content={<div>Привет</div>}>
    <InformationCircleMIcon className={styles.icon} />
</Tooltip>
```

# Ожидаемое поведение
При наведении должен показывается тултип, класс styles.icon остается у иконки

**Comment by dmitrsavk** [comment]
@aso1datov 
`className` у дочернего элемента тултипа появится после мерджа #147.
по иконкам все готово - обнови до `@alfalab/icons-glyph@1.15.0`
