### ISSUE TITLE
Необходимо дать возможность передавать ошибку без текста

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#148]
У нас есть кейсы когда инпут должен подсвечиваться но текста ошибки нет. Сейчас core-components-input принимает error string.
Что делать?

**Comment by reme3d2y** [comment]
Поменяем на `string | boolean`. Нужно только уточнить у дизайнеров, скрывать ли в таком случае хинт или нет. 

Как workaround пока: `error={' '}`

**Comment by reme3d2y** [comment]
Добавили возможность
