### ISSUE TITLE
Компоненты для табов

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#152]
# Описание
Предлагаю добавить компоненты для табов и обсудить, какие компоненты кому потребуются.

Сейчас готовы заголовки табов, двух видов - primary и secondary (в виде тэгов). 

[Демка](https://alfa-laboratory.github.io/core-components/bb1aa8dfad6742accc1d54f115c9a35074683c9d/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-tabs--primary-tabs-header)

https://github.com/alfa-laboratory/core-components/pull/149

- Какие компоненты нужны помимо заголовков?
- Нужен ли компонент Tabs с логикой переключения вкладок?
- Нужен ли в заголовках scroll-into-view и анимация?
- Выделять ли мобильные версии в отдельные компоненты?

# Внешний вид

<img src="https://user-images.githubusercontent.com/9968618/84387016-02c7a200-abfb-11ea-9495-6123d885ce5a.png" width="480" />

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=719%3A2

# API

```tsx
type TabsProps = {
    /**
     * Id активного таба
     */
    selectedId?: string | number;

    /**
     * Рендерить неактивные табы
     */
    keepMounted?: boolean;

    /**
     * Рендерить заголовки табов в контейнере со скроллом
     */
    scrollable?: boolean;

    /**
     * Компоненты табов
     */
    children: Array<ReactElement<TabProps>>;

    /**
     * Компонент заголовков табов
     */
    TabList: ComponentType<TablistProps>;

    /**
     * Обработчик переключения табов
     */
    onChange?: (event: MouseEvent, payload: { selectedId: string | number }) => void;
};
```

## TabProps

```tsx
type TabProps = {
    /**
     * Id таба
     */
    id: SelectedId;

    /**
     * Заголовок таба
     */
    title: string;

    /**
     * Дополнительный класс
     */
    className?: string;

    /**
     * Управление видимостью таба
     */
    hidden?: boolean;

    /**
     * Рендерить таб, если он неактивен
     */
    keepMounted?: boolean;

    /**
     * Контент таба
     */
    children: ReactNode;
}
```

Текущие реализации
- [`arui-feather`](https://alfa-laboratory.github.io/arui-feather/styleguide/#/Tabs)
- [`akit`](https://alfabank.ru/api/akit/?path=/story/components-navigation-tabs-readme--default-story)
- [`newclick-components`](https://digital.alfabank.ru/demo/newclick-components/master/?path=/story/common-tabs--my-story)

**Comment by denisx** [comment]
табы по сути комбайн из скрола чипсов и контентной части. 
управление трубуется такое: надо открывать по дефолту первый чипс, если не выбран пропсом другой, и атрибут для каждой контентной вкладки - рендерить в html сразу или по запросу выдавать (сео)
содержимое табов закидывать чилдами

**Comment by stepancar** [comment]
Хочется чтобы там были сделаны по WCAG

**Comment by reme3d2y** [comment]
Изначально думали добавить только простые табы(заголовки), как в фижере. 
Но мне кажется, что лучше сделать полноценный компонент. При этом останется возможность взять только хедер и собрать табы самому

**Comment by reme3d2y** [comment]
Обновил реквест:

- Добавил основной компонент `<Tabs/>`
- Вынес общую логику в хук `useTabs`
- Добавил клавиатурное управление и разметку в соответствии с WCAG
