### ISSUE TITLE
Компонент для ввода денежных значений

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#155]
# Описание
Предлагаю добавить компонент для ввода денежных значений

Варианты названий
👍  MoneyInput (такое название в фижере)
🚀  AmountInput (Amount - название компоеннета для отображения сумм в фижере)
❤️  CurrencyInput

Ставьте реакцию 

# Поведение
Позволяет ввести денежное значение, отвечает за форматирование денежного значения
Не позволяет вводить неправильные значения.
Отображает валюту, позволяет работать с валютами разлчными minorityUnits
Поведение совпадает с https://digital.alfabank.ru/components/moneyinput
Позволяет не работать на проекте со строкой, заниматься форматированиями и тд
При выделении всего значения символ валюты не выделяется,
Каретка не может быть справа от знака валюты
Минорные единицы красятся в цвет отличающийся от цвета мажорных единиц
Поддержка bold режима (font-weight: bold;)
По умолчанию если не введено значение placeholder формируется как 0+ тонкий проблел + символ валюты

# Чек лист
- [x] Макеты
- [x] Базовые тесты
- [x] Тесты на каретку
- [x] Документация

# Внешний вид
https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=532%3A544
В проработке.
Выглядит так же как обычный инпут.

# Технические требования
- Позволяет работать как с controlled и uncontrolled компонентом
- В отличии от https://digital.alfabank.ru/components/moneyinput не принимает shape Amount
 потому что все направления имеют разные интерфейсы и их выход - обертка над этим компонентом
- Поддерживает все те же параметры что и Input
- варианты реализации 
  1) Влоб (опробовано, довольно успешно)
  2) TextMaskCore (опробовано, частично успешно, не тривиально) есть проблемы с кареткой например https://github.com/text-mask/text-mask/issues/830

# API
```
type MoneyInputProps = Omit<InputProps, 'onChange' | 'rightAddons'> & {
    /**
     * Денежное значение в минорных единицах
     * Если передано значение null - это значит что значение не установлено, поле пустое
     */
    value?: number | null; Максимальное значение = 9 999 999 999 00 копеек

    /**
     * Валюта
     */
    currency?: string;

    /**
     * Минорные единицы
     */
    minority?: number;

   /**
   * Жирный
   */
   bold?: boolean;

    /**
     * Обработчик события изменения значения
     */
    onChange?: (
        e: React.ChangeEvent<HTMLInputElement>,
        payload: {
            /**
             * Денежное значение в минорных единицах
             */
            value: number;
            /**
             * Значение инпута
             */
            valueString: string;
        },
    ) => void;
};
```

## Дополнительно

Сейчас в arui-feather есть amount а есть moneyInput
Что по названиям странно, предлагаю выбрать один префикс

**Comment by etroynov** [comment]
предлагаю сделать проброс основных callback event через дженерик, что бы не дописывать при необходимости.

**Comment by stepancar** [comment]
@etroynov все events пробрасываются. onChange описан потому что имеет расширенный интерфейс в соовтствии с договренностью о том как в этой библиотеке раширяется event доп инфой

**Comment by FenkoAlex** [comment]
голосую за MoneyInput

**Comment by reme3d2y** [comment]
Еще нужен плавающий значок валюты, как в фижере

**Comment by stepancar** [comment]
@reme3d2y @SiebenSieben это прям железно, да? Дайте финальный макет плиз

**Comment by aso1datov** [comment]
Сейчас можно вводить отрицательные значения, нужно ли это регулировать как-то? Или оставить решение за потребителем?

**Comment by etroynov** [comment]
> @etroynov все events пробрасываются. onChange описан потому что имеет расширенный интерфейс в соовтствии с договренностью о том как в этой библиотеке раширяется event доп инфой

понял.

**Comment by stepancar** [comment]
@aso1datov подразумевается что пустую строку туда передавать нельзя. Разботаем с числами; Видишь кейс когда нужно передавть пустую строку?

**Comment by etroynov** [comment]
> @aso1datov подразумевается что пустую строку туда передавать нельзя. Разботаем с числами; Видишь кейс когда нужно передавть пустую строку?

а если с бэка придет?

**Comment by stepancar** [comment]
@etroynov с бэка всегда приходит число. и должно приходить

**Comment by stepancar** [comment]
Про отрицательные числа - буду узнавать насколько это нужно

**Comment by aso1datov** [comment]
@stepancar маловероятно конечно, но я тут больше топлю за стабильность компонента, как вариант можно начальное значение устанавливать так:

```typescript
const [inputValue, setInputValue] = useState<string>(value?.toString() ?? '');
```

**Comment by stepancar** [comment]
@aso1datov , учту

**Comment by stepancar** [comment]
давайте называть minority

**Comment by stepancar** [comment]
Добавил пропс bold, в соответствии с требованием от @SiebenSieben 
Не очень мне этот пропс нравится тут.

**Comment by stepancar** [comment]
@aso1datov на данный момент кейса отрицательных чисел нет. В фижере поддержи отрицательных чисел так же нет.

**Comment by AlexeyRyashencev** [comment]
@stepancar у нас на проекте есть 3 разных варианта значений:
- значение не задано
- 0
- величина до 9 999 999 999
т.е пустое значение имеет место быть.

**Comment by AlexeyRyashencev** [comment]
еще не понятно что такое
```
  /**
     * Валюта
     */
    currency?: string;
```
Это значок после числа?
Можно вместо currency и minority использовать currency как в thrift-services/entities
```
export interface Currency {
    code?: number;
    mnemonicCode?: string;
    minorUnits?: number;
    unicodeSymbol?: string;
    fullName?: string;
}
```
и как регулировать максимальную длину?

**Comment by stepancar** [comment]
@AlexeyRyashencev Trift известен только нибу. Но у вас будет своя обертка в arui-private работающая с вашим контрактом

**Comment by stepancar** [comment]
@AlexeyRyashencev для какой задачи потребовалось регулировать максимальную длину?

**Comment by stepancar** [comment]
@AlexeyRyashencev можете описать для чего есть понятие пустая строка и 0?
Какие кейсы?
