### ISSUE TITLE
Использование наследуемых свойств в миксинах для typography

### ISSUE THREAD

**Issue by NatalyaZ** [alfa-laboratory/core-components#158]
Предлагаю обсудить такой момент.

В миксинах для typography все свойства наследуемые. И в случае, когда надо поменять только начертание шрифта, используя миксин, мы так же дублируем и font-family, font-size или font-weight, даже если они такие же, как у родителя.

Я вижу тут проблему в том, что итоговый css будет разрастаться.

Предлагаю доработать миксины для typography, чтобы можно было без указания font-family изменять начертание шрифта

**Comment by Makvagabo** [comment]
Предлагаю атомизировать миксины, напрмер:
```
@define-mixin 40-48 {
    font-size: 40px;
    line-height: 48px;    
}
@define-mixin medium {   
    font-weight: 500;
}
```
А по поводу семейства шрифтов, оно разве не глобально устанавливаться должно в темизации?

**Comment by SiebenSieben** [comment]
Спасибо, семейство будем выносить

**Comment by reme3d2y** [comment]
Вынесли font-family для системного шрифта
