### ISSUE TITLE
Компонент Input

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/core-components#16]
# Описание

Предлагаю добавить элемент, для ввода данных ( Input ).

# Чек лист

- [x] Тесты
- [ ] Документация

# Внешний вид

https://digital.alfabank.ru/components/input

# API
| Свойство     | Описание                                                      | Тип      | Значение по умолчанию | Обязательное |
|--------------|---------------------------------------------------------------|----------|-----------------------|--------------|
| type         | оформление в соотвествии с используемой дизайн системой | string   | 'default'             | нет          |
| htmlType     | тип поля ввода ( значение атрибута `type` )                   | string   | 'text'                | нет          |
| value        | значение                                                      | string   | -                     | нет          |
| disabled     | заблокировать поле ввод                                       | boolean  | false                 | нет          |
| defaultValue | начальное значение                                            | string   | -                     | нет          |
| placeholder  | текст подсказки                                               | string   | -                     | нет          |
| block        | поле на всю ширину | boolean  | false                 | нет          |
| onInput      | обработчик ввода текста                                       | function | -                     | нет          |
| onFocus      | обработчик попадания в фокус                                  | function | -                     | нет          |
| onBlur       | обработчик потери фокуса                                      | function | -                     | нет          |
| className    | пользовательский класс                                        | string   | -                     | нет          |
| data-testid  | класс для тестирования                                        | string   | -                     | нет          |

**Type: default, ghost**

# Технические требования

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация

исходный код: https://github.com/alfa-laboratory/arui-feather/tree/master/src/button
пример: https://digital.alfabank.ru/components/button

**Comment by YozhEzhi** [comment]
1. API скопировано из кнопки. Стоит поправить.

2. Думаю, необходимы обработчики `onBlur` | `onFocus`.

3. Думаю, не хватает `size`.

4. А признак валидности\ошибки - в следующих сериях?

**Comment by stepancar** [comment]
А что по поводу методов? Типа focus?

**Comment by SiebenSieben** [comment]
Ещё не хватает:
* `label`
* `value` и `defaultValue`
* `block` (аналогично кнопке)

Что будем делать с `hint` и `error`?
Может не в базовой версии компонента, но отображение подсказки и ошибки нужно.

`type` (вариант оформления) тут не нужен.

**Comment by etroynov** [comment]
hint и error история не для примитивов.

**Comment by SiebenSieben** [comment]
> hint и error история не для примитивов.

Ок, можно сделать базовый примитив без этого, но расширенный компонент с hint и error нужен, чаще будет использоваться именно он.

**Comment by etroynov** [comment]
реализовано.
