### ISSUE TITLE
getByLabelText в тесте компонента Input

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#163]
В тестах не получается привязаться к инпуту по labelText
<img width="818" alt="Screen Shot 2020-06-17 at 23 08 20" src="https://user-images.githubusercontent.com/2854910/84945181-9fa0a880-b0ef-11ea-9fcd-c650d0f424e9.png">

testing library для того и не дает нам селекторы чтобы компоненты писались акцессабильными. Сейчас у инпута label почему-то эмулирован спаном, хотя по WCAG это неправильно

**Comment by reme3d2y** [comment]
Обернуть в label не получится, поэтому нужно другое решение.

Можно обсудить варианты с генерацией id, либо попробовать решить это с помощью только aria-атрибутов
