### ISSUE TITLE
cebab-case в css стилях при импорте на другие проекты

### ISSUE THREAD

**Issue by Artess999** [alfa-laboratory/core-components#165]
# Опишите проблему
Если класс css написан в нотации kebab-case (например, .tag-label), то при импорте компонента на другой проект такие стили не подтягиваются (но в сторибуке все работает так, как и ожидается - стили подтягиваются)

**Comment by stepancar** [comment]
@dmitrsavk @SiebenSieben @etroynov @reme3d2y а че вообще за  kebab в классах если в cssModules написано использовать camelCase?

**Comment by dmitrsavk** [comment]
Кто-то этого может не знать и написать в kebab-стиле, и у него будет все ок в сторибуке. Надо либо это поведение отрубить, либо линтить.

**Comment by reme3d2y** [comment]
@stepancar у нас сторибук сейчас поддерживает кебаб, из-за этого возникает путаница. Мы сами пишем стили в camelCase.

Отключим кебаб в сторибуке и, возможно, добавим линтинг
