### ISSUE TITLE
элементы с z-index перекрывают Tooltip 

### ISSUE THREAD

**Issue by Regina94** [alfa-laboratory/core-components#185]
# Проблема
Тултип перекрывается, нужно решение

# Шаги для воспроизведения
1. разместить тултип который накладывается на элемент с z-index
2. Нажать на тултип

# Ожидаемое поведение
Тултип отображается поверх

<img width="354" alt="Screenshot 2020-06-26 at 12 58 19" src="https://user-images.githubusercontent.com/8151643/85846587-ba89b180-b7ae-11ea-980a-104f3b9efd55.png">

**Comment by ilyamilosevic** [comment]
Для таких проблем можно использовать компонент Stack, чтобы централизованно управлять z-index-ом. См. примеры в [akit](https://alfabank.ru/api/akit/?path=/story/utils-stack--nested-stacks) или [evergreen](https://github.com/segmentio/evergreen/blob/master/src/stack/src/Stack.js).

**Comment by SiebenSieben** [comment]
В любом случае надо повысить `z-index` тултипа, сейчас 1 )

**Comment by denisx** [comment]
повышение z-index на уровне компонента маскирует проблему, а не решает
