### ISSUE TITLE
Переименовать MoneyInput в AmountInput

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#187]
Сейчас есть 2 компонента:
Amount и MoneyInput хотя один за ввод, другой за отображение одного и того же
Интересно что бэк называет структуру для денег Amount
прямо поля так называет
Есть 3 варианта
Amount и AmountInput (так совместимость терминологии с бэком)
Money и MoneyInput (так вроде называется лучше, но будет конфликтовать по неймингу в  приложениях)
оставить как есть Amount MoneyInput
Голосуем, предлагаем свои.

Голоса распределились как 
1 ) 8
2) 3
3) 4
Был один голос за альтернативный вариант от @etroynov который не был предложен.

Итого, предлагаю переименование по результатам голосования

**Comment by reme3d2y** [comment]
Переименовано в Amount и AmountInput
