### ISSUE TITLE
Новый компонент PhoneInput

### ISSUE THREAD

**Issue by aleksey-ilin** [alfa-laboratory/core-components#191]
# Описание
Предлагаю добавить компонент `<PhoneInput />`

# Поведение
1) если вставляется номер телефона длиннее маски, то лишнее обрезать

2) форматирование при наборе. при вводе в пустое поле:

    2.1) 7 форматируется в +7

    2.2) 8 форматируется в +7

    2.3) + форматируется в +7

    2.6) <любая цифра кроме 7 и 8> форматируется в +7 <любая цифра кроме 7 и 8>

    2.7) вводим + → подставляется "+7 ", далее вводим 7 → ничего не меняется, в поле остается "+7 "

3) форматирование при вставке (маска +7 ХХХ ХХ-ХХ-ХХ):

    3.1) +71112223344 -> +7 111 222-33-44

    3.2) 81112223344 -> +7 111 222-33-44

    3.3) 1112223344 -> +7 111 222-33-44

    3.4) 8882223344 -> +7 888 222-33-44

    3.5) 71112223344 -> +7 111 222-33-44

    3.6) +7 (111) 222-33-44 -> +7 111 222-33-44

 4) дефолтная маска ['+', '7', ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/]

5) при вводе в пустое поле <любая цифра кроме 7 и 8> форматируется в +7 <любая цифра кроме 7 и 8>, если потом нажать один раз на backspace, то в поле должны остаться "+7 "

# Чек лист
- [ ] Тесты
- [ ] Макеты
- [ ] Документация

# API

| Свойство     |                Описание                |    Тип    | Значение по умолчанию | Обязательное |
|--------------|:--------------------------------------:|:---------:|:---------------------:|-------------:|
| ...restProps | `Omit<MaskedInputProps, 'onBeforeDisplay' \| 'type'>`                           | object    |                    {} |          нет |

# Технические требования

- `React.forwardRef` (есть возможность пробросить ссылку на input через аргументы)

# Дополнительная информация
У аналогичного [компонента](https://alfabank.ru/api/akit/?path=/story/forms-hundreddaysform-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B--phone) сайта в поле всегда присутствует "+7 (", которое удалить невозможно.

**Comment by stepancar** [comment]
2.4) - форматируется в +7 - это требование откуда?

**Comment by riggs84** [comment]
А как отреагирует инпут на ввод +7 ?

**Comment by aleksey-ilin** [comment]
> 2.4) - форматируется в +7 - это требование откуда?

не помню, думаешь лучше его удалить?

**Comment by aleksey-ilin** [comment]
> А как отреагирует инпут на ввод +7 ?

если имеется ввиду ввод, а не вставка, то после ввода + в поле будет "+7 ", если потом ввести 7, то в поле будет "+7 7"

**Comment by riggs84** [comment]
Алексей, а это точно было в требованиях? "если вставляется номер телефона длиннее маски, то лишнее обрезать"

**Comment by aleksey-ilin** [comment]
> Алексей, а это точно было в требованиях? "если вставляется номер телефона длиннее маски, то лишнее обрезать"

как такового ТЗ на разработку компонента нет, поэтому требования собирались в основном группой заинтересованных людей. поэтому в описании к issue это то, что нам удалось собрать, что то я сам придумал

**Comment by SiebenSieben** [comment]
Да, 2.4 и 2.5 не очень понятно откуда

**Comment by aleksey-ilin** [comment]
> Да, 2.4 и 2.5 не очень понятно откуда

ок, удаляю оба

**Comment by aso1datov** [comment]
А у нас обязательна такая жесткая привязка к +7? Мы не рассматриваем кейсы когда нужен +8, к примеру?

**Comment by aleksey-ilin** [comment]
> А у нас обязательна такая жесткая привязка к +7? Мы не рассматриваем кейсы когда нужен +8, к примеру?

этот компонент только для российских номеров. у дизайнера спрашивал, ответила: "международный это отдельный компонент, я не закладывала такую логику"

**Comment by aleksey-ilin** [comment]
вариант фоматирования 3.5) 7772223344 -> +7 777 222-33-44 заменил на 3.5) 71112223344 -> +7 111 222-33-44, потому что номер телефона не может начинаться на 7

**Comment by aleksey-ilin** [comment]
есть предложение от @reme3d2y убрать пункт 2.3) + форматируется в +7.

> Например, я хочу ввести номер +7 999 000-00-00 не глядя на экран.
Кажется, что все должно быть ок, но сейчас получится +7 799 900-00-00

**Comment by reme3d2y** [comment]
> есть предложение от @reme3d2y убрать пункт "2.3) + форматируется в +7".
> 
> > Например, я хочу ввести номер +7 999 000-00-00 не глядя на экран.
> > Кажется, что все должно быть ок, но сейчас получится +7 799 900-00-00

не совсем убрать. Пока вводим то, что уже подставилось в поле - ничего не должно меняться.

1. Вводим + → подставляется "+7 "
2. Вводим 7 → ничего не меняется, в поле остается "+7 "

**Comment by aleksey-ilin** [comment]
> > есть предложение от @reme3d2y убрать пункт "2.3) + форматируется в +7".
> > > Например, я хочу ввести номер +7 999 000-00-00 не глядя на экран.
> > > Кажется, что все должно быть ок, но сейчас получится +7 799 900-00-00
> 
> не совсем убрать. Пока вводим то, что уже подставилось в поле - ничего не должно меняться.
> 
>     1. Вводим + → подставляется "+7 "
> 
>     2. Вводим 7 → ничего не меняется, в поле остается "+7 "

тогда если код будет начинаться на 7, то человек не сможет свой номер телефона ввести
