### ISSUE TITLE
Добавить компонент ProgressBar

### ISSUE THREAD

**Issue by lisovskyR** [alfa-laboratory/core-components#195]
# Описание
Предлагаю добавить компонент ProgressBar(LinearProgressBar)

# Поведение
Представляет собой элемент-полоску, часть которой может быть закрашена определенным цветом.

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид
Пока есть такой драфтовый вариант, который нужно доработать и добавить больше вариантов поведения: 
<img width="1031" alt="Screenshot 2020-07-08 at 18 13 24" src="https://user-images.githubusercontent.com/37869104/86936504-c37f6900-c146-11ea-8548-741bf99c5bd7.png">

# Технические требования

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Уже существует два реализованных компонента, один из которых в целом похож на то, что я пока сделал:
https://digital.alfabank.ru/components/progressbar
https://alfabank.ru/api/akit/?path=/story/components-feedback-progressbar--default-story

Варианты улучшений/абстракций, которые можно добавить:
- поменять название пропса filledPercent на value
- отключение/включение скругления
- изменяемая высота (в пикселях или майках)
- больше вариантов с цветом (фиксированый набор цветов или код цвета)
- кастомный цвет бекграунда (либо вариант с прозрачным бекграундом и бордером)
- анимация заполнения
- буферизация и "бесконечный"/загрузочный вариант, как здесь - https://material-ui.com/ru/components/progress
- лейбл с текстовым значением процента заполнения

**Comment by stepancar** [comment]
"value" - я бы предложил взять название value как это сделано в https://material-ui.com/ru/components/progress
"color" - в этой библиотеке для такого используется variant

**Comment by SiebenSieben** [comment]
Я тоже за value, а variant в этой библиотеке нет, есть view.

Значения view лучше positive/negative (сейчас такой нейминг цветов).

Вероятно, есть смысл сразу предусмотреть второй ползунок (как в [akit](https://alfabank.ru/api/akit/?path=/story/components-feedback-progressbar--default-story), он нужен на сайте и в анкетах) и анимацию (width transition).

**Comment by stepancar** [comment]
@SiebenSieben поможешь с макетами?  У нас есть только вариаент для нового клика
