### ISSUE TITLE
Систематизация процесса разработки компонента

### ISSUE THREAD

**Issue by SiebenSieben** [alfa-laboratory/core-components#202]
Согласование требований, дизайна и имплементации компонента — сложный и длительный процесс.

Предлагаю ввести стейджи, которые помогут понимать статус компонента и упростят принятие решения о готовности к внедрению.

Стейдж | Статус | Критерии
--- | --- | ---
0 | Proposal | Issue с требованиями, может соответствовать требованиям только одного продукта
1 | Draft | Реализованный опубликованный компонент, может соответствовать требованиям только одного продукта
2 | Candidate Recommendation | Компонент, соответствующий требованиям ключевых продуктов, прошёл [полный процесс сбора и согласования требования](http://confluence.moscow.alfaintra.net/pages/viewpage.action?pageId=387658586)
3 | Proposed Recommendation | Компонент с хорошо описанной документацией, примерами использования, покрыт тестами, готов к внедрению
4 | Recommendation | Компонент, протестированный хотя бы в двух продуктах, рекомендован к внедрению

**Comment by aleksey-ilin** [comment]
1) в (Порядок добавления нового компонента)[http://confluence.moscow.alfaintra.net/pages/viewpage.action?pageId=387658586] есть такой пункт:

> 5. Реализовать компонент с учётом согласованных требований и открыть PR (компонент, тесты, документация с примерами).

а в статусах "тесты, документация с примерами" появляются только на предпоследней стадии. может изначально следовать требованиях добавления новых компонентов с тестами и документацией?

2) если предполагается что по этим статусам можно будет понять на какой стадии находится компонент, то предлагаю для компонентов, которые выбились из графика и долго не смерживаются добавлять комментарий почему работа по ним приостановлена

**Comment by SiebenSieben** [comment]
> а в статусах "тесты, документация с примерами" появляются только на предпоследней стадии. может изначально следовать требованиях добавления новых компонентов с тестами и документацией?

Да, не хватает. Тесты и доки нужны и для Draft. Для Proposed Recommendation — повышенные требования к докам (примеры использования) и к тестам (например, скриншот-тесты). Это как вариант снижения порога для драфта.

А может Proposed Recommendation вообще лишний, и всё это критерии для Recommendation. Склоняюсь к такому варианту, убрать один стейдж.

> 2) если предполагается что по этим статусам можно будет понять на какой стадии находится компонент, то предлагаю для компонентов, которые выбились из графика и долго не смерживаются добавлять комментарий почему работа по ним приостановлена

👍🏻
