### ISSUE TITLE
Новый компонент <Autocomplete/>

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#206]
# Описание
Предлагаю добавить компонент `<Autocomplete/>` — селект с возможностью ввода.

[Демка с реализацией](https://alfa-laboratory.github.io/core-components/888f4bd3e09bbba4d7b1c0fa913919ab3f097c54/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-autocomplete--%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0)

# Внешний вид

Выглядит, как обычный селект, но вместо поля по умолчанию используется `<Input />`

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=719%3A0

# API

Апи и поведение сходно с селектом, за исключением пары моментов.

[BaseSelectProps](https://alfa-laboratory.github.io/core-components/835958d2efd996f379d57ca1b73eb9b6bb4713f9/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-select--%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0)

```
export type AutocompleteProps = Omit<BaseSelectProps, 'Field' | 'nativeSelect'> & {
    /**
     * Компонент ввода значения
     */
    Input?: FC<InputProps>;

    /**
     * Обработчик ввода
     */
    onInput?: (event?: React.ChangeEvent) => void;

    /**
     * Значение поля ввода
     */
    value?: string;
};
```

# Текущая реализация:

**Потребовались некоторые доработки, поэтому открыт [другой PR с рефакторингом](https://github.com/alfa-laboratory/core-components/pull/204).**

В текущем [PR](https://github.com/alfa-laboratory/core-components/pull/205) `<Autocomplete />` представляет из себя обертку над `<BaseSelect Field={<Input />} />`.
Логика фильтрации вынесена наружу, примеры можно посмотреть в [демке](https://alfa-laboratory.github.io/core-components/888f4bd3e09bbba4d7b1c0fa913919ab3f097c54/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-autocomplete--%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0)

Пример использования:

```tsx
const [value, setValue] = React.useState('');

const handleInput = event => setValue(event.target.value);

const handleChange = (event, payload) => {
    setValue(payload.selected ? payload.selected.text : '');
};

const filteredOptions = options.filter(option => option.text.toLowerCase().startsWith(value.toLowerCase()));

return (
    <Autocomplete
        options={filteredOptions}
        onChange={handleChange}
        onInput={handleInput}
        value={value}
    />
);
```

**Comment by SiebenSieben** [comment]
Multiple должен работать? Планируется?
Есть кнобс, но не работает
