### ISSUE TITLE
Определение фокуса с клавиатуры

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#213]
По дизайн-системе все интерактивные элементы должны иметь определенную обводку при фокусе, но только при переключении с клавиатуры. При клике мышки обводки быть не должно.

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=4165%3A8950

<img src="https://user-images.githubusercontent.com/9968618/89025107-e9a3bd80-d32e-11ea-9dc5-9c9f68ada16a.png" width="320" />

Предлагаю обсудить возможные варианты, как это лучше реализовать. 

### 1. Полифил https://github.com/WICG/focus-visible

Минусы:
- придется либо подключать его на проекте, либо импортировать в каждом компоненте (по идее не должно вызвать проблем)
- фокус применяется к активному элементу, что не совсем удобно. Например в кейсе, когда рамку нужно показать вокруг всего компонента, а не вокруг активного (чекбоксы, свитчи и пр.)

### 2. https://github.com/ten1seven/what-input

Минусы:
- Сбрасывается фокус при touchmove
- Слишком много лишнего

### 3. https://github.com/dipunm/use-focus-visible (код из полифила обернутый в хук)

Минусы:
- Нужно подключать компонент-провайдер

### 4. Свой хук https://codesandbox.io/s/usekeyboardfocus-0u2ko

При первом импорте он вешает на документ обработчики `keydown` и `mousedown` и запоминает последний ивент.  При фокусе, если последний ивент был с клавиатуры, то считает, что элемент был выбран с клавиатуры

Минусы:
- нужно вешать обработчики фокуса и блюра на интерактивный элемент

**Comment by dmitrsavk** [comment]
а тот вариант, который в уже закрытом PR, вообще не подошел для инпутов? как там вообще выглядел фокус с инпутом?

**Comment by reme3d2y** [comment]
> а тот вариант, который в уже закрытом PR, вообще не подошел для инпутов? как там вообще выглядел фокус с инпутом?

Ага, от того варианта пришлось отказаться, т.к. там обязательно должен быть вложенный элемент, что с инпутом сделать невозможно.

**Comment by jkikksa** [comment]
постоянно пользовался первым вариантом и очень доволен. кажется, что для проблемы применения фокуса к активному элементу можно попробовать скомбинировать с селектором focus-within

**Comment by reme3d2y** [comment]
> постоянно пользовался первым вариантом и очень доволен. кажется, что для решения проблемы применения фокуса к активному элементу можно попробовать скомбинировать с селектором focus-within

к сожалению, focus-within в IE11 не поддерживается. Он бы помог)

**Comment by SiebenSieben** [comment]
Я за четвёртый вариант

**Comment by reme3d2y** [comment]
Допилил хук и компонент для четвертого пункта. Получилось именно то, что нужно

https://github.com/alfa-laboratory/core-components/pull/215

**Comment by reme3d2y** [comment]
Добавили хук `useFocus` в https://www.npmjs.com/package/@alfalab/hooks
