### ISSUE TITLE
Компонент Typography

### ISSUE THREAD

**Issue by NatalyaZ** [alfa-laboratory/core-components#214]
# Описание
Предлагаю добавить компонент `Typography`, который будет содержать компоненты `Title` и `Text`. 

Компонент `Typography.Title` будет отображать контент заголовками `<h1>`-`<h6>`, а также допускать рендер в `div` и `span`. Шрифт по умолчанию - Styrene.

Компонент `Typography.Text` нужен для текстовых блоков. Позволяет задать тэг, в котором будет отображен текст через параметр `tag='p' | 'span' | 'div'`.

Для указания начертания шрифта предлагаю использовать строковый параметр `view`, значения которого формируются из названия шрифтов в макете. Например, для текста `Paragraph / 18–24 Primary Large` `view` будет равен `primary-large`.

Компоненты позволяют управлять цветом текста с помощью параметра `color`, который соответствует цветам из [новой палитры](https://www.figma.com/file/TM85e2Xex9QkKg3pJhF3TX/2020-Indigo-Colors?node-id=28%3A1003)

Толщина шрифта задается параметром `weight = 'regular' | 'medium' | 'bold'`

Шрифт для заголовков задается с помощью `font = styrene | system`

# Чек лист
- [ ] Обсуждение
- [ ] Документация
- [ ] Реализация
- [ ] Тесты

# Внешний вид
https://www.figma.com/file/FWya6P55TnXkiVGaM2qBio/2020-Web-Hybrid-Typography?node-id=593%3A0

# API
```
export type Color =
    | 'tertiary'
    | 'disabled'
    | 'accent'
    | 'primary'
    | 'attention'
    | 'positive'
    | 'secondary'
    | 'tertiary-inverted'
    | 'primary-inverted'
    | 'secondary-inverted'
    | 'link'
    | 'negative';


export type TextProps = {
    /**
     * Вариант начертания
     */
    view?:
        | 'primary-large'
        | 'primary-normal'
        | 'primary-small'
        | 'secondary-large'
        | 'secondary-normal'
        | 'secondary-small';

    /**
     * Цвет текста
     */
    color?: Color;

    /**
     * Толщина шрифта
     */
    weight?: 'regular' | 'medium' | 'bold';

    /**
     * HTML тег
     */
    tag?: 'p' | 'span' | 'div';

    /**
     * Css-класс для стилизации
     */
    className?: string;

    /**
     * Id компонента для тестов
     */
    dataTestId?: string;

    /**
     * Контент
     */
    children?: React.ReactNode;
};


export type TitleProps = {
    /**
     * HTML тег
     */
    tag?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'div';

    /**
     * Вариант начертания
     */
    view?: 'xlarge' | 'large' | 'normal' | 'small' | 'xsmall';

    /**
     * Цвет текста
     */
    color?: Color;

    /**
     * Толщина шрифта
     */
    weight?: 'regular' | 'medium' | 'bold';

    /**
     * Шрифт текста
     */
    font?: 'styrene' | 'system';

    /**
     * Css-класс для стилизации
     */
    className?: string;

    /**
     * Id компонента для тестов
     */
    dataTestId?: string;

    /**
     * Контент
     */
    children?: React.ReactNode;
};

```

# Дополнительная информация
Текущая реализация в [arui-feather|Heading](https://alfa-laboratory.github.io/arui-feather/styleguide/#/Heading) и [arui-feather|Paragraph](https://alfa-laboratory.github.io/arui-feather/styleguide/#/Paragraph)

**Comment by SiebenSieben** [comment]
1. Heading разделим на два компонента?

Например, Heading и HeadingClassic.

(Стили переименовали headline-styrene/headline-system → headline/headline-classic, чтобы в названии не было привязки к шрифту и было проще менять в будущем.)

2. Получается, для стилей типа paragraph-primary-normal/action-primary-normal/accent-primary-normal будут разные view?

Они отличаются только font-weight, и отдельный view для каждого утяжеляет компонент.

**Comment by denisx** [comment]
В команде сайта реализую такие компоненты:

Text
содержит размеры текущей и прошлой сетки, отдельными пропсами. 
коммон (без деления десктоп / мобайл)
несколько популярных цветов (базовые для темы + несколько отдельных kind, часть из низ зависят от темы - добаляют полупрозрачность, часть глобальные, типа продающего красного)
font-size (с 12 до 48, с разными шагами, 1, 2, потом реже. 13 значений)
три line-height (1.2, 1.3, 1.4)
font-weight (c 300 по 700)
Tag для сео - p/span/h1-h5
пропс инлайн для сброса всех классов (нужен для комбинирования разных размеров внутри единого <h1>)

внешние отступы через Styler (глобальный хок)
через DI заменяет собой компонент Strong

Font-Styrene - прокидывает переопределяющие классы для фонта в чилды

Text-Lines - хок над Text для выдерживания кол-ва заданных строк на экране, нужно для использования в соседних карточках по горизонтали

Давайте обсудим )

**Comment by SiebenSieben** [comment]
@denisx 

Про цвета расскажи подробнее, пожалуйста. Какие нужны? Тема в данном случае это что?

13 значений font-size это какие? Они соответствуют типографике в фигме?

Красивые line-height 1.2/1.3/1.4 не подойдут: текст будет отличаться от фигмы, и в фигме в пикселях — придётся каждый раз считать.

---

В дизайн-системе/фигме предусмотрен определённый набор текстовых стилей, которые будут использоваться во всех макетах. Хочется максимально упростить процесс для фронта: выделил текстовый элемент в фигме → увидел название → написал одну/две пропсы и получил текст с нужными стилями.

А ты предлагаешь универсальный конструктор, непонятно зачем.
Если есть уверенность, что он будет востребован, может сделать для этого отдельный компонент?
Но такой компонент тоже должен соответствовать дизайн-системе.

**Comment by YozhEzhi** [comment]
> Компонент Typography.HeadingClassic будет отображать контент заголовками <h1>-<h5>. Шрифт для этих заголовков будет системным.
> 
> Компонент Typography.Heading будет отображать контент заголовками <h1>-<h5>. Шрифт для этих заголовков будет Styrene UI.

Я бы назвал:
— Typography.Heading  — Шрифт для этих заголовков будет системным.
— Typography.HeadingStyrene — Шрифт для этих заголовков будет Styrene UI

Имхо, выделять что-то стандартное\классическое — лишнее.

А HeadingStyrene точно показывает по названию, чем именно отличается этот компонент.

**Comment by YozhEzhi** [comment]
@NatalyaZ А можно в описание добавить примеры кода будущих компонентов, пожалуйста?

Меня смущает заполнение пропса view. Хочу точно увидеть как это будет выглядеть для прикладного пользователя.

**Comment by SiebenSieben** [comment]
> Я бы назвал:
> — Typography.Heading — Шрифт для этих заголовков будет системным.
> — Typography.HeadingStyrene — Шрифт для этих заголовков будет Styrene UI
> 
> Имхо, выделять что-то стандартное\классическое — лишнее.
> 
> А HeadingStyrene точно показывает по названию, чем именно отличается этот компонент.

Там была долгая история нейминга )

Heading — основной дефолтный заголовок (сайт/клик). Сейчас в заголовках шрифт Styrene, но когда-то это изменится и не хочется завязываться на шрифт в названии.

При этом часть продуктов (например, ниб) какое-то время продолжат использовать заголовки с системным шрифтом и старыми размерами. Пробовали назвать их Legacy/System, но остановились на более нейтральном Classic (такое название уже есть в иконках).

И в компонентах стараемся использовать названия из фигмы, там сейчас Classic.

**Comment by YozhEzhi** [comment]
> Heading — основной дефолтный заголовок (сайт/клик)

На Сайте стайрина мало, если что.

![image](https://user-images.githubusercontent.com/2706062/89429360-1fd5a880-d746-11ea-83b8-c06dee92c66c.png)

**Comment by SiebenSieben** [comment]
Пока мало. Компонент для того что будет )

**Comment by denisx** [comment]
@SiebenSieben 
>Про цвета расскажи подробнее, пожалуйста. Какие нужны? 

сейчас там стандартные белый и индиго, + полупрозначный из них двоих, и красный

>Тема в данном случае это что? 

тема это светлая-темная

>13 значений font-size это какие? Они соответствуют типографике в фигме? 

да, + часть старых значений, для миграции

>Красивые line-height 1.2/1.3/1.4 не подойдут: текст будет отличаться от фигмы, и фигма показывает в пикселях — придётся каждый раз считать.

через алиасы вычислений попробую. внутри компонента уже выбирать ближайший. в подавляющем большинстве выходит попиксельное совпадение.

>В дизайн-системе/фигме предусмотрен определённый набор текстовых стилей, которые будут использоваться во всех макетах. Хочется максимально упростить процесс для фронта: выделил текстовый элемент в фигме → увидел название → написал одну/две пропсы и получил текст с нужными стилями.

конечно

>А ты предлагаешь универсальный конструктор, непонятно зачем.

вполне понятно зачем. текущий компонент содержит много мусора и им неудобно пользоваться. новый содержит минимальное кол-во стилей, но им можно заменить и будущие и устаревшие компоненты

>Если есть уверенность, что он будет востребован, может сделать для этого отдельный компонент?

может и так

>Но такой компонент тоже должен соответствовать дизайн-системе.

дизайн-системе должны соответствовать макеты дизайнеров

**Comment by stepancar** [comment]
А почему отошли от size?

**Comment by stepancar** [comment]
Для чего нужны прямо в компоненте inverted цвета? это должно переключаться родителем, разве нет?

**Comment by SiebenSieben** [comment]
> А почему отошли от size?

Size нужно запоминать, неудобно. В фигме его нет.

**Comment by stepancar** [comment]
@SiebenSieben , все компоненты построены на понятии size, а тут тот же вроде сайз, но называется secondary-normal
secondary-large хотя вроде если просто сохраняеть концепцию это view="secondary" size="m"

**Comment by reme3d2y** [comment]
> Для чего нужны прямо в компоненте inverted цвета? это должно переключаться родителем, разве нет?

Кажется, что стоит оставить возможность поставить любой цвет из доступных.

> А почему отошли от size?

Дизайнеры в новой типографике отказались от size в пользу чуть более осмысленных названий. И чтобы не было расхождений, в компонентах используется `view` вместо `size`.
Плюс, так будет чуть проще верстать, т.к. можно будет копипастить название стиля, а не угадывать размер.

**Comment by etroynov** [comment]
Вставлю от себя пару копеек:
- мне не нравится разделение на HeadingClassic и Heading т.к это дикий оверхэд и мне кажется это можно решить или пропсами или наследованием, но заводить отдельный компонент это ИМХО слишком;
- название Heading не раскрывает суть компонента если про Text все ясно то про Heading не понятно ( это header или может h1, h2, а может это какая то хитрая обертка с header и h1). Title звучит более понятно;
- использование:
```
    view?: 'xlarge' | 'large' | 'normal' | 'small' | 'xsmall';
```
Абсолютно бессмысленно т.к в макетах используется маркировка по типу:
<img width="160" alt="Screenshot 2020-08-10 at 18 22 19" src="https://user-images.githubusercontent.com/4591518/89799956-cb13a280-db36-11ea-8a90-88f47a82d5ef.png">

таким образом мне нужно постоянно держать в голове сетку что бы знать что 16-20 это xsmall( например ), а ходить постоянно на макет с типографикой для того чтобы проверить прав я или нет это глупо. Предлагаю либо дизайнерам заменить именования во всех макетах, либо изменить пропсу следующим образом:
```
<Text size="16-20" variant="bold" />
```
Что является более наглядным использованием.

**Comment by reme3d2y** [comment]
> * мне не нравится разделение на HeadingClassic и Heading т.к это дикий оверхэд и мне кажется это можно решить или пропсами или наследованием, но заводить отдельный компонент это ИМХО слишком;

Тут основная проблема в том, что хоть названия view и одинаковые, но помимо шрифта стили отличаются ещё и размерами

Если добавлять параметр в один компонент, то получится оверхед для тех, кому не нужен стайрин или наоборот нужен только он. 

Плюс от названия шрифта в названии компоненты решили отказаться, т.к он может измениться со временем 

Да, решение не самое элегантное, но есть много нюансов 🤷‍♂️ Можно попробовать улучшить 

> * название Heading не раскрывает суть компонента если про Text все ясно то про Heading не понятно ( это header или может h1, h2, а может это какая то хитрая обертка с header и h1). Title звучит более понятно;

Ага, мне Title тоже больше нравится 


> * использование:
> 
> ```
>     view?: 'xlarge' | 'large' | 'normal' | 'small' | 'xsmall';
> ```
> 
> Абсолютно бессмысленно т.к в макетах используется маркировка по типу:
> <img alt="Screenshot 2020-08-10 at 18 22 19" width="160" src="https://user-images.githubusercontent.com/4591518/89799956-cb13a280-db36-11ea-8a90-88f47a82d5ef.png">

В новых макетах как раз отказываются от указания размеров в пользу view из новой типографики

**Comment by etroynov** [comment]
> В новых макетах как раз отказываются от указания размеров в пользу view из новой типографики
А есть информация когда это произойдет?

**Comment by etroynov** [comment]
> Тут основная проблема в том, что хоть названия view и одинаковые, но помимо шрифта стили отличаются ещё и размерами

а можно пример? мне кажется это можно решить через классы

**Comment by etroynov** [comment]
> Плюс от названия шрифта в названии компоненты решили отказаться, т.к он может измениться со временем

поэтому кажется что пропса более удобное решение.

**Comment by reme3d2y** [comment]
> > Тут основная проблема в том, что хоть названия view и одинаковые, но помимо шрифта стили отличаются ещё и размерами
> 
> а можно пример? мне кажется это можно решить через классы

<img src="https://user-images.githubusercontent.com/9968618/89862727-3bf7a080-dbb1-11ea-9901-6613a664e377.png" width="480" />

view один и тот же, а размеры и интерлиньяж везде разный. Плюс шрифт другой. 
Если есть идеи, как это уместить в одном компоненте - welcome)

Можно конечно в зависимости от шрифта подставлять классы из нужного набора стилей:
```tsx
// system
<Heading font="system" view="xlarge" />

// styrene
<Heading view="xlarge" />
```

но тогда компонент станет в два раза больше, т.к. будет содержать оба набора стилей. Возможно, этим можно пренебречь 🤷‍♂️

**Comment by SiebenSieben** [comment]
> Title звучит более понятно

Title тоже нравится, но нужна голосовалка.

> `<Heading font='system' view='xlarge' />`

С одной стороны смущает system, т.к. обсуждают отказ от системных шрифтов, но classic смущает ещё больше )

> но тогда компонент станет в два раза больше

Не настолько, понять бы реальную стоимость.

>> В новых макетах как раз отказываются от указания размеров в пользу view из новой типографики

> А есть информация когда это произойдет?

Новая типографика уже принята, в новых макетах должны использовать (Клик уже, другие ждут готовности кор-компонента).

**Comment by reme3d2y** [comment]
Голосовалка №1

## Heading --> Title 

За - 🚀
Против - 👎

**Comment by reme3d2y** [comment]
Голосовалка №2

## Объединяем Heading и HeadingClassic
- добавляем пропсу `font?: 'styrene' | 'system'`
```tsx
// defaultProps
font = 'styrene',
weight = font === 'styrene' ? 'medium' : 'bold'
```

За - 🚀
Против - 👎

**Comment by reme3d2y** [comment]
Голосовалка №3

## Добавить пропсы fontSize и lineHeight

 для возможности вывести текст\заголовок любого размера.

> Мне кажется, что это не ок, т.к. мы все-таки дизайн-систему делаем. Но мы не в идеальном мире живем, в макетах всякое бывает.

За - 🚀
Против - 👎

**Comment by etroynov** [comment]
> > Title звучит более понятно
> 
> Title тоже нравится, но нужна голосовалка.
> 
> > `<Heading font='system' view='xlarge' />`
> 
> С одной стороны смущает system, т.к. обсуждают отказ от системных шрифтов, но classic смущает ещё больше )
> 
> > но тогда компонент станет в два раза больше
> 
> Не настолько, понять бы реальную стоимость.
> 
> > > В новых макетах как раз отказываются от указания размеров в пользу view из новой типографики
> 
> > А есть информация когда это произойдет?
> 
> Новая типографика уже принята, в новых макетах должны использовать (Клик уже, другие ждут готовности кор-компонента).

ага цвета уже в макетах заюзали, а в либе их еще нету :(

**Comment by etroynov** [comment]
> > > Title звучит более понятно
> > 
> > 
> > Title тоже нравится, но нужна голосовалка.
> > > `<Heading font='system' view='xlarge' />`
> > 
> > 
> > С одной стороны смущает system, т.к. обсуждают отказ от системных шрифтов, но classic смущает ещё больше )
> > > но тогда компонент станет в два раза больше
> > 
> > 
> > Не настолько, понять бы реальную стоимость.
> > > > В новых макетах как раз отказываются от указания размеров в пользу view из новой типографики
> > 
> > 
> > > А есть информация когда это произойдет?
> > 
> > 
> > Новая типографика уже принята, в новых макетах должны использовать (Клик уже, другие ждут готовности кор-компонента).
> 
> ага цвета уже в макетах заюзали, а в либе их еще нету :(

**Comment by etroynov** [comment]
> Голосовалка №3
> 
> ## Добавить пропсы fontSize и lineHeight
> для возможности вывести текст\заголовок любого размера (из тех, что встречаются в макетах в фигме).
> 
> > Мне кажется, что это не ок, т.к. мы все-таки дизайн-систему делаем. Но мы не в идеальном мире живем, в макетах всякое бывает.
> 
> За - 🚀
> Против - 👎

если у меня будут такие пропсы мне этот компонент не нужен будет.

**Comment by reme3d2y** [comment]
> > Голосовалка №3
> > ## Добавить пропсы fontSize и lineHeight
> > для возможности вывести текст\заголовок любого размера (из тех, что встречаются в макетах в фигме).
> > > Мне кажется, что это не ок, т.к. мы все-таки дизайн-систему делаем. Но мы не в идеальном мире живем, в макетах всякое бывает.
> > 
> > 
> > За - 🚀
> > Против - 👎
> 
> если у меня будут такие пропсы мне этот компонент не нужен будет.

Это одно из предложений в issue, поэтому и голосуем ;)

**Comment by reme3d2y** [comment]
> если у меня будут такие пропсы мне этот компонент не нужен будет.

Это одно из предложений в issue, поэтому и голосуем ;)

**Comment by SiebenSieben** [comment]
> ага цвета уже в макетах заюзали, а в либе их еще нету :(

Новые цвета давно в core-components-vars, или ты о каких?

**Comment by etroynov** [comment]
> > ага цвета уже в макетах заюзали, а в либе их еще нету :(
> 
> Новые цвета есть в [core-components-vars](https://github.com/alfa-laboratory/core-components/blob/master/packages/vars/src/colors-indigo.css), или ты о каких? Скорее всего тут недостаток информирования

мой косяк была ошибка в макете :(

**Comment by etroynov** [comment]
> > ага цвета уже в макетах заюзали, а в либе их еще нету :(
> 
> Новые цвета есть в [core-components-vars](https://github.com/alfa-laboratory/core-

такой вопрос а обязательно везде использовать rgb с альфа каналом? Хотел бы напомнить что они хорошо бьют по производительности.

<img width="1008" alt="Screenshot 2020-08-12 at 10 38 32" src="https://user-images.githubusercontent.com/4591518/89988511-50f33300-dc88-11ea-9ce8-1f4354eb94b4.png">
https://jsperf.com/css-color-names-vs-hex-codes/25

**Comment by SiebenSieben** [comment]
> такой вопрос а обязательно везде использовать rgb с альфа каналом? Хотел бы напомнить что они бьют по производительности

Отдельным реквестом поменяем

**Comment by reme3d2y** [comment]
Обновил реквест с учетом голосовалок
