### ISSUE TITLE
Поиск решений для KeyboardFocusable

### ISSUE THREAD

**Issue by FenkoAlex** [alfa-laboratory/core-components#226]
# Описание
В [KeyboardFocusable](https://github.com/alfa-laboratory/core-components/pull/215/files#diff-566f02f360e29cd57f09787a3177eb9eR78)  используется NodeResolver для получения ссылки на элемент

# Технические требования
Нужно получить ссылку на children и повесить на этот элемент focusin, focusout.

# Другой вариант
Передавать ref в рендер функцию, в ней надо будет (возможно и нет, зависит от компонента) добавить обертку для ref

Накидайте, пожалуйста, еще возможные варианты решения

**Comment by reme3d2y** [comment]
В принципе, я не против варианта с рефом. 

```tsx
<KeyboardFocusable>
    {(ref, focused) => <button type='button' ref={ref} className={cn({ [styles.focused]: focused })} />}
</KeyboardFocusable>

<KeyboardFocusable>
    {(ref, focused) => <ForwardRefComponent ref={ref} className={cn({ [styles.focused]: focused })} />}
</KeyboardFocusable>

<KeyboardFocusable>
    {(ref, focused) => (
        <div ref={ref} className={cn({ [styles.focused]: focused })}>
            <ComponentWithoutRef />
        </div>
    )}
</KeyboardFocusable>
```

**Comment by FenkoAlex** [comment]
тогда KeyboardFocusable должен быть forwardref, а не всем компонентам надо будет иметь свой ref

**Comment by reme3d2y** [comment]
> тогда KeyboardFocusable должен быть forwardref, а не всем компонентам надо будет иметь свой ref

Это как? Можешь пример сделать?

Я убрал NodeResolver, теперь обертка выглядит так:
https://codesandbox.io/s/nostalgic-resonance-jbqnn?file=/src/App.tsx

**Comment by FenkoAlex** [comment]
KeyboardFocusable как будет использоваться, ты в компонент его поместишь? Вот есть Button из библиотеки, он сразу будет обернут в KeyboardFocusable?

**Comment by reme3d2y** [comment]
> KeyboardFocusable как будет использоваться, ты в компонент его поместишь? Вот есть Button из библиотеки, он сразу будет обернут в KeyboardFocusable?

Я пока единственное применение для обертки вижу в ситуации, когда компоненты на классах и хук заюзать не получится. В остальных кейсах хук и удобнее и проще применить. 

В кнопку добавил хук в реквесте https://github.com/alfa-laboratory/core-components/pull/229/files#diff-8ae34086e125cf8f41c7c625f3cab4aaR88

**Comment by reme3d2y** [comment]
https://github.com/alfa-laboratory/core-components/pull/215
