### ISSUE TITLE
Новый компонент Attach

### ISSUE THREAD

**Issue by Artess999** [alfa-laboratory/core-components#227]
# Описание
Предлагаю добавить новый компонент `<Attach/>`

# Чек лист
- [ ] Обсуждение
- [ ] Документация
- [ ] Реализация
- [ ] Тесты

# Внешний вид
В данный момент макетов нет, внешний вид должен быть аналогичен компоненту в arui-feather

# API

```tsx
export type AttachProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type' | 'value'> & {
    /**
     * Содержимое кнопки для выбора файла
     */
    buttonContent?: React.ReactNode;

    /**
     * Свойства для кнопки
     */
    buttonProps?: ButtonProps & ButtonHTMLAttributes<HTMLButtonElement>;

    /**
     * Дополнительный класс
     */
    className?: string;

    /**
     * Число символов, после которого имя файла будет обрезаться
     */
    maxFilenameLength?: number;

    /**
     * Текст для случая, когда файл не загружен
     */
    noFileText?: string;

    /**
     * Процент выполнения загрузки файла
     */
    progressBarPercent?: number;

    /**
     * Размер компонента
     */
    size?: 'xs' | 's' | 'm' | 'l';

    /**
     * Содержимое поля ввода, указанное по умолчанию. Принимает массив объектов типа File или null.
     */
    value?: File[] | null;

    /**
     * Идентификатор для систем автоматизированного тестирования
     */
    dataTestId?: string;
};

```

# Технические требования

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Текущая реализация в [arui-feather](https://digital.alfabank.ru/components/attach)

**Comment by reme3d2y** [comment]
buttonContent - наверное избыточен, если есть buttonProps. И ButtonHTMLAttributes<HTMLButtonElement> тогда тоже.

**Comment by Artess999** [comment]
> buttonContent - наверное избыточен, если есть buttonProps. И ButtonHTMLAttributes тогда тоже.

И правда, согласен

**Comment by Artess999** [comment]
Хотя нет - нужен
В пропах кнопки нет переменной, отвечающей за ее внутреннее содержание (не аддоны)
