### ISSUE TITLE
Как импортятся компоненты?

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#23]
Гайз. Для меня очень важный вопрос.

Текущая предложенная схема импортов в newclick-components

import { Button } from 'newclick-components'

собсно с core-components (если не говорим о мультипакетности)
import { Button } from 'core-components';

в arui-feather

import Button from 'arui-feather/button';

И я хочу пояснить почему мне это нравится (замечу что мне нравится не дефолтный импорт а именно 'arui-feather/button').
Это легко найти в коде. Искать это нужно будет в коде, когда через  год существования библиотеки ты понимаешь что все могло быть по другому - ты можешь найти юсаджи без хитростей, просто вот так arui-feather/button.
У нас микросервисы, 30 страниц - 30 реп. Это отличный способ искать и не писать какие-то хреновины, которые будут перелопачивать весь код и находить реальные юсаджи.

**Comment by YozhEzhi** [comment]
Не сложно оформить возможность импортировать и так, и так?

```
import { Button } from 'core-components';

import { Button } from 'core-components/button';
```

**Comment by Luchanso** [comment]
Можно сделать и так и так

**Comment by stepancar** [comment]
Ребят, так если будет и так и так - все будут конечно импортить

```
import { Button } from 'core-components';
```

Услышьте плиз про задачу нахождения юсаджей библиотеки компонентов.
В моем предыдущем опыте было овер 150 реп. Всего одна возможность легкого грепа давала мне возможность проанализировать места использования без написания специальных утилит. Я понимаю что с учетом старта либы это может быть не важно, но я прошу подумать, ибо сегодня у нее один юсадж - а завтра 100 человек начнут неистово комиитить.

**Comment by YozhEzhi** [comment]
> Ребят, так если будет и так и так - все будут конечно импортить
> 
> ```
> import { Button } from 'core-components';
> ```

Ну, мы на сайте используем "полный"  путь `import { Button } from 'core-components/button';`.

На тришейкинг надейся, но сам - не плошай (с)

**Comment by denisx** [comment]
делать надо как надо, а не как удобней

**Comment by stepancar** [comment]
@denisx а как надо?

**Comment by stepancar** [comment]
@YozhEzhi я собсно и не верю до сих пор в тришейкинг. На каком-то может одном проекте он сработает, а вот на всех ...

**Comment by 7rulnik** [comment]
@stepancar с тришейкингом вопросы сложные.

Если я правильно понимаю, то просто то регэксп для грепа/поиск по проекту усложняется, если особенно модули оформлены так:

```js
import {
   foo,
   bar,
} from 'lib-name'
```
Т.е. этот способ не исключает возможности найти нужный импорт, просто становится чуть сложнее.

Мне в целом  всё равно как импортить, но как мне кажется, важно, чтобы именованный экспорт остался. Когда используют дефолтный экспорт, то потом сложно рефакторить

**Comment by stepancar** [comment]
@7rulnik 
если импорт такой, то вообще никаких проблем грепать нет
```
import { Button } from 'core-components/button'
```

```
grep core-components/button
```
и полетели

**Comment by Luchanso** [comment]
@stepancar давай оставим `import { Button } from 'core-components/button'`? Все современные редакторы кода умеют находить ссылки в проектах.

VS Code, например, умеет выполнять ссылочные поиск по всем открытым проектам/папкам, так что не думаю, что это составит трудности + задача, о который ты пишешь встречается раз в год максимум

**Comment by Luchanso** [comment]
А вот дефолтный импорт можно написать неправильно, что и создаст тот случай, когда даже grep не поможет

`import Baton from 'arui-feather/button'`

**Comment by stepancar** [comment]
@Luchanso , ты предложил `import { Button } from 'core-components/button'`
я предлагаю его же

**Comment by denisx** [comment]
только не забыть cделать двойной экспорт - именованый и дефолтный. нужно для `loadable`

**Comment by Hydrock** [comment]
> Ребят, так если будет и так и так - все будут конечно импортить
> 
> ```
> import { Button } from 'core-components';
> ```
> 
> Услышьте плиз про задачу нахождения юсаджей библиотеки компонентов.
> В моем предыдущем опыте было овер 150 реп. Всего одна возможность легкого грепа давала мне возможность проанализировать места использования без написания специальных утилит. Я понимаю что с учетом старта либы это может быть не важно, но я прошу подумать, ибо сегодня у нее один юсадж - а завтра 100 человек начнут неистово комиитить.

Поддерживаю. Должен быть один корректный путь импортировать компонент.

**Comment by etroynov** [comment]
Вопрос спорный т.к предлагаемый подход несет в себе плюсы только в одном конкретном кейсе который может наступить, а может и не наступить. К тому же осложненный поиск использования компонентов данной библиотеки говорит о том что на проекте неправильная архитектура которая не контролируется линтом. В этом случае это не проблема библиотеки а проблема проекта. Решение проблем проектов с кривой архитектурой посредством библиотеки идея спорная.

Как человек который был на поддержке большого количества проектов я понимаю и поддерживаю Степу, но как человек который разрабатывает библиотеку я не согласен с этим.

поэтому предлагаю проголосовать.

Вариант 1:
```
import { Button } from 'core-components';
import { Button } from 'core-components/button';
```

Вариант 2:
```
import { Button } from 'core-components/button';
```

Вариант 3:
```
 import Button from 'core-components/button';
```

**Comment by denisx** [comment]
import { Button } from 'core-components/button';
+
import Button from 'core-components/button';

**Comment by etroynov** [comment]
> import { Button } from 'core-components/button';
> +
> import Button from 'core-components/button';

а зачем нужно 2 этих подхода сразу?

**Comment by denisx** [comment]
@etroynov из кода берем по варианту 2, а для loadable вариант 3
