### ISSUE TITLE
Предлагаю удалить в компоненте Typography.Title значение tag по умолчанию

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#233]
# Описание
Предлагаю удалить в компоненте Typography.Title значение tag по умолчанию

# Поведение
Считаю что необходимо заставлять разработчика явно указывать всегда.
```
<Typography.Title tag="h1">Hello</Typography.Title>
```
Сейчас можно забить на семантику. Обязательность этого параметра заставит задуматься разработчика

**Comment by etroynov** [comment]
я бы предложил вернуть level (1-5) для h1-5, а tag сделать опциональным при его явной необходимости.

**Comment by reme3d2y** [comment]
Обычно level отвечает в том числе и за внешний вид(размер) заголовка. Кажется, что level будет вводить в заблуждение, т.к у нас он влияет только на тэг, в котором будет отрисован текст. 
К тому же так будет две отдельные пропсы, которые будут отвечать за одно и то же.
