### ISSUE TITLE
Описать область применения компонента типографики

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#234]
# Описание
Описать область применения компонента типографики

# Поведение
При нажатии на кнопку должно появится модальное окно

Дело в том что компонент применис не везде. Если мы говорим об интерактивном элменете, в котором мы хотим добиться различных цветов на hover, то поскольку цвет мы будем устанавливать из css и по последним трендам хэто просветление базового, а цвет базового при компонентном подходе ставится параметром color - выглядит что система сломалась. Компонент типографики подходит вроде только в контекстах отображения

**Comment by reme3d2y** [comment]
Кажется, что это какой-то специфичный кейс и он должен решаться через css-класс и манипуляции с цветами, благо переменные цветов есть и названия ~ совпадают с пропсой color.

А каким еще образом можно решить данный кейс?
