### ISSUE TITLE
 Select отступы у айтема слева не по макету

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#241]
# Опишите проблему
Элементы селекта в кликовой теме имеют отступ не по макету

# Ожидаемое поведение
Все сделано по макету
<img width="1406" alt="Screen Shot 2020-08-25 at 18 56 15" src="https://user-images.githubusercontent.com/2854910/91198163-e371e880-e704-11ea-9dab-285d19c9097b.png">

**Comment by reme3d2y** [comment]
Причешем, я по макетам ниба делал, т.к. других не было
