### ISSUE TITLE
FormControll должен быть внутри селекта?

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#242]
# Опишите проблему
Не понятно как отобразить ошибку в селекте

Нужно явно вкладывать один в другой?  тогда нужно добавить пример

**Comment by reme3d2y** [comment]
Добавил пропсу error в селект и автокомплит. 
Остальные пропсы можно прокинуть в FormControl и Input с помощью `fieldProps` и `inputProps` (но это для каких-то сложных кейсов уже)
