### ISSUE TITLE
Предлагаю создать в vars файл с базовыми анимациями

### ISSUE THREAD

**Issue by aso1datov** [alfa-laboratory/core-components#257]
# Описание
Предлагаю шарить css-анимации, чтобы не создавать их заново в каждом проекте.

# Поведение
При надобности, можно подключить себе файлик с анимациями и использовать готовые.

**Comment by etroynov** [comment]
идея неплохая, но я думаю не в этой репе.

**Comment by aso1datov** [comment]
> идея неплохая, но я думаю не в этой репе.

Почему не в этой? Предлагаешь отдельную заводить?

**Comment by reme3d2y** [comment]
Норм, но хотелось бы увидеть список анимаций.
Они вообще сейчас есть и едины ли между продуктами?

Затащить в либу то не проблема, но кажется, что начинать эту историю лучше с другого конца)

**Comment by SiebenSieben** [comment]
Поддерживаю 👍

Часть анимаций важно/нужно выравнивать, и в планах было добавить рекомендуемые анимации/транзишены именно в core-components/vars.

**Comment by aso1datov** [comment]
Окей, тогда когда наберу какое-то кол-во анимаций приду с пр-ом
