### ISSUE TITLE
Крестик у инпутов и другие улучшения

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#261]
У клика все инпуты с крестиком, а у остальных нет. Также, на макетах был замечен инпут с тултипом при наведении. 
Отсюда вопрос - что делать с подобными плюшками?

![image](https://user-images.githubusercontent.com/9968618/92555297-00173000-f270-11ea-8f74-6a9a72c7e883.png)

### Вариант один
тупо добавить крестик в инпут. Но не тащить же и тултип туда? 

### Вариант два
сделать для этого хок. А в локальной либе клика, или другого продукта, сделать реэкспорт инпутов, применив этот хок. Получится что-то типа:
```tsx
import { Input as DefaultInput, withСlear, withTooltip } from '@alfalab/core-components-input';
import { MaskedInput as DefaultMaskedInput } from '@alfalab/core-components-masked-input';

export const Input = withTooltip(withСlear(DefaultInput));
...
export const MaskedInput = withTooltip(withСlear(DefaultMaskedInput));
```

Что думаете?

**Comment by dmitrsavk** [comment]
а через аддоны если?

**Comment by reme3d2y** [comment]
> а через аддоны если?

Это как? 
Хок и будет предустанавливать `rightAddons` у инпутов

**Comment by aso1datov** [comment]
Мне по душе вариант с хоком. Реэкспортить, похоже, в любом случае придется, т.к. у нас крестик всегда должен быть и постоянно этот пропс везде пропихивать будет запарно.

**Comment by raylyanway** [comment]
Я голосую за хок. Больше гибкости и вариативности.
А так конечно странно, что весь банк не стремится к единому виду.
Конечно лучше этот вопрос поднять на собрании, чтобы решение не вызывало реакции с изюминкой.))

**Comment by dmitrsavk** [comment]
Я имею ввиду в локальных либах делать это. Есть ли смысл тащить эти хоки в кор?

**Comment by reme3d2y** [comment]
> Я имею ввиду в локальных либах делать это. Есть ли смысл тащить эти хоки в кор?

Да, возможно стоит это в кликовой либе сделать

**Comment by SiebenSieben** [comment]
> Я голосую за хок. Больше гибкости и вариативности.
> А так конечно странно, что весь банк не стремится к единому виду.
> Конечно лучше этот вопрос поднять на собрании, чтобы решение не вызывало реакции с изюминкой.))

Банк стремится )

Тут пока больше локальная история, ещё не подкреплённая тестами (но не безосновательная, это важно).

**Comment by reme3d2y** [comment]
Через hoc сделать не получилось, пришлось добавить его в инпут

https://github.com/alfa-laboratory/core-components/pull/269
