### ISSUE TITLE
Компонент Skeleton

### ISSUE THREAD

**Issue by NatalyaZ** [alfa-laboratory/core-components#262]
# Описание
Предлагаю добавить компонент Skeleton

Скелетон используется в качестве прелоадера. Его можно использовать как отдельно, так и в качестве обертки над контентом. В компоненте закладывается базовое оформление скелетона: цвет, скругление углов, анимация.

Цвет и радиус скругления можно переопределить классом.

Анимацию включается параметром `animate`.

Если скелетон используется как обертка над контентом, то используется параметр `visible` для его отображения.

# Чек лист
- [x] Обсуждение
- [ ] Документация
- [ ] Реализация
- [ ] Тесты

# Внешний вид
Есть вариант https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=35%3A101. Но он в процессе редизайна
# API
```
type SkeletonProps = {
    /** Флаг, явно задающий состояние, при котором контент закрывается прелоадером */
    visible?: boolean;
    /** Флаг явного включения анимации скелета */
    animate?: boolean;
    /** Css-класс для стилизации */
    className?: string;
    /** Id компоента для тестов */
    dataTestId?: string;
    /** Контент */
    children?: ReactNode;
};
```
# Дополнительная информация
Есть реализации скелетонов в [arui-private](https://digital.alfabank.ru/demo/arui-private/#/Components/ThemedSkeletonLabel) и в [newclick-components](http://digital/demo/newclick-components/master/?path=/story/common-skeleton--basic)

**Comment by SiebenSieben** [comment]
Заложенные отступы точно нужны? Слишком много вариантов

**Comment by NatalyaZ** [comment]
> Заложенные отступы точно нужны? Слишком много вариантов

Можно и без них, конечно.

**Comment by Makvagabo** [comment]
получится использовать миксин типографский для скелетона вместо свойства view?

**Comment by NatalyaZ** [comment]
> получится использовать миксин типографский для скелетона вместо свойства view?

**Comment by NatalyaZ** [comment]
> получится использовать миксин типографский для скелетона вместо свойства view?

Кстати, да. Что-то не подумала про это. Попробую
