### ISSUE TITLE
Компонент List

### ISSUE THREAD

**Issue by NatalyaZ** [alfa-laboratory/core-components#263]
# Описание
Предлагаю добавить компонент `List`

Задача компонента показать оформленный список: маркированный или нумерованный. Указать, какой список нужен, предлагаю через параметр `tag: 'ul' | 'ol'`, по-умолчанию будет `ul`. _Ранее предлагала разделить на два компонента `List.Ordered` и `List.Unordered`._

Параметр `marker` может принимать `'a' | 'A' | '1'` для нумерованного списка, и `string | React.ReactNode` для ненумерованного. То есть для передачи картинки, символа или svg будет просто свой слот в ненумерованном списке, для нумерованного сработают только параметры нумерованного списка. _Ранее предлагала url на svg и изображение добавлять отдельным параметром._

Цвет маркера будет указан в css-переменной.

# Чек лист
- [x] Обсуждение
- [x] Документация
- [ ] Реализация
- [ ] Тесты

# API
```
type ListProps = {
     /** HTML тег */
    tag?: 'ul' | 'ol';
     /** Маркер  */
    marker?: 'a' | '1' | 'string' | ReactNode;
    /** Css-класс для стилизации */
    className?: string;
    /** Id компоента для тестов */
    dataTestId?: string;
    /** Контент */
    children?: ReactNode;
}
```

# Дополнительная информация
Компонент есть в демо [arui-feather](https://digital.alfabank.ru/components/list), [akit
](https://alfabank.ru/api/akit/?path=/story/components-datadisplay-lists--list) и в репозитории, но нет в демо в [newclick-components](http://git.moscow.alfaintra.net/projects/NEWCLICK/repos/newclick-components/browse/src/list)

**Comment by SiebenSieben** [comment]
Кажется, markerPosition это лишняя настройка, должен остаться один вариант, соответствующий дизайн-системе.

Также не уверен, что нужно так много вариантов настройки маркера для нумерованного списка.

И может не разделять на два компонента?

Вполне возможно, достаточно одного компонента, у которого будет:

* view/type (default|ordered);
* marker и markerImage, которые будут иметь приоритет, даже если список нумерованный.

**Comment by NatalyaZ** [comment]
> Вполне возможно, достаточно одного компонента, у которого будет:

Чтобы не использовать много проверок: что за компонент, какие параметры в приоритете -- подумала, что два компонента будет проще поддерживать

**Comment by denisx** [comment]
компонент лучше единый
приоритет пропсов и логику лучше не закладывать
