### ISSUE TITLE
Ошибка при прокидывании rest props в Button

### ISSUE THREAD

**Issue by Makvagabo** [alfa-laboratory/core-components#264]
# Опишите проблему
Хочу использовать Button в конкретном контексте, где нужно захардкодить параметр view, какие-то просто исключить, остальные свойства собираю в ..rest и передаю в Button.

# Шаги для воспроизведения
```tsx
import React from 'react';
import { Button, ButtonProps } from '@alfalab/core-components/button';

import { SuperEllipse } from '../super-ellipse';

export type SuperEllipseButtonProps = Omit<ButtonProps, 'view' | 'children'>

export const SuperEllipseButton: React.FC<SuperEllipseButtonProps> = ({ children, ...rest }) => {
    return (
        <Button view="ghost" {...rest}>
            <SuperEllipse>
                {children}
            </SuperEllipse>
        </Button>
    );
};
```

# Ожидаемое поведение
Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ошибок нет  ** | ** [Фактический](https://monosnap.com/file/Rs9I7MDBnPzHusrJ03LtNmq5nLYNoA)    **|

# Текущее решение рабочее
Хотелось бы лучше
```tsx
export type SuperEllipseButtonProps = Omit<
    Exclude<ButtonProps, ButtonHTMLAttributes<HTMLButtonElement>>,
    'view' | 'size' | 'children' | 'leftAddons' | 'rightAddons' | 'loading'
>;
```

**Comment by reme3d2y** [comment]
Пока что, можно заменить на ```<Button {...rest as ButtonProps} view="ghost">```

**Comment by denisx** [comment]
`rest` в целом неоч тема
