### ISSUE TITLE
Расположение Tooltip не по фигме

### ISSUE THREAD

**Issue by aleksey-ilin** [alfa-laboratory/core-components#287]
# Опишите проблему
Если компоненту Tooltip сделать правое расположение, а потом сузить окно, то тултип перескакивает налево, но в  [фигме](https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=8932%3A150) написано что он должен располагаться внизу в таком случае

**Comment by SiebenSieben** [comment]
Дизайнеры не против того как это сейчас работает в кор, им нужно поправить то самое описание в фигме

**Comment by aleksey-ilin** [comment]
Тогда закрываем issue, а дизайнеры правят описание?

**Comment by SiebenSieben** [comment]
Подскажи, пожалуйста, где сейчас это в фигме найти?

**Comment by aleksey-ilin** [comment]
[здесь](https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=3167%3A109)
