### ISSUE TITLE
Новый компонент SliderInput

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#289]
# Описание
Предлагаю добавить новый компонент `<SliderInput/>`.

Ориентировался на [akit](https://alfabank.ru/api/akit/iframe.html?id=components-inputs-sliderfield-default--desktop), но не стал добавлять логику в сам компонент.

Также, для реализации всех кейсов понадобятся доработки `AmountInput` и создание инпута с закрепленным значением.

# Чек лист
- [x] Обсуждение
- [x] Документация
- [x] Базовая реализация
- [x] Тесты

# Внешний вид

![image](https://user-images.githubusercontent.com/9968618/94679386-ab278080-0328-11eb-93bf-810c0015cbd6.png)

# API

```tsx

export type SliderInputProps = Omit<
    InputProps,
    'min' | 'max' | 'step' | 'value' | 'type' | 'onChange' | 'bottomAddons'
> & {
    /**
     * Мин. допустимое число
     */
    min?: number;

    /**
     * Макс. допустимое число
     */
    max?: number;

    /**
     * Шаг (должен нацело делить отрезок между мин и макс)
     */
    step?: number;

    /**
     * Массив подписей к слайдеру
     */
    steps?: ReactNode[];

    /**
     * Значение инпута
     */
    value?: number | string;

    /**
     * Значение слайдера
     */
    sliderValue?: number | string;

    /**
     * Дополнительная информация в правой части поля
     */
    info?: ReactNode;

    /**
     * Компонент поля ввода
     */
    Input?: FC<InputProps>;

    /**
     * Кастомные пропсы для поля ввода
     */
    customInputProps?: Record<string, unknown>;

    /**
     * Класс для инпута
     */
    inputClassName?: string;

    /**
     * Класс для слайдера
     */
    sliderClassName?: string;

    /**
     * Обработчик изменения значения через слайдер или поле ввода
     */
    onChange?: (event: ChangeEvent<HTMLInputElement>, payload: { value: string }) => void;

    /**
     * Обработчик ввода
     */
    onInputChange?: (event: ChangeEvent<HTMLInputElement>, payload: { value: string }) => void;

    /**
     * Обработчик изменения слайдера
     */
    onSliderChange?: (event: ChangeEvent<HTMLInputElement>, payload: { value: string }) => void;

    /**
     * Идентификатор для систем автоматизированного тестирования
     */
    dataTestId?: string;
};

```

**Comment by vamukhin** [comment]
имхо у слайдера одно значение, и на изменение этого значения должен быть один обязательный коллбек `onChange`. Другие же `onInputChange` и `onSliderChange` должны быть необязательными, чтобы программно определять как именно значение было изменено

**Comment by reme3d2y** [comment]
> имхо у слайдера одно значение, и на изменение этого значения должен быть один обязательный коллбек `onChange`. Другие же `onInputChange` и `onSliderChange` должны быть необязательными, чтобы программно определять как именно значение было изменено. Ну и в аргументах коллбеков разрешить использовать числа.
> 
> Пропсы min и max по все видимости должны быть обязательными, потому что у слайдера всегда есть границы

Насчет onChange - согласен, добавлю.

min, max есть дефолтные 0 и 100

**Comment by vamukhin** [comment]
видимо еще нужны `onBlur` и `onFocus` для инпута, чтобы нормально работало с форм-менеджерами

**Comment by reme3d2y** [comment]
> видимо еще нужны `onBlur` и `onFocus` для инпута, чтобы нормально работало с форм-менеджерами

Они уже есть в `InputProps`. В [демке](https://alfa-laboratory.github.io/core-components/3e8364e1a6aa813cabe2144c4d747e9a5f20b44f/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B--slider-input) есть примеры с `onBlur`
