### ISSUE TITLE
Перенести компонент Amount из arui-feather

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/core-components#3]
# Описание
Перенести компонент для отображения суммы Amount из arui-feather

# Поведение
Форматирует передаваемое значение по заданным правилам:
- отвечает только за форматирование не содержит стилей;
- минорная часть отображается всегда ( при отсуствии значения показывается , 00 например при 100 коп / 100 = 1p но показываем как 1, 00 р );
- по умолчанию используется валюта рубль;

# Чек лист
- [x] Тесты
- [x] Документация

# Темы
- [x] Базовая

# Внешний вид
https://digital.alfabank.ru/components/amount

# API
| Свойство          |           Описание           |   Тип   | Значение по умолчанию | Обязательное |
|-------------------|:----------------------------:|:-------:|:---------------------:|-------------:|
| value             |    форматируемое значение ( сумма в минимально допустимой единице валюты )    | number  |           -           |           да |
| currency          |   международный код валюты   | string  |           -           |           да |
| minority          |        число на которую делят сумму ( 100коп / 100 = 1р )        | number  |           -           |          да |
| view      |         | default | withZeroMinorPart; |         default         |          нет |
| className         |   присваивается контейнеру   | string  |           -           |          нет |

если withZeroMinorPart то отображаем копейки даже если они 00

# Технические требования
https://digital.alfabank.ru/patterns/amount

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
исходный код: https://github.com/alfa-laboratory/arui-feather/tree/master/src/amount
пример: https://digital.alfabank.ru/components/amount
Нужен режим без стилей

**Comment by stepancar** [comment]
```
       amount: Type.shape({
            /** Абсолютное значение суммы */
            value: Type.number,
            /** Валюта */
            currency: Type.shape({
                /** Международный код валюты */
                code: Type.string,
                /** Количество минорных единиц валюты */
                minority: Type.number
            })
        }).isRequired,
        /** Отображение минорной части, если она нулевая */
        showZeroMinorPart: Type.bool,
        /** Размер компонента */
        size: Type.oneOf(['s', 'm', 'l', 'xl']),
        /** Толщина шрифта */
        bold: Type.bool,
        /** Использовать компонент `Heading` для вывода числа */
        isHeading: Type.bool,
        /** Дополнительный класс */
        className: Type.string,
        /** Идентификатор компонента в DOM */
```
чего с этим не так?

**Comment by denisx** [comment]
Думается пропсы `size`, `bold` и `isHeading` нужно выносить отсюда в более высокоуровневый стейлер

**Comment by stepancar** [comment]
@etroynov что скажешь? вот по поводу bold, isHeading я еще согласен, а что по поводу size?

**Comment by SiebenSieben** [comment]
Нужен ли здесь size. Amount только форматирует по правилам, нужен большой размер — вложи в компонент текста большого размера.

А вот currency явно не хватает.

**Comment by denisx** [comment]
ещё есть непопулярное мнение, что пропсы должны стремится к простейшим, и всякие shape - не нужно юзать, по возможности. либо плоский компонент, либо сложный виджет с массивами данных. а там сверху ещё - уровень с логикой.
вот чего надо описывать - структуру взаимодействий. уровни иерархий.

**Comment by etroynov** [comment]
почему сразу непопулярное ? Наоборот за бугром оно очень популярное это у нас в РФ оно непопулярно. Я планирую в большей части компонентов перейти к плоскому Api.

**Comment by stepancar** [comment]
Пока смущает
1) название minorityClassName
2) и типы value и описание к минорным единицам

**Comment by SiebenSieben** [comment]
Раньше обходились без hideMinority, точно нужен?

И сомневаюсь, что нужен minorityClassName.

А так вроде ок.

**Comment by etroynov** [comment]
hideMinority это замена showZeroMinorPart но я решил его убрать т.к в большинстве случаев эта часть показывается, а редким кейсом является его скрытие.

minorityClassName - он нужен т.к у нас в макете мажорная и минорная часть имеют разный дизайн.

**Comment by SiebenSieben** [comment]
`showZeroMinorPart`
Эта пропса cкрывала минорную часть только если она нулевая.

`hideMinority`
 Вместо неё можно передать minority=1.

**Comment by stepancar** [comment]
@SiebenSieben да нет же. Minority - это количество коппеек в рубле, центов в доллере. То что ты предложил будет добавлять путанницу с суммами, а тут вопрос отображения

**Comment by SiebenSieben** [comment]
Согласен

**Comment by SiebenSieben** [comment]
Закрываем?

**Comment by etroynov** [comment]
Done.

**Comment by stepancar** [comment]
Вижу проблемы в именовании

'hideMinority'

Minority - это не то же самое что минорные единицы.
Пропса не отражает суть происходяещего.

Полностью покрывает суть showZeroMinorPart или hideZeroMinorPart

Предлагается ввести 
pure как это сделано в newclick-components
Тогда 
`minorityClassName` теряет смысл

**Comment by SiebenSieben** [comment]
Приложи ссылку на ньюклик-компонент, пожалуйста (чтобы посмотреть что такое `pure`)

**Comment by SiebenSieben** [comment]
Поддерживаю `showZeroMinorPart`

**Comment by SiebenSieben** [comment]
Не вижу смысла в `hideMinority`

**Comment by stepancar** [comment]
https://www.figma.com/file/9heKh2solfi1OWdr908rQE/%D0%94%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D1%8B?node-id=1789%3A15613

Прикладываю макет где можно увидеть все контексты

**Comment by stepancar** [comment]
showZeroMinorPart

**Comment by stepancar** [comment]
view = default | withoutZeroMinorPart;
12,34 full -> 12,34
12,00 withoutZeroMinorPart -> 12
12,34 short -> 12 ; 12,00 short -> 12 // можно будет добавить если будет необходимость

**Comment by stepancar** [comment]
Сравнили 3 подхода

1) Amount c пропсой pure
2) Amount и Amount.Pure
3) useAmount() хук - тут возник вопрос что хотелось бы чтобы Amount следил за тем чтобы сумма не переносилась на след строку

**Comment by stepancar** [comment]
выбрали второй вариант.

**Comment by stepancar** [comment]
Предлагаю назвать компонент Money

**Comment by SiebenSieben** [comment]
Лучше переименовать MoneyInput → AmountInput
