### ISSUE TITLE
Перенести компонент Divider из newclick-components

### ISSUE THREAD

**Issue by raylyanway** [alfa-laboratory/core-components#31]
# Описание
Предлагаю добавить разделитель (hr)

# Поведение
Просто добавляете, где необходимо

# Чек лист
- [x] Реализация самого компонента
- [x] Тесты
- [x] Документация

# Внешний вид
- [вид](https://digital.alfabank.ru/demo/newclick-components/a8bacf2/?path=/story/common-divider--basic-divider)

# API
Свойство|Описание|Тип|Значение по умолчанию|Обязательное
-|-|-|-|-
className|кастомный класс|string|-|нет
dataTestId|id для тестирования|string|-|нет

# Технические требования
## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
[PR](https://github.com/alfa-laboratory/core-components/pull/33)

**Comment by etroynov** [comment]
Думаю accent будет не часто используемым свойством и его стоит реализовывать локально.

**Comment by FenkoAlex** [comment]
> Думаю accent будет не часто используемым свойством и его стоит реализовывать локально.

Если его добавили в дизайн систему, его будут использовать больше нескольких раз, он не так сильно утяжелит компонент, чтоб выпилить `accent`

**Comment by raylyanway** [comment]
@etroynov и @FenkoAlex вы оба правильно рассуждаете. Тогда давайте пойдём по пути меньшего сопротивления и оставим реализованный функционал.

**Comment by pavelozavr** [comment]
> > Думаю accent будет не часто используемым свойством и его стоит реализовывать локально.

Имхо, название пропса **strong** яснее отражало бы его назначение

**Comment by SiebenSieben** [comment]
У меня больше вопрос к `<Divider orientation='vertical' />`.
Зачем нам линия на все случаи жизни?

Я бы оставил только горизонтальный (как `<hr>`).

Вертикальные линии пока встречаются редко, нарисуете на месте :)

И не будет таких конструкций:
```
<Col span={ 1 }>
  <Divider orientation='vertical' />
</Col>
```

А `accent` тоже редкий, да, но тут не вижу проблемы в том, чтобы оставить.

**Comment by etroynov** [comment]
Использование props для реализации редких стилистических поведений не завязанных на механику считаю плохой практикой.

Конкретно данный пропс малого того что не влияет на механику так еще и используется не часто.

**Comment by raylyanway** [comment]
В принципе всегда можно повлиять на толщину `divider` через класс.

**Comment by raylyanway** [comment]
Давайте подводить итог. Пальцы вверх если оставляем `accent`.

**Comment by raylyanway** [comment]
Пальцы вверх если оставляем `vertical `.

**Comment by FenkoAlex** [comment]
> Использование props для реализации редких стилистических поведений не завязанных на механику считаю плохой практикой.

мы и так везде добавляем пропс `type` который отвечает за стиль

> Вертикальные линии пока встречаются редко, нарисуете на месте :)
> Тем более уже Солдатов Саша уже заюзал)
Саше уже получается не нужен компонент из библиотеки?)
