### ISSUE TITLE
Кнопка в IE11 поехала

### ISSUE THREAD

**Issue by Luchanso** [alfa-laboratory/core-components#319]
# Опишите проблему
![image](https://user-images.githubusercontent.com/2098777/96139453-9261c200-0f07-11eb-9a9e-7991916822be.png)

# Шаги для воспроизведения
1. Открыть любую кнопку в IE11

# Ожидаемое поведение
Текст выровнен по центру

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
![image](https://user-images.githubusercontent.com/2098777/96139636-b6bd9e80-0f07-11eb-995f-f9759ed97ac6.png) | ![image](https://user-images.githubusercontent.com/2098777/96139453-9261c200-0f07-11eb-9a9e-7991916822be.png)|

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: Windows 10
 - Browser: IE
 - Version: 11

**Comment by SiebenSieben** [comment]
Да, видели, скоро пофиксим, спасибо
