### ISSUE TITLE
Компонент CircularProgressBar

### ISSUE THREAD

**Issue by raylyanway** [alfa-laboratory/core-components#321]
# Описание
Предлагаю добавить новый компонент
https://github.com/alfa-laboratory/core-components/pull/320

# Чек лист
- [x] Тесты
- [x] Документация
- [x] Реализация самого компонента

# Внешний вид
https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=11501%3A44533

# API
Свойство|Описание|Тип|Значение по умолчанию|Обязательное
-|-|-|-|-
className|кастомный класс|string|-|нет
dataTestId|id для тестирования|string|-|нет
value|значение в процентах|number|-|да
view|тип отображения|'positive', 'negative'| 'positive'|нет
size|размер|'s', 'l'|'s'|нет
headLine|основной текст|string|-|нет
caption|вспомогательный текст|string|-|нет

**Comment by SiebenSieben** [comment]
Прокомментил в реквесте

**Comment by stepancar** [comment]
Title, subTitle?

**Comment by raylyanway** [comment]
>Title, subTitle?
 Я следовал дизайнерским названиям. Переименовать не долго,  если все согласны.
Но меня кажется нам с дизайнерами надо как-то договориться об одинаковых названиях.

**Comment by raylyanway** [comment]
Заменил на title, subTitle
