### ISSUE TITLE
Новый компонент Badge

### ISSUE THREAD

**Issue by Artess999** [alfa-laboratory/core-components#327]
# Описание
Предлагаю добавить новый компонент `<Badge/>`

# Чек лист
- [ ] Обсуждение
- [ ] Документация
- [ ] Реализация
- [ ] Тесты

# Внешний вид
https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components
https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library

# API
```tsx
export type BadgeProps = {
    /**
     * Размер компонента
     */
    size?: 's' | 'm';

    /**
     *  Вид компонента
     */
    view: 'icon' | 'count';

    /**
     * Контент компонента
     */
    content?: React.ReactNode | number;

    /**
     * Цветовое оформление иконки
     */
    iconColor?: 'positive' | 'attention' | 'negative' | 'hold' | 'repeat';

    /**
     * Цвет подложки иконки
     */
    iconBackgroundColor?: ‘white’ | ‘gray’ | ‘dark-indigo’;

    /**
     * Идентификатор для систем автоматизированного тестирования
     */
    dataTestId?: string;
};
```

# Дополнительная информация
В данном компоненте предполагается также реализовать Стикер (по сути, бейдж с иконкой)
Если в компонент не передается контент, то отображается бейдж в виде точки

**Comment by Artess999** [comment]
значения iconBackgroundColor могут поменяться, так как пока не добавлены в макет возможные варианты подложек и их названия

**Comment by SiebenSieben** [comment]
Пока встречается только белый фон под иконкой, может пока не добавлять iconBackgroundColor?

А если добавлять, то нужна привязка к названиям цветов в новой палитре, теперь нет дарк индиго )

**Comment by Artess999** [comment]
> Сейчас встречается только белый фон под иконкой, может пока не добавлять iconBackgroundColor?
> 
> А если добавлять, то нужна привязка к названиям цветов в новой палитре, теперь нет дарк индиго )

Дизайнер скоро добавит еще цветов фона, и из макета я возьму актуальные наименования цветов

**Comment by SiebenSieben** [comment]
Как вариант — добавить для этого css-переменную

**Comment by Artess999** [comment]
> Как вариант — добавить для этого css-переменную

согласен, можно и так
тогда в ридми укажу, что по умолчанию цвет фона белый, но с помощью переменной им можно управлять

**Comment by lisovskyR** [comment]
С помощью переменной звучит не очень удобно, если распространенным кейсом будет другой цвет - кажется что лучше его добавить в пропсы

**Comment by SiebenSieben** [comment]
Насколько я понял, цвет может меняться при переключении темы

Пока всё в теории, и если станет понятно, что переменной недостаточно, добавить пропсу всегда успеем )

**Comment by lisovskyR** [comment]
да, звучит нормас
