### ISSUE TITLE
Ошибки в core-components при обновлении icons-glyph

### ISSUE THREAD

**Issue by Artess999** [alfa-laboratory/core-components#347]
# Опишите проблему
В данный момент в core-components icons-glyph версии 1.26.0
при обновлении до последней версии  (1.65.0) при запуске линтера начинают падать ошибки, линтер проверяет папку node_modules, которая устанавливается в компоненты
<img width="578" alt="Снимок экрана 2020-11-06 в 12 03 17" src="https://user-images.githubusercontent.com/25062433/98352827-975df100-202f-11eb-9885-b2fd07665e5e.png">
<img width="654" alt="Снимок экрана 2020-11-06 в 12 03 49" src="https://user-images.githubusercontent.com/25062433/98352842-9af17800-202f-11eb-9dfb-bc19cd948f4a.png">

**Comment by reme3d2y** [comment]
fixed 9e6cdc3be6e323eb041aacd47ef945a30e702494
