### ISSUE TITLE
[Button] Добавить nowrap

### ISSUE THREAD

**Issue by praiz** [alfa-laboratory/core-components#352]
# Опишите проблему
Сейчас текст в компоненте `button` по умолчанию работает перенос строк. При переезде с `arui-feather` начинает ехать верстка.

# Шаги для воспроизведения
1. Меняем импорты
2. Мигрируем пропсы
3. ...

# Ожидаемое поведение
Добавляется пропс `nowrap` и текст не уезжает

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
![Screenshot 2020-11-09 at 15 54 34](https://user-images.githubusercontent.com/3061978/98543684-e6ac5780-22a3-11eb-8163-d56c527f2016.png) |  ![Screenshot 2020-11-09 at 15 50 18](https://user-images.githubusercontent.com/3061978/98543533-b06ed800-22a3-11eb-85e6-087674d9ed7c.png)  |

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: MacOS
 - Browser: Safari
 - Version: 10

## Смартфон (если данных нет оставьте блок пустым):
 - Device: iPhone 6
 - OS: iOS 10
 - Browser: Chrome
 - Version: 65

**Comment by SiebenSieben** [comment]
Из-за флексов плющит? Насколько частый кейс?

По дефолту предлагаешь nowrap false?

**Comment by praiz** [comment]
плющит из-за флексов. частенько флексы используются. по дефолту можно `false`
