### ISSUE TITLE
Добавить миксины для медиа-запросов

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#363]
Предлагаю добавить миксины для медиа-запросов:

```css
@define-mixin mobileS {
	@media screen and (min-width: 320px) {
		@mixin-content;
	}
}

@define-mixin mobileM {
	@media screen and (min-width: 375px) {
		@mixin-content;
	}
}

/** Ну и так далее по списку */
```

Плюс еще можно добавить миксин для ретины

**Comment by prosto-lapsha** [comment]
мне кажется screen излишним.
сейчас есть планшеты с шириной 1024 (видела у старых версий планшетов эпл, скок сейчас не знаю), а у нас с 1024 сейчас начинается desktop-s. И в данном случае дизайнеры никак не разделяют 1024 для экранов и 1024 для десктопов, соответсвенно и нам не стоит завязываться на это условие.
Ну и как пример есть разрешение экрана в 900 пикселей, не знаю кто этим пользуется, но если такое есть, значит кому-то надо и в данном случае screen тоже не будет актуален.
В общем только на брейкпоинты предлагаю завязываться.

**Comment by aso1datov** [comment]
Кажется тут должны быть переменные вместо значений
```css
@media screen and (min-width: var(--mobile-s)) {
```

**Comment by prosto-lapsha** [comment]
еще бы я добавила миксин tablets-only для планшетов. Редко, но иногда бывает нужным только для планшетных разрешений стили поправить и с таким миксином будеи меньше переопределений

**Comment by SiebenSieben** [comment]
> еще бы я добавила миксин tablets-only для планшетов. Редко, но иногда бывает нужным только для планшетных разрешений стили поправить и с таким миксином будеи меньше переопределений

В фижере (то что берём за основу) есть такой вариант только без `only` → `tablet`

Предлагаешь поменять пока никто не использует?
https://github.com/alfa-laboratory/core-components/blob/master/packages/mq/src/mq.json

**Comment by dmitrsavk** [comment]
В `arui-scripts` уже подключен плагин [postcss-custom-media](https://github.com/postcss/postcss-custom-media).
Делать медиа-запросы можно с помощью него вот так:

```css
@media (--mobile-m) {
    /* styles */
}

@media (--desktop-s) {
    /* styles */
}
```
По-этому необходимость использовать миксины вроде как отпадает.
