### ISSUE TITLE
className для компонента Plate

### ISSUE THREAD

**Issue by Rabamidab** [alfa-laboratory/core-components#366]
Если передать в компонент Plate проп className, то он применится не только к родительсому элементу, но и к контенту. Например вот что происходит когда я хочу добавить нижний маргин к Plate:
![image](https://user-images.githubusercontent.com/13537091/99554555-5f13c680-29d0-11eb-8a51-dca3fbb0f6c0.png)
Маргин появляется в 2 местах

Я ожидаю что className применится в одном месте у контейнера.

**Comment by reme3d2y** [comment]
ага, косяк
