### ISSUE TITLE
Параметр loading не срабатывает на кнопках-ссылках

### ISSUE THREAD

**Issue by aso1datov** [alfa-laboratory/core-components#367]
# Опишите проблему
Если кнопка использована как ссылка, то пропс `loading` не добавляет спиннер и кнопку можно нажать.

# Шаги для воспроизведения
1. Использовать компонент `Button` c пропсом `href`
2. Установить пропс `loading` = true

# Ожидаемое поведение
Спиннер появляется, нажатие по кнопке не срабатывает

# Внешний вид
https://take.ms/EpmvF

**Comment by dmitrsavk** [comment]
а что за кейс? зачем ссылке состояние loading?

**Comment by aso1datov** [comment]
Кейса нет, заметил пока тыркал nowrap. Но разве поведение не должно быть одинаковым?

**Comment by dmitrsavk** [comment]
Оно так и работало раньше, но это поведение [поменяли](https://github.com/alfa-laboratory/core-components/commit/eac3c3ca888ee0092a1693b9a39843c1dd9a75f1#diff-864c9acdba5906b38227a0f798880da7667416e704e45261f5a27ffdbac6e043).
@reme3d2y сможешь вспомнить, в чем была проблема?

**Comment by reme3d2y** [comment]
> а что за кейс? зачем ссылке состояние loading?

возможно я так же тогда подумал. Не вспомню уже, почему так. Но вроде все ок с ней, открою ПР

**Comment by reme3d2y** [comment]
Предлагаю блокировку нажатия для loading ссылки не тащить в компонент. Ссылки не блокируются, поэтому придется делать костыль с onClick и preventDefault. Если такое понадобится, то это можно сделать снаружи компонента.

**Comment by aso1datov** [comment]
@reme3d2y А если `pointer-events: none` заюзать в случае ссылки?
