### ISSUE TITLE
Как будут тестироваться компоненты?

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#4]
# В проекте нет тестов для компонентов.
Какие тесты будем писать?

**Comment by etroynov** [comment]
Предлагаю:
- Jest;
- Enzyme;

???

**Comment by SiebenSieben** [comment]
Нужен будет визуальный регресс, но ближайшие пару месяцев предлагаю ехать без него.

**Comment by 7rulnik** [comment]
Что на счёт https://testing-library.com/docs/react-testing-library/intro ?
Реакт рекомендует jest + react-testing-library

**Comment by stepancar** [comment]
Я прелагаю запихнуть визуальный регресс сейчас, это "потом" может никогда не настать

**Comment by SiebenSieben** [comment]
> Я прелагаю запихнуть визуальный регресс сейчас, это "потом" может никогда не настать

Какое решение предлагаешь?

**Comment by etroynov** [comment]
Думаю будем брать react-testing-library т.к:
- ее рекомендует react;
- у enzyme есть проблемы с поддержкой хуков;

В качестве ранера будем использовать jest т.к его рекомендует react-testing-library;

**Comment by etroynov** [comment]
Подводя итог было выбрано: react-testing-library
