### ISSUE TITLE
Prop "translate" обязательный для некоторых компонентов

### ISSUE THREAD

**Issue by PutilovAI** [alfa-laboratory/core-components#400]
# Опишите проблему
При использовании например компонентов: Textarea, Tag, Radio тайпскрипт требует указать проп **translate**.
![image](https://user-images.githubusercontent.com/22417118/100730220-9b412100-33eb-11eb-8df9-e21c826ccae1.png)

# Дополнительная информация
"@alfalab/core-components": "5.2.0"

**Comment by reme3d2y** [comment]
Что-то странное. А какая версия @types/react в проекте?

https://github.com/formium/formik/issues/2120
https://github.com/ant-design/ant-design/issues/23266

**Comment by PutilovAI** [comment]
"@types/react": "16.9.11",
"@types/react-dom": "16.9.8",

**Comment by PutilovAI** [comment]
Обновил на "@types/react": "16.14.0" заработало.
