### ISSUE TITLE
Странное поведение компонента Link

### ISSUE THREAD

**Issue by FenkoAlex** [alfa-laboratory/core-components#406]
<img width="1678" alt="Снимок экрана 2020-12-03 в 10 39 04" src="https://user-images.githubusercontent.com/30617230/100979625-13772600-3555-11eb-80bd-ae4188027294.png">
компонент съезжает вниз внутри текста, на скрине обычный тег а и компонент

в теге `<a>` почему-то два спана, не понял для чего

**Comment by SiebenSieben** [comment]
[Добавление слотов](https://github.com/alfa-laboratory/core-components/pull/337/files) сломало, пофиксим

**Comment by Regina94** [comment]
от себя добавлю  
<img width="412" alt="Screenshot 2020-12-08 at 17 50 20" src="https://user-images.githubusercontent.com/8151643/101499067-df996780-397d-11eb-9611-2e00d6a156b7.png">

vertical-align: middle
