### ISSUE TITLE
Новый компонент Tag

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#43]
# Описание
Новый компонент `Tag`.
Отличается от кнопки тем, что может имеет состояние `checked`.

# Внешний вид
[Figma](https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=214%3A1873)

# API
| Свойство     |                               Описание                                |       Тип       | Значение по умолчанию | Обязательное |
|--------------|:---------------------------------------------------------------------:|:---------------:|:---------------------:|-------------:|
| title        |                      текст всплывающей подсказки                      |     string      |           -           |          нет |
| disabled     |                         заблокировать кнопку                          |     boolean     |         false         |          нет |
| leftAddons         |                                Слот слева                                 |ReactNode |           -           |          нет |
| rightAddons         |                                Слот справа                                 |ReactNode |           -           |          нет |
| size         |                размер в соотвествии с дизайн системой                 |     string      |           -           |          нет |
| onClick      |                     обработчик нажатия на кнопку                      |    function     |           -           |          нет |
| className    |                        пользовательский класс                         |     string      |           -           |          нет |
| dataTestId |                        класс для тестирования                         |     string      |           -           |          нет |
| checked     |                         состояние, когда кнопка выбрана                          |     boolean     |         false         |          нет |
| children | | ReactNode | - | нет

# Дополнительная информация
У дизайнеров называется Chips

**Comment by YozhEzhi** [comment]
Назвать просто `Tag` — не рассматривали?

**Comment by dmitrsavk** [comment]
> Назвать просто `Tag` — не рассматривали?

Можно и так, не принципиально

**Comment by etroynov** [comment]
а где пропса для контента?
