### ISSUE TITLE
Новый компонент Checkbox

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#44]
# Описание
Предлагаю добавить компонент `<Checkbox/>`

В данный момент чекбокс имеет один единственный вид.
Для возможности темизации — некоторые css свойства будет вынесены в переменные.
Также, атрибут `text` будет иметь тип `ReactNode`.

Компонент [`Toggle`](https://user-images.githubusercontent.com/9968618/77512011-38be7b00-6e83-11ea-82e3-dede8ed570ef.png) будет реализован отдельным компонентом.

# Чек лист
- [x] Обсуждение
- [x] Документация
- [x] Реализация
- [x] Тесты

# Внешний вид

<img src="https://user-images.githubusercontent.com/9968618/77403745-c20d7900-6dc1-11ea-8a11-8d17f63b62bb.png" width="240" />

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=83%3A306

# API

| Свойство     |                Описание                |    Тип    | Значение по умолчанию | Обязательное |
|--------------|:--------------------------------------:|:---------:|:---------------------:|-------------:|
| text         |        текст подписи к чекбоксу        | ReactNode |           -           |          нет |
| size         | размер в соотвествии с дизайн системой | "s" \| "m" |           m           |          нет |
| className    |         пользовательский класс         |   string  |           -           |          нет |
| dataTestId   |         класс для тестирования         |   string  |           -           |          нет |
| ...restProps | `Omit<InputHTMLAttributes<HTMLInputElement>, 'type' \| 'size'>`                           | object    |                    {} |          нет |

# Технические требования

- `React.forwardRef`

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация

Текущая реализация в [`arui-feather`](https://digital.alfabank.ru/components/checkbox)

## Stage - 0

# Изменения в API:
 | Prop name | Type | Причина
| ------ | ------ | ---- |
| ~~text~~ label | ReactNode | поменял название для единообразия с компонентом Switch |
| hint | ReactNode | см. макеты  |
| indeterminate | boolean | см. макеты |

**Comment by reme3d2y** [comment]
Хотелось бы еще обсудить вопрос с сигнатурами коллбэков.
Нашел на проектах следующие варианты:

### newclick_components:

1. Input
 ```onChange(event)```
2. MoneyInput
```onChange(amount, value, event)```

### akit:

1. Checkbox
```onChange({ checked, name, value, event })```

2. Radio
```onChange({ event, id, name, value })```

3. Input
```onChange({ value, name, event })```

### arui-feather

1. Checkbox
```onChange(isChecked, value, event)```

1. Radio
```onChange(value, isChecked, event)```

---

Хотелось бы добиться единообразия.
Есть такой вариант:

- Учитывая, что во всех базовых компонентах используется `...restProps`, то в колбэк можно передавать только `event`, а все нужные свойства (name, id и т.д.) получить через `event.target`
- В случае усложненных компонентов, типа `InputAutocomplete` и пр., колбэк может иметь вид `(event, prop1, ...)`, либо `(prop1, ..., event)`

**Comment by etroynov** [comment]
зачем checkbox restProps?

**Comment by reme3d2y** [comment]
Для тех же целей, для чего и обычному чекбоксу, инпуту и пр. все остальные атрибуты.
Я против того, чтобы ограничивать разработчиков в настройке **базовых** компонентов.

**Comment by YozhEzhi** [comment]
> Для тех же целей, для чего и обычному чекбоксу, инпуту и пр. все остальные атрибуты.
> Я против того, чтобы ограничивать разработчиков в настройке **базовых** компонентов.

+1. Главное, что `restProps` типизированы явно.

**Comment by etroynov** [comment]
> Для тех же целей, для чего и обычному чекбоксу, инпуту и пр. все остальные атрибуты.
> Я против того, чтобы ограничивать разработчиков в настройке **базовых** компонентов.

я не против того что их прокидывают, мне как и @YozhEzhi не нравится тот факт что это не типизировано т.е туда можно пропихнуть все что захочешь. Все таки предлагаю написать типы на это.

**Comment by reme3d2y** [comment]
> > Для тех же целей, для чего и обычному чекбоксу, инпуту и пр. все остальные атрибуты.
> > Я против того, чтобы ограничивать разработчиков в настройке **базовых** компонентов.
> 
> я не против того что их прокидывают, мне как и @YozhEzhi не нравится тот факт что это не типизировано т.е туда можно пропихнуть все что захочешь. Все таки предлагаю написать типы на это.

почему не типизировано? 
Там же стоит `<InputHTMLAttributes<HTMLInputElement>` - все что позволяет html.

**Comment by etroynov** [comment]
просто в компонентах которые я видел ранее типизации не было, поэтому я решил дополнительно уточнить этот момент.

**Comment by dmitrsavk** [comment]
#### Изменения API относительно issue:
 | Prop name | Type |
| ------ | ------ |
| ~~text~~ label | ReactNode |
| hint | ReactNode |
| indeterminate | boolean |
