### ISSUE TITLE
Сигнатуры коллбэков

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#45]
Хочу обсудить вопрос с сигнатурами коллбэков.
Нашел на проектах следующие варианты:

### newclick_components:

1. Input
 ```onChange(event)```
2. MoneyInput
```onChange(amount, value, event)```

### akit:

1. Checkbox
```onChange({ checked, name, value, event })```

2. Radio
```onChange({ event, id, name, value })```

3. Input
```onChange({ value, name, event })```

### arui-feather:

1. Checkbox
```onChange(isChecked, value, event)```

1. Radio
```onChange(value, isChecked, event)```

---

Хотелось бы добиться единообразия.
Есть такой вариант:

- Учитывая, что во всех базовых компонентах используется `...restProps`, то в колбэк можно передавать только `event`, а все нужные свойства (name, id и т.д.) получить через `event.target`
- В случае усложненных компонентов, типа `InputAutocomplete` и пр., колбэк может иметь вид `(event, prop1, ...)`, либо `(prop1, ..., event)`

**Comment by aso1datov** [comment]
Мне больше нравится вариант akit, т.к. не надо парится о последовательности аргументов, можно всё что нужно вытащить через деструктуризацию, плюс его гораздо проще расширять.

**Comment by reme3d2y** [comment]
Будет ли проблема из-за того, что некоторые обработчики будут возвращать объект, а все остальные, прокинутые через ...restProps, будут возвращать event?

**Comment by etroynov** [comment]
Мое мнение на сей счёт:

**newclick_componets:**
1. input - используется подход "чистых" аргументов;
2. MoneyInput - здесь часть аргументов кастомные т.к это не стилизация нативного компоенента а его расширение;

**akit**
Категорически не согласен с таким подходом т.к передача всех аргументов одним объектом блокирует или значительно усложняет множество подходов программирования таких как каррирование, мемоизация и т.д

**arui-feather**
Мне кажется тут вообще нет подхода а все по принципу так исторически сложилось.

**Comment by YozhEzhi** [comment]
> 2\. MoneyInput

1. `MoneyInput`, как быть, если нужно добавить ещё 1 аргумент? Будет breaking changes.

`onChange(amount, value, someNew, event)`

2. `MoneyInput`, как быть, если один из параметров нужно сделать необязательным? В ТС такой аргумент, д.б. после обязательного (в данном случае после `event`). 

Категорически не согласен с таким подходом.

**Comment by stepancar** [comment]
Стандартный onChange(event)
И это важно для всяких redux form и тд иметь этот объект.
Нам надо иметь возмжность проводить постобработку дополнительной нагрузки события.

я предлагаю скомпозировать подходы

onChange(event, payload: { value: string; amount: amount etc })
event как и был - прокидывается он первым что по семантике событий дом элементов и нагрузка расширяемая

**Comment by stepancar** [comment]
@etroynov в arui-feather есть подход порядка аргументов. Просто ридми кто-то потер.
Ребята выбрали передавать первым аргрументом value а вторым event.
Делали по принципу kiss чтоб на месте народ не писал event.target.value.  Уже не вспомню какой библиотекой на тот момент вдохновились.

**Comment by stepancar** [comment]
@etroynov , я щас зашел и немного прифигел в newclick-components
```
    /** обработчик ввода */
    onChange?: (amount: AmountType, value: string, e: React.ChangeEvent<HTMLInputElement>) => void;
```
Какой же это чистый подход? Я шокирован. Как @YozhEzhi сказал не понятно как с этим жить если все эти аргументы не нужны.
И чего-то не припомню чтоб это проходило ревью.
Задавай пожалуйста тренд как меинтейнер по процессу работы чтоб потом у нас не было после твоего ухода "так исторически сложилось". Не забудь пожалуйста описать концепт "чистых аргументов" который как оказалось у нас используется но в ридми про него ни слова. добавь к доке ревьюеров.

Так же, хотелось бы увидеть конкретный пример карирования с параметрами колбэка  компонентов или мемоизация , которыми ты оперировал в аргументе. Покажи пожалуйста что ты можешь сделать с интерфейсом
```
    /** обработчик ввода */
    onChange?: (amount: AmountType, value: string, e: React.ChangeEvent<HTMLInputElement>) => void;
```
но не можешь с интерфейсом akit?

**Comment by YozhEzhi** [comment]
> onChange(event, payload: { value: string; amount: amount etc })

Выглядит симпотично!

**Comment by reme3d2y** [comment]
@stepancar, спасибо за участие. Пока что твой вариант кажется самым подходящим и “правильным”.

**Comment by etroynov** [comment]
> > 2. MoneyInput
> 
> 1. `MoneyInput`, как быть, если нужно добавить ещё 1 аргумент? Будет breaking changes.

да и это правильное поведение при разработке библиотек т.к сигнатура изменилась.

> `onChange(amount, value, someNew, event)`
> 
> 1. `MoneyInput`, как быть, если один из параметров нужно сделать необязательным? В ТС такой аргумент, д.б. после обязательного (в данном случае после `event`).

а как это относится к библиотеке которая собирается в bundle ?

> 
> Категорически не согласен с таким подходом.

**Comment by etroynov** [comment]
> @etroynov , я щас зашел и немного прифигел в newclick-components
> 
> ```
>     /** обработчик ввода */
>     onChange?: (amount: AmountType, value: string, e: React.ChangeEvent<HTMLInputElement>) => void;
> ```
> 
> Какой же это чистый подход? Я шокирован. Как @YozhEzhi сказал не понятно как с этим жить если все эти аргументы не нужны.

Во первых это не примитив, а композитный компонент который спроектирован под конкретную бизнес цель и он изначально не проектировался для универсальных кейсов.

> И чего-то не припомню чтоб это проходило ревью.

т.к я сразу уточнял что это прототип и он требует переосмысления, так же я предупреждал ребят которые используют newclick-componets его пока не использовать или предупредить заранее если он понадобится.

> Задавай пожалуйста тренд как меинтейнер по процессу работы чтоб потом у нас не было после твоего ухода "так исторически сложилось". Не забудь пожалуйста описать концепт "чистых аргументов" который как оказалось у нас используется но в ридми про него ни слова. добавь к доке ревьюеров.

в README какой библиотеки?

> 
> Так же, хотелось бы увидеть конкретный пример карирования с параметрами колбэка компонентов или мемоизация , которыми ты оперировал в аргументе. Покажи пожалуйста что ты можешь сделать с интерфейсом

а причем здесь интерфейс? я говорил про функцию если в функцию все аргументы приходят объектом как ты будешь их каррировать можно сделать это и через объект но это будет выглядеть не очень.

> 
> ```
>     /** обработчик ввода */
>     onChange?: (amount: AmountType, value: string, e: React.ChangeEvent<HTMLInputElement>) => void;
> ```
> 
> но не можешь с интерфейсом akit?

могу я просто высказал свое мнение по поводу общего подхода.

**Comment by YozhEzhi** [comment]
> а как это относится к библиотеке которая собирается в bundle ?

Если придётся один из обязательных параметров сделать не обязательным — придётся изменить сигнатуру. Итого: и правки внутри либы: изменить тесты, например. И брейкинг чейнджес для прикладного пользователя. Но ты считаешь, что _это правильное поведение при разработке библиотек_.

**Comment by reme3d2y** [comment]
Всем спасибо за активность. 
Решено остановится на варианте @stepancar:
```
onChange(event, payload)
```
