### ISSUE TITLE
prop view для AmountInput

### ISSUE THREAD

**Issue by aleksey-ilin** [alfa-laboratory/core-components#464]
# Описание
Предлагаю добавить prop view для AmountInput по аналогии с для Amount, чтобы можно было скрывать минорные нули.

**Comment by stepancar** [comment]
А есть такой запрос от дизайна?

**Comment by stepancar** [comment]
скрывать при первом рендере? Звучит странно

**Comment by SiebenSieben** [comment]
Закинешь реквест?

Кажется, действительно не хватает пропсы

**Comment by aleksey-ilin** [comment]
> А есть такой запрос от дизайна?
> скрывать при первом рендере? Звучит странно

в случае когда в динамических компонентах с мидла приходит в сумме 0,00

**Comment by aleksey-ilin** [comment]
> Закинешь реквест?
> 
> Кажется, действительно не хватает пропсы

да, попробую
