### ISSUE TITLE
Смена формата номера телефона в Confirmation

### ISSUE THREAD

**Issue by aleksey-ilin** [alfa-laboratory/core-components#481]
# Описание
Предлагаю изменить формат номера телефона в компоненте `Confirmation` с отформатированного `+7 111 222 33 44` на номер телефона без форматирования `71112223344`. Тогда не будет привязки в форматированию, а для перевода номера телефона из любого формата в набор чисел можно будет использовать общую [утилиту](https://github.com/alfa-laboratory/utils/pull/44)

**Comment by reme3d2y** [comment]
Может не надо? Так мы зашьем определенное форматирование номера и могут быть проблемы при использовании компонента в разных продуктах, где принято разное форматирование.
