### ISSUE TITLE
Где будут лежать компоненты типа popup, tooltip?

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#5]

**Comment by etroynov** [comment]
Tooltip в отдельном package, а вот попап уже больше похож на виджет а не примитив и в состав библы входить не должен ( как мне кажется ).

**Comment by stepancar** [comment]
@etroynov а где будет лежать попап?

**Comment by SiebenSieben** [comment]
Смотря что называть попапом :)

В фижере Popup — это все «выпадающие» элементы.
Используется в Select, InputAutocomplete, CalendarInput.
В новой либе как отдельный компонент скорее всего не нужен, хотя стили этих выпадалок будут одинаковые.

Иногда попапом называют модалки.
И модалка, на мой взгляд, должна входить в состав библиотеки.
Это не примитив, но базовый компонент, который нужен всем.
