### ISSUE TITLE
Замечания и предложения по IntlPhoneInput

### ISSUE THREAD

**Issue by aso1datov** [alfa-laboratory/core-components#518]
# Описание
В процессе использование с IntlPhoneInput заметил следующее: сигнатура функции onChange не совпадает с сигнатурой Input, PhoneInput и т.п. Плюс, сейчас невозможно узнать какую страну выбрал пользователь, а следовательно непонятно как валидировать ввод, т.к. у разных стран количество символов в номере может различаться. Хотелось бы получать код страны в формате ISO 3166, двузначным кодом. Это позволит легко интегрироваться с https://github.com/google/libphonenumber.

**Comment by dmitrsavk** [comment]
Сигнатура не совпадает, так как во многих местах, где вызывается обработчик `onChange`, отсутствует само событие. Можно event сделать опциональным, но тогда какой смысл в этом смысл?

`libphonenumber.js` уже используется под капотом, можно в параметрах  `onChange` присылать еще и код  страны.

**Comment by aso1datov** [comment]
Ну такой же инпут, но с российскими номерами, например, содержит уже сигнатуру с ивентом, как потребителю, мне кажется, что и тут та же самая механика.

Можно добавить onCountryChange и там пробрасывать код выбранной страны
