### ISSUE TITLE
Дизейбл тултипа

### ISSUE THREAD

**Issue by ethorz** [alfa-laboratory/core-components#529]
# Описание
Предлагаю добавить пропс disabled, проблема заключается в том, что если отображение тултипа нужно по ряду условий, например если дизейбл кнопки - то отображать тултип при наведении на эту кнопку (флаг будет один), если дизейбла кнопки нет - то тултип не должен отображаться при наведении на кнопку

**Comment by SiebenSieben** [comment]
У тултипа есть `open`, можешь делать `false` когда он не должен отображаться. Такой вариант не подходит?

**Comment by ethorz** [comment]
> У тултипа есть `open`, можешь делать `false` когда он не должен отображаться. Такой вариант не подходит?

Не подойдет в том плане, что нужно делать управление на уровне родителя. Если open будет false - он будет отображен всегда, не зависимо от того, какой был триггер
