### ISSUE TITLE
Нет возможности использовать нестилизованную ссылку

### ISSUE THREAD

**Issue by prosto-lapsha** [alfa-laboratory/core-components#584]
# Опишите проблему
Есть кейс при котором надо обернуть элемент в ссылку, но подчеркивание не нужно.
![image](https://user-images.githubusercontent.com/18405099/112132412-a65acf80-8bdb-11eb-9e4f-0361dc09a5fd.png)
Если добавить иконку через addons а в чилдрен указать пустую строку (т.к. наличие children обязательно), то рисуется ок, но код выглядит костыльно
![image](https://user-images.githubusercontent.com/18405099/112132959-3ac53200-8bdc-11eb-8a19-fea7d6d74276.png)
![image](https://user-images.githubusercontent.com/18405099/112133001-46b0f400-8bdc-11eb-9609-a6f54c4d8223.png)

# Шаги для воспроизведения
1. Обернуть в link иконку

# Ожидаемое поведение
Хотелось бы для таких кейсов уметь импортить ссылку без стилей (но возможно со сбросом дефолтных стилей, оставить фокус и все такое) или просто добавить новый view без подчеркивания

# Чек лист
- [ ] Тесты
- [ ] Документация

**Comment by reme3d2y** [comment]
Можно `view='ghost'` добавить по аналогии с кнопкой

**Comment by prosto-lapsha** [comment]
Тогда надо доку поправить 
![image](https://user-images.githubusercontent.com/18405099/112142570-cee8c680-8be7-11eb-855a-b139a3e7d6b5.png)

**Comment by SiebenSieben** [comment]
[IconButton](https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B--icon-button) не подойдёт?

**Comment by prosto-lapsha** [comment]
визуально похоже на правду, ток описания пропсов в демке не хватает
