### ISSUE TITLE
Перенести компонент Button из arui-feather

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/core-components#6]
# Описание
Предлагаю добавить новую кнопку, для обработки пользовательских действий.

# Чек лист
- [x] Тесты
- [ ] Документация

# Внешний вид
https://digital.alfabank.ru/components/button

# API
| Свойство     |                               Описание                                |       Тип       | Значение по умолчанию | Обязательное |
|--------------|:---------------------------------------------------------------------:|:---------------:|:---------------------:|-------------:|
| type         | оформление кнопки в соотвествии с используемой дизайн системой: type* |     string      |        'default'      |          нет |
| title        |                      текст всплывающей подсказки                      |     string      |           -           |          нет |
| disabled     |                         заблокировать кнопку                          |     boolean     |         false         |          нет |
| htmlType     |            тип кнопки ( значение атрибута `type`)                     |     string      |           -           |          нет |
| icon         |                                иконка                                 | string, element |           -           |          нет |
| loading      |                 показываем индикатор загрузки: спинер                 |     boolean     |           -           |          нет |
| size         |                размер в соотвествии с дизайн системой                 |     string      |           -           |          нет |
| block        |                       принимает ширину родителя                       |     boolean     |           -           |          нет |
| onClick      |                     обработчик нажатия на кнопку                      |    function     |           -           |          нет |
| className    |                        пользовательский класс                         |     string      |           -           |          нет |
| data-test-id |                        класс для тестирования                         |     string      |           -           |          нет |

**Type: default, primary, secondary, pseudo, link**

# Технические требования
https://digital.alfabank.ru/patterns/amount

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
исходный код: https://github.com/alfa-laboratory/arui-feather/tree/master/src/button
пример: https://digital.alfabank.ru/components/button
PR: https://github.com/alfa-laboratory/core-components/pull/15

**Comment by stepancar** [comment]
Может не block а isFullWidth?

**Comment by stepancar** [comment]
что такое htmlType? что туда можно передать?

**Comment by SiebenSieben** [comment]
Сначала тоже смутил `block`, но это достаточно распространённое название для такой пропсы, так что мне ок.

`htmlType` тоже ок.

Не хватило:
* tabIndex
* tag (button/a)
* href

Не понимаю разницу default и primary.
И нам вроде не нужны success/danger/ghost.
На мой взгляд типы следующие: primary/secondary/pseudo/link.

**Comment by SiebenSieben** [comment]
И тут уже будут темы.

**Comment by denisx** [comment]
`htmlType` это `tag` | `htmlWrapper`?

**Comment by FenkoAlex** [comment]
```
`type` - оформление кнопки в соотвествии с используемой дизайн системой: type*
```
у тега `button` есть одноименное св-во `type` = `button | reset | submit`, это не `theme` в https://digital.alfabank.ru/components/button?

Вопрос по поведению кнопки. Как смотрите на то, чтобы кнопка по разрешениям сама определяла свои стили, а размер кнопки задавал ее габариты, пример:
```
`s` 
1920: font-size: 20px
768: fs: 15px
320: fs 10px 
`xl` 
1920: font-size: 40px
768: fs: 30px
320: fs 20px 
```

**Comment by FenkoAlex** [comment]
@denisx 
```
size слишком расплывчато. задавать отдельно margin/padding/width
```
margin/padding по дизайн системе не должны меняться? Если очень надо будет, переопределить по месту. По мне, `size` - оч говорящее название для пропса

**Comment by denisx** [comment]
@FenkoAlex базовый слой - это размеры 10-15-20. а уже абстракция выше - уровень неймингов и медиа-квери

**Comment by SiebenSieben** [comment]
`htmlType` — это обычный атрибут type (submit/reset).

`size` — один из предусмотренных размеров:
<img src="https://user-images.githubusercontent.com/109410/71463957-1015df00-27c9-11ea-9079-423781d95d56.png" width="452" alt="" />

**Comment by denisx** [comment]
@SiebenSieben нейминг это уровень абстракции. он может зависеть от устройства или медиа-квери. базовые размеры должны быть в фактических цифрах.

**Comment by denisx** [comment]
@FenkoAlex про `type` согласен

**Comment by SiebenSieben** [comment]
> Вопрос по поведению кнопки. Как смотрите на то, чтобы кнопка по разрешениям сама определяла свои стили, а размер кнопки задавал ее габариты

Обычно это не требовалось, насколько я знаю.

**Comment by SiebenSieben** [comment]
@denisx, приведи примеры проблем с s/m/l, пожалуйста.

**Comment by denisx** [comment]
@SiebenSieben написал выше

**Comment by dunai12** [comment]
Не хватает пропсов для кастомизации **aria-* атрибутов**, которые нужны людям с ограниченными способностями, для взаимодействия с интерфейсом

**Comment by denisx** [comment]
@dunai12 кстати вопрос на уровне `type` - стоит ли вносить в компоненты базовые пропсы? типа, если нужны - пиши их, не нужны - не пиши. через `...rest` всё провалится

**Comment by YozhEzhi** [comment]
Не планируется ли в кнопку и вообще в кор-компоненты передавать пропс для тестирования? `data-test-id` / `data-qa-id`

**Comment by SiebenSieben** [comment]
@YozhEzhi да, нужен

**Comment by etroynov** [comment]
> `htmlType` это `tag` | `htmlWrapper`?
> `type` -> `kind` ?
> `loading` !== `icon` ?
> `block` -> `inline` ?
> `size` слишком расплывчато. задавать отдельно margin/padding/width

- htmlType это значение type для атрибута `type` который есть у тега `button`;
- тип кнопки берется из предустановленных стилей;
- показывать/скрывать предустановленный спинер ( если таковой имеется );
- size предопределенный стили если нужны кастомные то они либо переопределяются темой, либо через className;

**Comment by etroynov** [comment]
> ```
> `type` - оформление кнопки в соотвествии с используемой дизайн системой: type*
> ```
> 
> у тега `button` есть одноименное св-во `type` = `button | reset | submit`, это не `theme` в https://digital.alfabank.ru/components/button?

да но поскольку это обертка, мы используем этот атрибут несколько иначе + многие фреймворки использую этот атрибут для тех же целей ( antd, react-bootstrap, materialUI и т.д );

> 
> Вопрос по поведению кнопки. Как смотрите на то, чтобы кнопка по разрешениям сама определяла свои стили, а размер кнопки задавал ее габариты, пример:

нет, если нужна адаптивность она реализуется подключением адаптивной темы, по умолчанию адаптивности у кнопки не будет, т.к не всем это нужно.

> 
> ```
> `s` 
> 1920: font-size: 20px
> 768: fs: 15px
> 320: fs 10px 
> `xl` 
> 1920: font-size: 40px
> 768: fs: 30px
> 320: fs 20px 
> ```

**Comment by etroynov** [comment]
> Не хватает пропсов для кастомизации **aria-*** атрибутов, которые нужны людям с ограниченными способностями, для взаимодействия с интерфейсом

они будет зашиты изначально без возможности изменения поскольку основные моменты уже стандартизированы.

**Comment by stepancar** [comment]
@etroynov block - согласен, исправляюсь , снимаю вопрос, поддерживаю

**Comment by denisx** [comment]
> они будет зашиты изначально без возможности изменения поскольку основные моменты уже стандартизированы.
у нас есть html5, и зашивать то, что нужно не всем - не нужно

**Comment by etroynov** [comment]
aria роли нужны для корректной работы ПО людей с ограниченными возможностями и я считаю что они должны быть обязательно не зависимо от того хочет этого разработчик этого или нет.

**Comment by ilatovsky** [comment]
> @YozhEzhi да, нужен `data-test-id`

Назвать пропсу лучше наверное в camelCase (как остальные) и уже на рендере переводить ее в kebab

**Comment by YozhEzhi** [comment]
> Назвать пропсу лучше наверное в camelCase (как остальные) и уже на рендере переводить ее в kebab

Да, пропс `dataTestId`. Аттрибут для `<button>` — `data-test-id`.

**Comment by etroynov** [comment]
реализованно.
