### ISSUE TITLE
Новый компонент Radio

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#60]
# Описание
Предлагаю добавить компонент `<Radio/>`

Для возможности темизации — некоторые css свойства будет вынесены в переменные.
Также, атрибут `text` будет иметь тип `ReactNode`.

# Чек лист
- [ ] Обсуждение
- [ ] Документация
- [ ] Реализация
- [ ] Тесты

# Внешний вид

<img src="https://user-images.githubusercontent.com/9968618/78327530-c84fe200-7585-11ea-83d5-7551af10228e.png" width="240" />

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=83%3A306

# API

```tsx

type NativeProps = InputHTMLAttributes<HTMLInputElement>;

export type RadioProps = Omit<
    NativeProps,
    'type' | 'onChange' | 'checked' | 'disabled' | 'name' | 'className'
> & {
    /**
     * Идентификатор для систем автоматизированного тестирования
     */
    dataTestId?: string;

    /**
     * Текст подсказки снизу
     */
    hint?: ReactNode;

    /**
     * Текст подписи
     */
    label?: ReactNode;

    /**
     * Управление состоянием отмечен/не отмечен
     */
    checked?: boolean;

    /**
     * Управление состоянием активен / не активен
     */
    disabled?: boolean;

    /**
     * Html аттрибут name инпута
     */
    name?: string;

    /**
     * Класс компонента
     */
    className?: string;

    /**
     * Обработчик на выбор элемента
     */
    onChange?: (
        event?: ChangeEvent<HTMLInputElement>,
        payload?: {
            checked: boolean;
            name?: string;
        },
    ) => void;
};
```

# Технические требования

- `React.forwardRef`

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация

Текущая реализация в [`arui-feather`](https://digital.alfabank.ru/components/radio)

**Comment by etroynov** [comment]
почему контент не сделать через children и убрать text? у size тип неправильный возможно имелось ввиду string сейчас "s"

**Comment by reme3d2y** [comment]
> почему контент не сделать через children и убрать text? у size тип неправильный возможно имелось ввиду string сейчас "s"

таблица сломалась, поправил. 

Насчет text или children - подразумевается, что в качестве контента будет обычный или отформатированный текст, поэтому ReactNode.
В принципе согласен, лучше на children заменить. Вдруг будут кейсы, где будет не текст, а что-то другое.
