### ISSUE TITLE
Компонент Select отрисовывается с "безумной" высотой в `IE11`

### ISSUE THREAD

**Issue by ZEXSM** [alfa-laboratory/core-components#607]
# Опишите проблему
Проблема с высотой у компонента Select и тех компонентов, где используется FormControl в IE11.

# Шаги для воспроизведения
1. Закинуть на страницу компонент Select 

# Ожидаемое поведение
Высота адекватного размера в соответствии с имеющимися размерами с компонента.

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
![image](https://user-images.githubusercontent.com/7240769/113515044-baf37c00-957a-11eb-92d7-dc79f91ed2d6.png)
 | 
![image](https://user-images.githubusercontent.com/7240769/113515005-7f58b200-957a-11eb-93f6-ae17a4e50095.png)
|

# Дополнительная информация
1. на первый взгляд исправляется, если тут 
https://github.com/alfa-laboratory/core-components/blob/master/packages/form-control/src/index.module.css#L85
задать height: auto;
2. так же можно было бы исправить, через props inputClassName, но его по каким-то причинам нет, хотя есть labelClassName, addonsClassName

**Comment by reme3d2y** [comment]
Не получается воспроизвести. Какие у контейнера стили?
Есть возможность подготовить ссылку, чтобы можно было в браузерстеке посмотреть?

![image](https://user-images.githubusercontent.com/9968618/113540273-71417a80-95e8-11eb-8a98-c73cb073a5da.png)

Класс на компонент можно накинуть через className

**Comment by reme3d2y** [comment]
Проблема оказалась в том, что в AppHTML из arui-private не рендерится doctype. Решилось добавлением doctype на стороне приложения.
