### ISSUE TITLE
Новый компонент Switch

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#61]
# Описание
Предлагаю добавить компонент ~~`<Toggle/>`~~  `<Switch/>`

Варианты реализации:
**1. Полностью отдельный компонент.**
~~2. Отдельный компонент `<Toggle/>`, который рендерит стилизованный `<Checkbox/>`.
Но для этого нужно будет добавить в чекбокс пропсу для выбора стиля, типа `view` из фижера или `type`.~~
~~3. Отдельный компонент не делать. Добавить пропсу в чекбокс:
`<Checkbox {type|view}="toggle"/>`.~~

# Чек лист
- [x] Обсуждение
- [x] Документация
- [x] Реализация
- [x] Тесты

# Внешний вид

<img src="https://user-images.githubusercontent.com/9968618/78329284-eddeea80-7589-11ea-85a5-e523ffe5f427.png" width="120"/>

### Актуальный
<img src="https://user-images.githubusercontent.com/9968618/79191042-5c476680-7e2e-11ea-8864-fb9b49af2089.png" width="240"/>

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=83%3A306

# API

| Свойство     |                Описание                |    Тип    | Значение по умолчанию | Обязательное |
|--------------|:--------------------------------------:|:---------:|:---------------------:|-------------:|
| text         |       Текст подписи к переключателю      | ReactNode |           -           |          нет |
| hint       | Подсказка снизу                        | ReactNode |           -           |          нет |
| size         | Размер в соотвествии с дизайн системой | "s"\| "m" |           m           |          нет |
| className    |         Пользовательский класс         |   string  |           -           |          нет |
| dataTestId   |         Класс для тестирования         |   string  |           -           |          нет |
| ...restProps | `Omit<InputHTMLAttributes<HTMLInputElement>, 'type' \| 'size'\|'hint'>`                           | object    |                    {} |          нет |

# Технические требования

~~- `React.forwardRef`~~

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация

Текущая реализация в [`arui-feather`](https://digital.alfabank.ru/components/toggle)

**Comment by YozhEzhi** [comment]
> Предлагаю все-таки делать его отдельным компонентом, чтобы не путать пользователей библиотеки.

+1

**Comment by YozhEzhi** [comment]
А не рассматривается вариант, когда текст будет в 2 строки? Например, `<Toggle/>` поместят в некий Grid и ограничат Grid по ширине.

Такой кейс редкий, но может стоит спросить у дизайнеров что делать в такум случае?

**Comment by SiebenSieben** [comment]
> А не рассматривается вариант, когда текст будет в 2 строки? Например, `<Toggle/>` поместят в некий Grid и ограничат Grid по ширине.

Так вёрстка будет это учитывать.
Или не понял о чём ты.

**Comment by SiebenSieben** [comment]
@reme3d2y 

У этого компонента отличаются стили на мобилке.
На десктопе, как правило, лейбл справа от тоггла, на мобилке — всегда лейбл слева.

А в фижере есть ещё пропса `labelAlign`, т.к. иногда на десктопе тоже нужно сделать лейбл слева.

**Comment by etroynov** [comment]
Предлагаю переименовать <Toggle /> -> <Switch />:
- https://material.io/components/selection-controls/#switches;
- https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/;
- https://getbootstrap.com/docs/4.2/components/forms/#switches;
- https://ant.design/components/switch/;

**Comment by reme3d2y** [comment]
> Предлагаю переименовать Toggle -> Switch:
> 
> * https://material.io/components/selection-controls/#switches;
> * https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/;
> * https://getbootstrap.com/docs/4.2/components/forms/#switches;
> * https://ant.design/components/switch/;

Если везде так, то я тоже не против переименовать.

**Comment by ilyamilosevic** [comment]
Toggle бы я использовал для абстрагирования таких переключателей. См. пример: https://codesandbox.io/s/9yp5p2z7yr?from-embed=&file=/src/toggle.js

В чем смысл:
* Сам Switch это «глупый» компонент
* Toggle отвечает за само состояние и показывает в зависимости от состояния компонент On/Off с нужным контентом

На сайте мы так унифицировали показ/скрытие (переключение/включение) чего-то: https://alfabank.ru/api/akit/?path=/story/utils-toggle--online-request

**Comment by etroynov** [comment]
> Toggle бы я использовал для абстрагирования таких переключателей. См. пример: https://codesandbox.io/s/9yp5p2z7yr?from-embed=&file=/src/toggle.js
> 
> В чем смысл:
> 
> * Сам Switch это «глупый» компонент
> * Toggle отвечает за само состояние и показывает в зависимости от состояния компонент On/Off с нужным контентом
> 
> На сайте мы так унифицировали показ/скрытие (переключение/включение) чего-то: https://alfabank.ru/api/akit/?path=/story/utils-toggle--online-request

тогда будет смешивание понятий, т.к с первого взгляда это не очевидно.

**Comment by reme3d2y** [comment]
https://github.com/alfa-laboratory/core-components/pull/79#issue-402983330

**Comment by etroynov** [comment]
issue переименуйте в switch
