### ISSUE TITLE
Новый компонент Tooltip

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#69]
# Описание
Новый компонент `Tooltip`.

# Внешний вид
[Site/NIB](https://www.figma.com/file/NDAzQX1HYAJ2NtQQHNo4LDLs/NIB-Components?node-id=451%3A0)
[Click](https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=35%3A101)

# API
| Свойство     |                               Описание                                |       Тип       | Значение по умолчанию | Обязательное |
|--------------|:---------------------------------------------------------------------:|:---------------:|:---------------------:|-------------:|
| children|Дочерние элементы. При наведении или клике на них, показывается тултип | ReactNode | -|     да |
| content| Контент | ReactNode | -|     нет |
| position| Расположение | right-bottom, right, right-top, top-right, top, top-left, left-top, left, left-bottom, bottom-left, bottom, bottom-right |     нет |
| mouseEnterDelay | Время, через которое откроется тултип | number | 0.3s |     нет |
| mouseLeaveDelay | Время, через которое закроется тултип | number | 0.3s |     нет |
| trigger | Триггер открытия | hover, click | hover |     нет |
| onVisibilityChange | callback, когда тултип открывается или закрывается | (visible: boolean) => void | - |     нет |
| open | Если true, то тултип открыт (для 'ручного' управления видимостью тултипа ) | boolean | - |     нет |
| className | Дополнительный класс | string | - |     нет |
| dataTestId | id для тестирования | string | - |     нет |

# Дополнительная информация

**Comment by SiebenSieben** [comment]
Нужно ли так много вариантов расположения?

**Comment by SiebenSieben** [comment]
Предлагаю переименовать `position` → `direction`

**Comment by dmitrsavk** [comment]
Ну по идее, они все нужны, это не сложно будет сделать, и кода для этого много не надо.
По поводу нэйминга, я бы оставил `position ` или `placement`, ведь это именно расположение элемента относительно children

<img width="419" alt="Снимок экрана 2020-04-08 в 13 44 55" src="https://user-images.githubusercontent.com/16844982/78775602-25410300-799f-11ea-8a30-01590bc15aa2.png">

**Comment by ilyamilosevic** [comment]
Если поможет, на сайте есть своя реализация: https://alfabank.ru/api/akit/?path=/story/utils-popover--popover-with-close-button

Использует popper.js под капотом.

За пример брались:
* Atlassian: https://bitbucket.org/atlassian/atlaskit-mk-2/src/master/packages/core/tooltip/
* Evergreen: https://github.com/segmentio/evergreen/tree/master/src/popover

Очень важно использовать централизованный способ управления z-index-ом, чтобы не было случаев, когда тултип в модалке, допустим, не виден из меньшего z-index. См. [Stack](https://github.com/segmentio/evergreen/tree/master/src/stack).

Также должен быть единый контейнер для компонентов с абсолютным/фиксированным позиционированием. См. [Portal](https://github.com/segmentio/evergreen/tree/master/src/portal)

**Comment by dmitrsavk** [comment]
@ilyamilosevic 
Спасибо за ссылки)

**Comment by etroynov** [comment]
Мне кажется лучше будет:
- mouseEnterDelay -> onOpenDelay;
- mouseLeaveDelay - > onCloseDelay;
- onVisibilityChange разбить на onOpen и onClose ( т.к может понадобится сделать эвент только на открытие );

**Comment by SiebenSieben** [comment]
Согласен про mouseEnterDelay/mouseLeaveDelay
