### ISSUE TITLE
Когда будет contribute guide?

### ISSUE THREAD

**Issue by pavelozavr** [alfa-laboratory/core-components#7]
Когда и будет ли contribution guide? Чего хотелось бы видеть:

1. Конвенцию по именованию веток
2. Конвенцию по содержанию коммитов
3. Гайд по интеграции в сторибук (CSF или нет, аддоны и бла, бла, бла)

**Comment by etroynov** [comment]
в работе, добавил черновик. Сейчас его прорабатываю.
