### ISSUE TITLE
Как выглядят комментарии к пропсам

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#73]
Сейчас комментарии к пропсам в одну строку. typescript предлагаеь использовать многострочные комменты как это сделано в фижере. Я предлагаю использовать их.
Если есть возможность - нужно капнуть линтинн комментов

**Comment by YozhEzhi** [comment]
> typescript предлагаеь использовать многострочные комменты

А где это почитать?

**Comment by stepancar** [comment]
@YozhEzhi , hm, реально не смог найти четких рекомендаций, хотя в памяти отложилось что они точно были. Хм, я в замешательстве) Однако если провалиться в исходники typescript там преобладают многострочные комменты (именно для прпертей и филдов https://github.com/microsoft/TypeScript/blob/master/src/server/project.ts#L180)
Попробовал eslint-jsdoc-plugin и там вроде как ничего нет про этот кейс. Однако есть куча других. Сам typescript использует у себя как раз его https://github.com/microsoft/TypeScript/blob/master/.eslintrc.json#L14

**Comment by etroynov** [comment]
> https://github.com/microsoft/TypeScript/blob/master/.eslintrc.json#L14


> @YozhEzhi , hm, реально не смог найти четких рекомендаций, хотя в памяти отложилось что они точно были. Хм, я в замешательстве) Однако если провалиться в исходники typescript там преобладают многострочные комменты (именно для прпертей и филдов https://github.com/microsoft/TypeScript/blob/master/src/server/project.ts#L180)
> Попробовал eslint-jsdoc-plugin и там вроде как ничего нет про этот кейс. Однако есть куча других. Сам typescript использует у себя как раз его https://github.com/microsoft/TypeScript/blob/master/.eslintrc.json#L14
> 
> Я предлагаю затащить его по крайней мере в либы, в arui-presets-lint это не затащить, потому что на проекте вещь не обяхательаня

сложный момент т.к там есть:
- /* */
- /*
*/
- //

так что они все 3 используют

Я лично за однострочне для *props* так короче и читается проще

**Comment by YozhEzhi** [comment]
Да, может у них там есть причины, но выглядит неконсистентно.

![image](https://user-images.githubusercontent.com/2706062/79132854-b0f9cb80-7db3-11ea-8289-f9f1cfbd53fd.png)

**Comment by stepancar** [comment]
Я больше топлю за 3, но это вкус. Мне всего лишь хочется чтоб все было одинаково.
3 строки просто обеспечивает упрощеное написнаие регулярки для поиска чем я пользовался в фижере и это дало возможность поменть одновремнно хертилион файлов.
Операция не частая, но почему бы себе не упростить жизнь.

Давайте начнем хотябы просто в недрения jsdoc линта на минималках и постепенно его закрутим

**Comment by reme3d2y** [comment]
Я пожалуй тоже за многострочные.
Часто бывают кейсы, когда в одну строчку все не вместить.
