### ISSUE TITLE
CalendarInput валидация ввода с клавитуры 

### ISSUE THREAD

**Issue by Tisaev** [alfa-laboratory/core-components#731]
# Описание
У компонента есть атрибуты minDate maxDate которые виляют только на datePicker
При вводе даты руками можно прописать любые цифры например 99.99.9999

**Comment by reme3d2y** [comment]
Да, вообще было бы круто это сделать. Но думаю правильнее будет сделать сначала DateInput и потом просто заюзать его в CalendarInput
