### ISSUE TITLE
Компонент comfirmation - timer. 

### ISSUE THREAD

**Issue by raylyanway** [alfa-laboratory/core-components#733]
# Описание
Предлагаю заменить реализацию таймера для comfimation c window.requestAnimationFrame на setTimeout.
Причины:
- код для таймера в 60 раз чаще будет запускаться, чем от него требуется
- не видно глобальной анимации, чтобы использовать window.requestAnimationFrame
- не понятны причины почему не setTimeout, который вроде для этого и создан )

**Comment by raylyanway** [comment]
Я там в ишью не писал, но проблема вытекла из сайпрес.
Который не корректно работал с этим таймером.
При использовании cy.clock and cy.tick таймер замораживался и начинал показывать 99:99

Проблема:
comfirmation из core использует window.requestAnimationFrame для таймера
использование cy.clock() cy.tick(60000) ломает его работу
может это связано с тем, что clock контролирует только setTimeout , clearTimeout , setInterval , clearInterval , Date Objects
таймер начинает показывать 99:99
ожидание запросов происходит с большой задержкой, если они между clock и tick К примеру в такой последовательности clock wait tick
поэтому тест на ожидание кнопки, чтобы повторить запрос иногда падает
количество секунд выставленных в tick никак не влияет
таймер как будто замораживает
Решение:
надо подставлять дату в clock и чуть больше секунд в tick, так как время на завершения минуты таймера определяется по разному то 6200, то 63000
чтобы наверняка можно сделать больше 70000
таймер будет показывать -8 сек, но это не важно
запросы, где бы они не находились между clock и tick или нет, будут летать со скоростью звука
тест станет работать стабильно
clock(Date.now()) wait tick(70000) || wait  clock(Date.now()) tick(70000)

**Comment by raylyanway** [comment]
Но всё равно предложение остаётся актуальным !!

**Comment by stepancar** [comment]
setTimeInterval a не setTimeout

**Comment by raylyanway** [comment]
Да, я это и имел введу))

**Comment by reme3d2y** [comment]
@dmitrsavk пока в отпуске, думаю стоит его подождать

**Comment by dmitrsavk** [comment]
requestAnimationFrame используется для плавной анимации лоадера (который слева от таймера).

<img width="351" alt="Снимок экрана 2021-07-15 в 09 29 01" src="https://user-images.githubusercontent.com/16844982/125739727-91027fbf-4c57-4e9f-9baa-5e7b739e1d81.png">

Если делать через setInterval, то при небольших значениях таймера лоадер будет уменьшатся "рывками".
@raylyanway а какое у вас обычно значение таймера? В принципе, если значение большое, то может и незаметно будет

**Comment by AleksandrSerov** [comment]
@dmitrsavk 60 сек наверное везде

**Comment by dmitrsavk** [comment]
@AleksandrSerov 
@raylyanway 
Открыл PR, покажите, пожалуйста своим дизайнерам, нормально ли им так

**Comment by dmitrsavk** [comment]
Если что, то анимацию лоадера можно сделать плавнее, главное чтобы тесты пофиксились

**Comment by dmitrsavk** [comment]
Анимацию лоадера сделали более плавной, проверяйте, пофиксились ли тесты
