### ISSUE TITLE
Прикладывать ссылку на макет компонента

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#74]
Предлагаю прикладывать ссылку на макет в фигма, пряма в коде

```
/**
* [Figma](url)
*/
class MyComponent {}
```

Мотивация такая что сейчас посмотрев фижер - не понятно где макеты

**Comment by reme3d2y** [comment]
Да, я в фижере лично столкнулся с этим. 
Насчет ссылки - думаю будет лучше ее указывать в сторибуке.

**Comment by SiebenSieben** [comment]
Чуть прокачаем сторибук и везде укажем ссылку в доке

**Comment by YozhEzhi** [comment]
А в сторибук не думаете прикладывать? Мне кажется макет захотят посмотреть не только разрабы.

![image](https://user-images.githubusercontent.com/2706062/78971145-9bff0d00-7b13-11ea-96f5-96f6964b6eb6.png)

**Comment by YozhEzhi** [comment]
> Чуть прокачаем сторибук и везде укажем ссылку в доке

Написал сообщение, а потом увидел твоё. Простите.

**Comment by stepancar** [comment]
Гайз, можно хоть в стори буке. Но лично мне в коде больше нравится, но чтоб сторибук оттуда доставал. Так есть связь кода и макета
