### ISSUE TITLE
Attach: Uncontrolled

### ISSUE THREAD

**Issue by Aliaksandra-Sunny** [alfa-laboratory/core-components#743]
# Опишите проблему
Хотела поменять onChange, но столкнулась с проблемой, что value привязано к локальному стейту, поэтому нет возможности изменения value извне. 
Например, мне нужно было поменять поведение при onChange, чтобы файлы не перезаписывались, а добавлялись к предыдущему массиву, но в своем onChange нельзя обратиться к методу изменения локального стейта, а значит нельзя поменять value компоненты.

# Ожидаемое поведение
Возможность контроля value

**Comment by reme3d2y** [comment]
Есть такое.

@Artess999 Артем, ты ведь в цели взял загрузчик файлов? Думаю тебе тоже придется это делать. Есть возможность эту таску сделать пораньше?

**Comment by Artess999** [comment]
> Есть такое.
> 
> @Artess999 Артем, ты ведь в цели взял загрузчик файлов? Думаю тебе тоже придется это делать. Есть возможность эту таску сделать пораньше?

Я пока в отпуске, если не накидают ничего критичного, думаю, что могу)
В любом случае, по идее, я под капотом тот же Attach буду использовать (не точно, так как макеты не особо помню)
