### ISSUE TITLE
Attach: сброс массива только по крестику(кнопке сброса), и сложение массивов при повторном нажатии кнопки

### ISSUE THREAD

**Issue by Aliaksandra-Sunny** [alfa-laboratory/core-components#744]
# Описание
Сейчас компонента Attach всегда сбрасывает старый массив и записывает новый. 
При повторном нажатии на компонент и выборе дополнительных файлов, компонент не добавляет новые файлы к предыдущим, а удаляет предыдущие и записывает новые. Т.е. в ситуации, если пользователь прикрепил два файла, а потом захотел прикрепить ещё три, предыдущие два выбранных файла удалятся и будут отображаться только новые выбранные три.
Придлагаю не перезаписывать массив, а к предыдущему массиву добавлять новый массив

# Поведение
Нажимаем на кнопку прикрепления файла, выбираем n файлов, подтверждаем выбор. Видим n прикрепленных файлов. Далее нажимаем на кнопку прикрепа файлов и выбираем ещё m файлов, подтверждаем выбор. В итоге видим n+m прикрепленных файлов. Удаляем файлы из прикрепленных по кнопке крестика(сброса).

**Comment by reme3d2y** [comment]
Думаю стоит предусмотреть оба режиме
