### ISSUE TITLE
Демо. Проблемы с селектом выбора темы

### ISSUE THREAD

**Issue by AleksandrSerov** [alfa-laboratory/core-components#745]
# Опишите проблему
1. При изменении knobs тема компонента не соответсвует выбранной
2. При переключении между табами Docs/Canvas тема не соответствует выбранной

# Шаги для воспроизведения
Проблема 1
1. Перейти на [ демку, IntlPhoneInput](https://alfa-laboratory.github.io/core-components/90a4f41c75da032c24113dc420544df3c69217bd/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-inputautocomplete--input-autocomplete)
2. Перейти на вкладку canvas
3. В селекте выбора темы, выбрать click
4. Изменить knob size

Фактическое поведение
Компонент рендерится в default теме, в селекте значение - click

Ожидаемое поведение
Компонент рендерится в теме - click, в селекте значение - click

Проблема 2
1. Перейти на [ демку, IntlPhoneInput](https://alfa-laboratory.github.io/core-components/90a4f41c75da032c24113dc420544df3c69217bd/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-inputautocomplete--input-autocomplete)
2. Находясь на табе Docs, в селекте выбора темы, выбрать click
3. Перейти в таб Canvas

Фактическое поведение
Компонент рендерится в default теме, в селекте значение - click

Ожидаемое поведение
Компонент рендерится в теме - click, в селекте значение - click

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
** Ожидаемый  ** | ** Фактический    **|

# Тестовый стенд

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Дополнительная информация

**Comment by reme3d2y** [comment]
В мастере уже пофиксили, нужно актуализировать ветку
