### ISSUE TITLE
Компонент Modal создает горизонтальный скролл

### ISSUE THREAD

**Issue by ekabolotina** [alfa-laboratory/core-components#775]
# Опишите проблему
Модальное окно размера `l` создает горизонтальную прокрутку, если выполняется условие `767px > W < 800px, где W — ширина окна браузера`.

# Шаги для воспроизведения
1. Перейти в песочницу https://codesandbox.io/s/agitated-butterfly-l95cw
2. Перейти в полноэкранный режим
2. Открыть модальное окно кликом на кнопку «Open modal»
3. Изменить ширину экрана в пределах от 768px до 799px
4. Браузер начинает отображать полосу прокрутки. Часть модального окна по горизонтали скрыта за областью видимости.

<img width="778" alt="Снимок экрана 2021-07-30 в 16 43 36" src="https://user-images.githubusercontent.com/8043216/127663437-658ce0ac-d483-425c-a79b-21c0c117901a.png">

# Ожидаемое поведение
Открытое модальное окно имеет ширину 800px, но не более 100% видимой области. Горизонтальная полоса прокрутки не появляется ни при каких условиях. Также желательно, чтобы модальное окно не прилипало к краям экрана при 100% ширине, то есть имело отступы. См. [пример](https://material-ui.com/components/dialogs/), как работают модальные окна.

## Десктоп (если данных нет оставьте блок пустым):
 - OS: MacOS
 - Browser: Google Chrome
 - Version: 92.0.4515.107 (Официальная сборка), (x86_64)

**Comment by reme3d2y** [comment]
Косяк :( поправим в ближайшее время
