### ISSUE TITLE
Реализация MaskedInput

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#78]
Предлагаю обсудить реализацию `MaskedInput`.

Кейсы:
1. Ввод по маске
2. Ввод суммы
3. Умный ввод номера карты
4. Умный ввод номера телефона, РФ и др страны.
5. Возможность реализации других сложных кейсов на основе этого компонента.

### 1. Текущая реализация на [text-mask-core](https://github.com/text-mask/text-mask/tree/master/core): https://github.com/alfa-laboratory/core-components/pull/76

Плюсы:
- нормальный ux
- расширяемость
- _используется в material_

Минусы:
- **не react-way**.
-  в данный момент нет мейнтейнера, но проект достаточно старый и самый используемый.

### 2. https://github.com/sanniassin/react-input-mask

Плюсы:
- нормальный ux
- react-way

Минусы:
- Есть [проблема](https://github.com/sanniassin/react-input-mask/issues/20) с масками динамичной длины (например ввод суммы). Но это вроде как решаемо.
- **Не работают тесты**

### 3. https://github.com/uNmAnNeR/imaskjs

Плюсы:
- подходит вообще для всего

Минусы:
- **не react-way**.
- жирный (53кб)

### 4. https://github.com/realadvisor/rifm

Плюсы:
- react-way
- маленький, простой и понятный

Минусы:
- Есть проблемы с ux (решаемые?)
<img src="https://user-images.githubusercontent.com/9968618/79103739-d4058a80-7d75-11ea-908b-887db9b3dc1c.gif" width="300"/>

### 5. https://github.com/insin/inputmask-core
Плюсы:
- используется в фижере

Минусы:
- судя по кол-ву доделок и issue в фижере - с ним не совсем все хорошо.

**Comment by SiebenSieben** [comment]
Давай опишем здесь требования к апишке компонента

**Comment by SiebenSieben** [comment]
Пока мне нравится 1 или 2 вариант, но не будет ли каких-то ещё проблем со вторым вариантом

**Comment by reme3d2y** [comment]
Попробовал поставить react-input-mask - не работают тесты.
Issue открыты, но реакции автора нет, и судя по его активности на гитхабе - фиксы вряд ли будут.

**Comment by reme3d2y** [comment]
Заметил также, что на проектах эту задачу все решают по-своему.

Как вариант - написать с нуля или взять наработки других проектов(акит, фижер и т.д.) и собрать все основные кейсы, типа номера, карты и пр.
Возможно, так получится лучше, чем пытаться найти универсальное решение.

**Comment by ilyamilosevic** [comment]
Есть такой на Vanilla JS: https://github.com/text-mask/text-mask

Но есть готовые обертки для React и прочих фреймворков, которые довольно просто реализуются: https://github.com/text-mask/text-mask/blob/master/react/src/reactTextMask.js

**Comment by reme3d2y** [comment]
> Есть такой на Vanilla JS: https://github.com/text-mask/text-mask
> 
> Но есть готовые обертки для React и прочих фреймворков, которые довольно просто реализуются: https://github.com/text-mask/text-mask/blob/master/react/src/reactTextMask.js
> 
> Демо: https://text-mask.github.io/text-mask/

Спасибо. Именно на нам сейчас и сделал. 
PR тут https://github.com/alfa-laboratory/core-components/pull/76

**Comment by reme3d2y** [comment]
Попробовал реализовать `<PhoneInput/>` с замечаниями из https://github.com/alfa-laboratory/arui-feather/issues/1113 - решение уместилось в несколько строчек. 

Если возражений нет - то предлагаю закрепить использование `text-mask-core`.
