### ISSUE TITLE
Закрытие/открытие Plate только нажатием на стрелочку

### ISSUE THREAD

**Issue by artemgafarov66** [alfa-laboratory/core-components#796]
# Описание
Было бы круто добавить в Plate возможность открытия/закрытия плашки кликом только по стрелочке. А то сейчас плашка открывается/закрывается кликом по плашке

## Десктоп (если данных нет оставьте блок пустым):
 - OS: MacOS
 - Browser: Safari
 - Version: 10

## Смартфон (если данных нет оставьте блок пустым):
 - Device: iPhone 6
 - OS: iOS 10
 - Browser: Chrome
 - Version: 65

# Дополнительная информация
Дополнительная информация

**Comment by reme3d2y** [comment]
fixed
