### ISSUE TITLE
Plate со свойством foldable закрывается/открывается по нажатию на пробел

### ISSUE THREAD

**Issue by artemgafarov66** [alfa-laboratory/core-components#798]
# Опишите проблему
Plate открывается/закрывается при нажатии на пробел

## Десктоп (если данных нет оставьте блок пустым):
 - OS: MacOS
 - Browser: Safari
 - Version: 10

## Смартфон (если данных нет оставьте блок пустым):
 - Device: iPhone 6
 - OS: iOS 10
 - Browser: Chrome
 - Version: 65

# Дополнительная информация
Дополнительная информация

**Comment by reme3d2y** [comment]
Такое происходит только если компонент в фокусе, и это ок. 

Или проблема в чем-то еще?

**Comment by reme3d2y** [comment]
fixed
