### ISSUE TITLE
Новый компонент Select

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/core-components#81]
# Описание
Предлагаю добавить компонент `<Select/>`

[Демка](https://alfa-laboratory.github.io/core-components/365c4fe077c8fcc23c3e8ed6e277a0ff5ce70f19/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-select--%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0)

Реализована базовая версия селекта на основе хуков из [downshift](http://downshift.netlify.app/)

- [x] Интеграция с downshift
- [x] Базовый API
- [x] Single/Multiple и allowUnselect
- [x] Кастомные компоненты
- [ ] ~~Типизация селекта и кастомных компонентов(generic)~~
- [x] Поддержка произвольных данных
- [x] Disabled для выборов
- [x] Поддержка нативного селекта
- [x] Поддержка Optgroup (включая кастомный компонент)
- [x] Рендер длинных списков
- [x] Stories и дока
- [ ] Согласование и расширение API
- [ ] Тесты

Макеты до сих пор не готовы, поэтому стандартные компоненты будут переделаны после того, как будет понятно, что можно считать за дефолтный селект. 

Поддерживаются кастомные компоненты, типы тут:
- [FieldProps](https://github.com/alfa-laboratory/core-components/pull/118/files#diff-62bd124daf4d22ac3c5f4f2d8e3b676fR162)
- [OptionsListProps](https://github.com/alfa-laboratory/core-components/pull/118/files#diff-62bd124daf4d22ac3c5f4f2d8e3b676fR187)
- [OptgroupProps](https://github.com/alfa-laboratory/core-components/pull/118/files#diff-62bd124daf4d22ac3c5f4f2d8e3b676fR199)
- [OptionProps](https://github.com/alfa-laboratory/core-components/pull/118/files#diff-62bd124daf4d22ac3c5f4f2d8e3b676fR211)

# Внешний вид

Точных макетов пока нет, но ориентировочный вид такой:

<img src="https://user-images.githubusercontent.com/9968618/79312219-3e016980-7f07-11ea-83aa-50bb4bd8844c.png" width="240" />

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=719%3A0

# API

```
type OptionShape = {
    /**
     * Значение выбранного пункта (например, для отправки на сервер)
     */
    value: string;

    /**
     * Контент, который будет отрендерен в выпадающем списке и в поле при выборе
     */
    text?: ReactNode;

    /**
     * Текст для нативного option (nativeSelect)
     */
    nativeText?: string;

    /**
     * Блокирует данный пункт для выбора
     */
    disabled?: boolean;
};

type GroupShape = {
    /**
     * Заголовок группы
     */
    label?: string;

    /**
     * Дочерние элементы
     */
    options: OptionShape[];
};
```

<table>
<thead>
  <tr>
    <th>Свойство</th>
    <th>Описание</th>
    <th>Тип</th>
    <th>По умолчанию</th>
    <th><span style="font-weight:400;font-style:normal">Обязательное</span></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><span style="font-weight:normal">block</span></td>
    <td><span style="font-weight:400;font-style:inherit;text-decoration:none">Растягивает компонент на ширину контейнера</span></td>
    <td>boolean</td>
    <td>false</td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">className</span></td>
    <td><span style="font-weight:400;font-style:inherit;text-decoration:none">Дополнительный класс</span></td>
    <td>string</td>
    <td></td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:400;font-style:normal">size</span></td>
    <td>Размер в соотвествии с дизайн системой</td>
    <td>'s' | 'm' | 'l' | 'xl'</td>
    <td>'m'</td>
    <td><span style="font-weight:400;font-style:normal">нет</span></td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">options</span></td>
    <td><span style="font-weight:400;font-style:inherit;text-decoration:none">Список вариантов выбора</span></td>
    <td>Array&lt;OptionShape | GroupShape&gt;</td>
    <td></td>
    <td>да</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">disabled</span></td>
    <td>Блокирует селект для выбора</td>
    <td>boolean</td>
    <td>false</td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">label</span></td>
    <td><span style="font-weight:400;font-style:inherit;text-decoration:none">Лейбл для поля</span></td>
    <td><span style="font-weight:normal">ReactNode</span></td>
    <td></td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">placeholder</span></td>
    <td>Плейсхолдер поля</td>
    <td>string</td>
    <td></td>
    <td>нет</td>
  </tr>
 <tr>
    <td><span style="font-weight:normal">name</span></td>
    <td>Атрибут name</td>
    <td>string</td>
    <td></td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">multiple</span></td>
    <td>Разрешает множественный выбор</td>
    <td><span style="font-weight:normal">boolean</span></td>
    <td>false</td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">allowUnselect</span></td>
    <td>Разрешает снимать выбор(multiple=false)</td>
    <td>boolean</td>
    <td>false</td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">closeOnSelect</span></td>
    <td>Закрывать селект после выбора?</td>
    <td>boolean</td>
    <td>!multiple</td>
    <td>нет</td>
  </tr>
 <tr>
    <td><span style="font-weight:normal">showArrow</span></td>
    <td>Рендерить стрелку?</td>
    <td>boolean</td>
    <td>true</td>
    <td>нет</td>
  </tr>
<tr>
    <td><span style="font-weight:normal">circularNavigation</span></td>
    <td>При навигации с клавиатуры переходить от последнего пункта меню к первому и наоборот</td>
    <td>boolean</td>
    <td>false</td>
    <td>нет</td>
  </tr>
<tr>
    <td><span style="font-weight:normal">selected</span></td>
    <td>Список выбранных пунктов (controlled-селект)</td>
    <td>OptionShape |</td>
    <td></td>
    <td>нет</td>
  </tr>
<tr>
    <td><span style="font-weight:normal">nativeSelect</span></td>
    <td>Рендерит нативный селект вместо выпадающего меню. (на десктопе использовать только с multiple=false)</td>
    <td>boolean</td>
    <td>false</td>
    <td>нет</td>
  </tr>
<tr>
    <td><span style="font-weight:normal">popoverOffset</span></td>
    <td>Смещение выпадающего меню по вертикали</td>
    <td>number</td>
    <td>4</td>
    <td>нет</td>
  </tr>
 <tr>
    <td><span style="font-weight:normal">valueRenderer</span></td>
    <td>Кастомный рендер выбранного пункта</td>
    <td>(options: OptionShape[]) =&gt; ReactNode</td>
    <td>Рендерит через запятую</td>
    <td>нет</td>
  </tr>
 <tr>
    <td><span style="font-weight:normal">optionRenderer</span></td>
    <td>Кастомный рендер пункта меню</td>
    <td>(option: OptionShape) =&gt; ReactNode</td>
    <td>option.text</td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">Field</span></td>
    <td>Компонент поля</td>
    <td>React.ComponentType&lt;FieldProps&gt;</td>
    <td><a href="https://github.com/alfa-laboratory/core-components/pull/118/files#diff-97112fc8b06718cd9e8747a83d0fb589" target="_blank" rel="noopener noreferrer">DefaultField</a></td>
    <td>нет</td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">OptionsList</span></td>
    <td><span style="font-weight:400;font-style:normal">Компонент меню</span></td>
    <td>React.ComponentType&lt;OptionsListProps&gt;</td>
    <td><a href="https://github.com/alfa-laboratory/core-components/pull/118/files#diff-ff145db97abe3f69c7d180c7a998bfd2" target="_blank" rel="noopener noreferrer">DefaultOptionsList</a></td>
    <td><span style="font-weight:400;font-style:normal">нет</span></td>
  </tr>
   <tr>
    <td><span style="font-weight:normal">Optgroup</span></td>
    <td><span style="font-weight:400;font-style:normal">Компонент группы</span></td>
    <td>React.ComponentType&lt;OptgroupProps&gt;</td>
    <td><a href="https://github.com/alfa-laboratory/core-components/pull/118/files#diff-151434fc50b8858c20881d814cf73b9d" target="_blank" rel="noopener noreferrer">DefaultOptgroup</a></td>
    <td><span style="font-weight:400;font-style:normal">нет</span></td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">Option</span></td>
    <td><span style="font-weight:400;font-style:normal">Компонент варианта (списка меню)</span></td>
    <td>React.ComponentType&lt;OptionProps&gt;</td>
    <td><a href="https://github.com/alfa-laboratory/core-components/pull/118/files#diff-6af90c77c6270d1c1ece6ca0a45402e3" target="_blank" rel="noopener noreferrer"><span style="font-weight:400;font-style:normal;text-decoration:none">DefaultOption</span></a></td>
    <td><span style="font-weight:400;font-style:normal">нет</span></td>
  </tr>
  <tr>
    <td><span style="font-weight:normal">onChange</span></td>
    <td>Обработчик выбора</td>
    <td>( event?: ChangeEvent, payload?: { selected?: OptionShape |; value?: string | string[]; name?: string; }, ) =&gt; void;<br></td>
    <td></td>
    <td>нет</td>
  </tr>
 <tr>
    <td><span style="font-weight:normal">onOpen</span></td>
    <td>Обработчик выбора</td>
    <td>(payload?: { open?: boolean; name?: string }) => void;<br></td>
    <td></td>
    <td>нет</td>
  </tr>
</tbody>
</table>

# Технические требования

- Стандартная функциональность селекта (в т.ч. multiple и optgroup)
- Возможность очистки значения
- Управление отображением нативного селекта на мобильных устройстах
- Поддержка произвольного набора данных
- Кастомный рендер поля ввода и списка опций.

Текущие реализации:
[akit](https://alfabank.ru/api/akit/?path=/docs/components-inputs-select--select-default)
[feather](https://digital.alfabank.ru/components/select)
[newclick](https://digital.alfabank.ru/demo/newclick-components/master/?path=/story/form-select--basic)

**Comment by prosto-lapsha** [comment]
Предлагаю для начала дождаться точных макетов, чтобы не пришлось переделывать реализацию.
Возможно для мультиселекта можно будет использовать компонент чекбокса, например, и всякое такое.
И вопрос, будем ли на мобильных устройствах оставлять кастомные селекты (знаю есть такие практики)?

**Comment by reme3d2y** [comment]
> Предлагаю для начала дождаться точных макетов, чтобы не пришлось переделывать реализацию.

Я планирую сделать так, чтобы сам селект не зависел от внешнего вида.
Т.е. по большей части он будет содержать только логику и апи.
А дочерние компоненты(поле и option'ы) уже сами будут задавать внешний вид и добавлять доп. логику. Поле и option'ы можно будет заменить.
По крайней мере сейчас идея такая 🤷‍♂️

> И вопрос, будем ли на мобильных устройствах оставлять кастомные селекты (знаю есть такие практики)?

Такая возможность будет. Судя по макетам - далеко не всегда получится использовать нативные option'ы для отображения инфы.

**Comment by 7rulnik** [comment]
https://github.com/downshift-js/downshift может помочь

**Comment by stepancar** [comment]
Возможность рендерить длинный список

**Comment by stepancar** [comment]
Клавиатурная навигация

**Comment by reme3d2y** [comment]
Реализована базовая версия селекта на основе хуков из [downshift](http://downshift.netlify.app/)

- [x] Интеграция с downshift
- [x] Базовый API
- [x] Single/Multiple и allowUnselect
- [x] Кастомные компоненты
- [x] Типизация селекта и кастомных компонентов (generic components)
- [x] Поддержка произвольных данных
- [ ] Согласование и расширение API
- [ ] Поддержка нативного селекта
- [ ] Поддержка Optgroup (включая кастомный компонент)

Макеты до сих пор готовы, поэтому стандартные компоненты будут переделаны после того, как будет понятно, что можно считать за дефолтный селект. 

Селект реализован как generic-компонент. 
Поддерживаются кастомные компоненты, типы тут:
- [FieldProps](https://github.com/alfa-laboratory/core-components/pull/118/files#diff-62bd124daf4d22ac3c5f4f2d8e3b676fR58)
- [MenuProps](https://github.com/alfa-laboratory/core-components/pull/118/files#diff-62bd124daf4d22ac3c5f4f2d8e3b676fR71)
- [MenuItemProps](https://github.com/alfa-laboratory/core-components/pull/118/files#diff-62bd124daf4d22ac3c5f4f2d8e3b676fR77)

**Comment by aso1datov** [comment]
Сейчас навигация стрелочками работает не так как ожидается. Разве перемещение по опциям не должно начинаться от выбранного элемента?

https://take.ms/BkxUb

**Comment by reme3d2y** [comment]
> Сейчас навигация стрелочками работает не так как ожидается. Разве перемещение по опциям не должно начинаться от выбранного элемента?
> 
> https://take.ms/BkxUb

Похоже это стандартное поведение downshift'а. Сделаю, чтобы было ожидаемо)

**Comment by dftpnd** [comment]
Привет из команды сайта)

**Comment by stepancar** [comment]
e нас есть кейсы когда в то что в айтеме списка отличается от того что подставляется в выбранное значение. Есть кейс когда кнопки справа нет

**Comment by 7rulnik** [comment]
@dftpnd ты куда-то не туда смотришь. Есть там управление с клавиатуры

**Comment by reme3d2y** [comment]
> у нас есть кейсы когда в то что в айтеме списка отличается от того что подставляется в выбранное значение. Есть кейс когда кнопки справа нет

<img src="https://user-images.githubusercontent.com/9968618/82042420-805ac980-96b2-11ea-8e7c-ef5e983a1965.png" width="120" />

**Comment by reme3d2y** [comment]
Обновил ссылку на макеты.

https://www.figma.com/file/hqSP3L6qu8UcL3sf18Su1M/Web-Components?node-id=719%3A0

**Comment by reme3d2y** [comment]
> Привет из команды сайта)
> 
> в этом селекте не реализован базовый функционал доступности (управление с клавиатуры, перемещение стрелочками, выбор элемента по пробелу, навигация к итему)
> 
> Так же хотелось бы изменить API, чтобы он был такой же как у стандартного селекта, в будущем это облегчит разработку с использование сторонних библиотек, таких как final-form

И вам привет)

С доступностью все должно быть ок, поэтому дауншифт и взяли за основу. Возможно у тебя что-то не работает?

По апи - что стоит поменять\добавить?
Я думаю отказаться от items в пользу options.

**Comment by aso1datov** [comment]
Вот еще что заметил: после выбора опции, при повторном открытии позиция скрола обнуляется, придется скролить до него самостоятельно

https://take.ms/YIRZFK

**Comment by reme3d2y** [comment]
> Вот еще что заметил: после выбора опции, при повторном открытии, позиция скрола обнуляется - придется скролить до него самостоятельно
> 
> https://take.ms/YIRZFK

исправил

**Comment by dftpnd** [comment]
> По апи - что стоит поменять\добавить?
> Я думаю отказаться от items в пользу options.
Хочется сохранить нативное api (так же проброс популярных свойст типа data-test-id или classname),а option сделать рендерпропсами типа такого:

<Select name="country" id="someId" data-test-id="foobar" className="my-">
    <option value="chicken">Chicken</option>
    <option value="ham">Ham</option>
    <option value="mushrooms">Mushrooms</option>
    <option value="cheese">Cheese</option>
    <option value="tuna">Tuna</option>
    <option value="pineapple">Pineapple</option>
</Select >

**Comment by stepancar** [comment]
@dftpnd как в этом случае предполагается работать с большими списками? ^

**Comment by reme3d2y** [comment]
@dftpnd так не получится сделать, есть слишком много нюансов. В каком кейсе может понадобиться рендерить селект именно таким способом, а не через пропсу?

**Comment by aso1datov** [comment]
@reme3d2y Планируется ли пропса, которой можно регулировать направление открытия опций? Будете ли popover прикручивать для них, чтобы избежать моментов, когда селект по каким-то причинам открывается в нескроллируемую область?

**Comment by reme3d2y** [comment]
> @reme3d2y Планируется ли пропса, которой можно регулировать направление открытия опций (вверх\вниз)? Будете ли popover прикручивать для них, чтобы избежать моментов, когда селект по каким-то причинам открывается в нескроллируемую область?

Popover уже используется. Контроля над ним нет, по умолчанию меню появляется снизу, а если места нет, то сверху.

**Comment by aso1datov** [comment]
Ну и еще к хотелкам, в беклог, `visibleOptionsCount`

**Comment by 7rulnik** [comment]
Добавлю, пару пунктов:

1. Возможно имеет смысл сделать цикличную навигацию с клавиатуры (при нажатии вниз на последнем элементе перекидывать к перввому)
2. При открытии с уже выбранным элементом можно было бы позиционировать его по центру, чтобы было видно, что ниже ещё есть другие опции (после меделевиума ещё уйма других опций, но их не видно)
![image](https://user-images.githubusercontent.com/5969049/82616025-a31a4000-9bd4-11ea-9d01-4dc1eab6c1b4.png)

**Comment by reme3d2y** [comment]
> 1. Возможно имеет смысл сделать цикличную навигацию с клавиатуры (при нажатии вниз на последнем элементе перекидывать к перввому)

done.

**Comment by dftpnd** [comment]
@reme3d2y главный кейс который я преследую, легкая интеграция с финал-формой. (а финал-форм используется хорошие практики и использует нативное апи компонентов)

Таким образом, мы бы на сайте смогли легко собирать формы. 

```
import { useForm, useField } from 'react-final-form-hooks'

const MyForm = () => {
  const { form, handleSubmit, values, pristine, submitting } = useForm({
    onSubmit, // the function to call with your form values upon valid submit
    validate // a record-level validation function to check all form values
  })
  const countries = useField('countries', form)

  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label>First Name</label>
        <Select {... countries.input} placeholder="Countries" />
       </div>
      
      <button type="submit" disabled={pristine || submitting}>
        Submit
      </button>
    </form>
  )
}
```

Может сразу сделаем пример селекта с финал-форм? я готов помочь)

**Comment by reme3d2y** [comment]
> Может сразу сделаем пример селекта с финал-форм? я готов помочь)

Окей, попробую собрать пример с ним.
Или можешь сам, если есть желание)

**Comment by reme3d2y** [comment]
@7rulnik, @stepancar 
> Возможность рендерить длинный список

done.

![screencast 2020-05-22 20-12-18](https://user-images.githubusercontent.com/9968618/82692802-06ee4880-9c69-11ea-9979-9772de0bcd3b.gif)
