### ISSUE TITLE
Textarea использует несуществующие css переменные

### ISSUE THREAD

**Issue by PutilovAI** [alfa-laboratory/core-components#811]
# Опишите проблему
Для примера нет переменной `--input-placeholder-color`
и в результирующем кода выводиться с ошибкой
![image](https://user-images.githubusercontent.com/22417118/130626918-b7e5ec4b-1548-417b-82c2-b452e48fd857.png)

![image](https://user-images.githubusercontent.com/22417118/130626727-29f4168f-a27f-464a-b202-17f50a47e158.png)

# Ожидаемое поведение
Свойство использует корректное значение переменной

**Comment by reme3d2y** [comment]
Ух, пофиксим. Можно попробовать пока заимпортить в проект инпут, должно быть ок
