### ISSUE TITLE
Иконки в компоненте Input имеют разный размер

### ISSUE THREAD

**Issue by ekabolotina** [alfa-laboratory/core-components#812]
# Описание
Предлагаю привести размер иконок success и erorr в компоненте Input к одному размеру. Сейчас иконка error имеет бОльший диаметр, чем иконка success. Выглядит это не очень.
На скриншоте наложенные друг на друга иконки, верхняя иконка полупрозрачная. Видно, что иконка error выходит за пределы иконки success.
![image](https://user-images.githubusercontent.com/8043216/130750608-2e5ef3f4-203c-460a-ae48-abe4cbd47b36.png)

# Дополнительная информация
https://codesandbox.io/s/sad-nobel-4ejmq?file=/src/App.js

**Comment by reme3d2y** [comment]
Обсудим с дизами

**Comment by reme3d2y** [comment]
Дизайнеры знают — как будут какие-то изменения, сделаем ПРы. Пока закрою
