### ISSUE TITLE
Добавить свойство ref для Typography

### ISSUE THREAD

**Issue by aleksey-ilin** [alfa-laboratory/core-components#827]
# Описание
Предлагаю прокинуть ref Typography. Надо чтобы следить за переполнением элемента с помощью https://github.com/alfa-laboratory/utils/blob/master/packages/utils/src/is-overflown/util.ts

**Comment by reme3d2y** [comment]
Норм, давай добавим :)

**Comment by reme3d2y** [comment]
Добавили
