### ISSUE TITLE
Проблема при сборке сторибук

### ISSUE THREAD

**Issue by raylyanway** [alfa-laboratory/core-components#84]
# Опишите проблему
Падает сборка сторибук, если я у себя в проекте подключаю компонент `button`

# Шаги для воспроизведения
1. Подключить компонент

# Ожидаемое поведение
Не падает сборка
<img width="1158" alt="Screen Shot 2020-04-15 at 15 18 52" src="https://user-images.githubusercontent.com/35544150/79341345-4fad3600-7f34-11ea-9192-f915b1833873.png">

**Comment by reme3d2y** [comment]
https://github.com/alfa-laboratory/core-components/issues/29
Пропустили ошибку и зарелизили. 

Уже пофиксили
