### ISSUE TITLE
Поведение Amount и Amount.Pure различаются

### ISSUE THREAD

**Issue by kiskv** [alfa-laboratory/core-components#858]
# Опишите проблему
при передаче пустого/неизвестного параметра currency в Amount отображается пустота на месте символа валюты
при передаче пустого/неизвестного параметра currency в Amount.Pure отображается строка undefined на месте символа валюты

# Шаги для воспроизведения
`<Amount.Pure value={1234500} currency={ undefined } minority={100} />`
`<Amount.Pure value={1234500} currency='MONOPOLY_DOLLARS' minority={100} />`

# Ожидаемое поведение
Amount и Amount.Pure должны вести себя одинаково

**Comment by reme3d2y** [comment]
https://github.com/alfa-laboratory/utils/pull/74
