### ISSUE TITLE
Уезжающий крестик в нотификациях

### ISSUE THREAD

**Issue by empty-child** [alfa-laboratory/core-components#865]
При использовании нотификаций с изменениями по разбивке текста, в нотификациях уезжает крестик на середину экрана. При этом в сторибуке воспроизвести подобное невозможно, только в реальном проекте

# Ожидаемое поведение
Корректное отображение крестика, как в сторибуке

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
![image](https://user-images.githubusercontent.com/17131646/139239519-2bf17a2e-f693-4680-9834-823d52637dac.png) | ![image](https://user-images.githubusercontent.com/17131646/139239553-031b3144-4772-43a4-bf8c-d0b8a875cbc3.png)|

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

**Comment by dmitrsavk** [comment]
https://github.com/alfa-laboratory/core-components/issues/866#issuecomment-965311711
