### ISSUE TITLE
Проблема взаимодействия arui-private и core-components

### ISSUE THREAD

**Issue by empty-child** [alfa-laboratory/core-components#866]
# Опишите проблему
При обновлении arui-private выше 17.45.2 (в 17.46.0 они бампнули версию core-components) в некоторых случаях происходит коллизия (судя по всему) стилей

# Ожидаемое поведение
Корректное отображение [элементов ](http://git.moscow.alfaintra.net/projects/CASHUFR/repos/ufr-cashrequest-components/browse/src/components/paginator)

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
![image](https://user-images.githubusercontent.com/17131646/139298240-ca07189d-83f3-43fe-afd0-99a35e7730d4.png) | ![image](https://user-images.githubusercontent.com/17131646/139298275-572aa187-3888-4520-a6bf-0d9fea61f346.png)|

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: Windows
 - Browser: Chrome
 - Version: 94

**Comment by dmitrsavk** [comment]
@empty-child

Проблема заключается в том, что при установке зависимостей, ставятся две разные версии кор-компонентов - для arui-private одна версия, для самого проекта другая. Затем, в итоговую сборку попадают обе версии стилей, которые странным образом конфликтуют между собой.

В следующих релизах мы это пофиксим, а пока можешь явно указать, какую версию кор-компонентов ставить.
Это можно сделать, прописав `resolutions` в `package.json`:

```json
"resolutions": {
    "@alfalab/core-components": "21.3.0"
}
```

PS: надо будет снести node_modules

**Comment by empty-child** [comment]
Я пока зафиксировал старый прайвет, тоже помогло
