### ISSUE TITLE
Использование компонента Radio без лейбла

### ISSUE THREAD

**Issue by empty-child** [alfa-laboratory/core-components#869]
# Опишите проблему
Некорректно происходит обработка границ компоненты Radio при использовании без лейблов и подсказок

# Шаги для воспроизведения
Убрать у компоненты label и hint

# Ожидаемое поведение
Корректное вычисление границ объекта

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
Квадратные границы, совпадающие с границами кружка | ![image](https://user-images.githubusercontent.com/17131646/140039359-012ea522-6c30-419e-a449-94ee8781026e.png)|

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version: 94, 93

**Comment by SiebenSieben** [comment]
Вероятно, касается и Checkbox

**Comment by empty-child** [comment]
Нет)))
(я серьезно, оно нормально отображается)
![image](https://user-images.githubusercontent.com/17131646/142429634-f90ae9cf-7b5b-4d0b-9735-72573f892d15.png)
