### ISSUE TITLE
Позиционирование селектов относительно инпутов

### ISSUE THREAD

**Issue by empty-child** [alfa-laboratory/core-components#877]
# Опишите проблему
Проблема еще из arui-feather: если в рамках одного Grid.Col разместить Input и Select, Select не будет поставлен в одну линию с Input (в скриншотах)

# Шаги для воспроизведения
В рамках одного Grid.Col разместить Input и Select

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
![image](https://user-images.githubusercontent.com/17131646/140911488-6e4f2812-725a-4f91-ac4d-786313476a2e.png) | ![image](https://user-images.githubusercontent.com/17131646/140910504-c0a51783-130d-4a4e-9655-0aa6cec1e191.png)|

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version: 94, 94

**Comment by EGNKupava** [comment]
Можно подробнее по шагам воспроизведения? И откуда в инпуте появляется padding-top 25px?. т.к. и CalendarInput | Input | Select завязаны на одной переменной --form-control-labeled-s-paddings где верхний паддинг 23px

**Comment by empty-child** [comment]
25px - это я пытался показать, как хотелось бы видеть
Могу дать ссылку как на хостящийся внутренний проект, так и на специальный sandbox, который надо сбилдить

**Comment by empty-child** [comment]
Либо вот так сделать
`                    <Grid.Row>
                        <Grid.Col>
                            <Input block={ true } label="email" name="email" />
                        </Grid.Col>
                        <Grid.Col>
                            <Select block={ true } options={ [{ key: 'test', content: 'test' }] } />
                        </Grid.Col>
                    </Grid.Row>`
И посмотреть на их расположение

**Comment by EGNKupava** [comment]
Ну если к Select добавить label то все Ок 
![image](https://user-images.githubusercontent.com/62112300/142863844-02f5c1b2-c8ac-4c11-9fe5-5a1fe76a0f09.png)

**Comment by EGNKupava** [comment]
А ты имеешь ввиду когда у Input есть label, а у Select нет? 
![image](https://user-images.githubusercontent.com/62112300/142864170-e0b67044-a9c6-4daf-94b9-ed8a21c36922.png)

**Comment by empty-child** [comment]
![image](https://user-images.githubusercontent.com/17131646/142865886-72288fc9-52fd-41c9-8950-deafc2b89c19.png)
Вне зависимости. Не исключаю, что это опять конфликт прайвета и компонент

**Comment by EGNKupava** [comment]
Ок, ну тут явно!

**Comment by EGNKupava** [comment]
> 25px - это я пытался показать, как хотелось бы видеть Могу дать ссылку как на хостящийся внутренний проект, так и на специальный sandbox, который надо сбилдить

Можно на хостящийся проект ссылку?

**Comment by empty-child** [comment]
https://ufrmsdev1/ufr-cashrequest-ui/editRequest/38515511
Только из внутренней сети

**Comment by reme3d2y** [comment]
Еще актуально? 

На скриншотах какие-то странные инпуты, у нас таких нет)) Там накинуты какие-то стили сверху?

**Comment by empty-child** [comment]
Как ни странно, кто-то, видимо, исправил, но не отписался. Закрываю
Это стандартные компоненты со стилями
`:root {
    --form-control-bg-color: #fff;
    --form-control-disabled-bg-color: #fff;
}`

**Comment by reme3d2y** [comment]
Это вы под старый стиль так компоненты адаптировали?

**Comment by empty-child** [comment]
Да. Не очень хотелось услышать "бу-бу-бу" от пользователей
