### ISSUE TITLE
17 реакт и нпм

### ISSUE THREAD

**Issue by zinoviev** [alfa-laboratory/core-components#878]
Кажется не работает с 17 реактом из-за зависимости у icons-classic, если использовать npm 

npm ERR! node_modules/react
npm ERR!  react@"^17.0.2" from the root project
npm ERR!  peer react@"^16.9.0 || ^17.0.1" from @alfalab/core-components@21.3.0
npm ERR!  node_modules/@alfalab/core-components
npm ERR!   @alfalab/core-components@"*" from the root project
npm ERR!  7 more (react-dom, @testing-library/react, flexlayout-react, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.0" from @alfalab/icons-classic@1.74.0
npm ERR! node_modules/@alfalab/core-components/node_modules/@alfalab/icons-classic
npm ERR!  @alfalab/icons-classic@"^1.74.0" from @alfalab/core-components@21.3.0
npm ERR!  node_modules/@alfalab/core-components
npm ERR!   @alfalab/core-components@"*" from the root project

Что бы воспроизвести, можно создать проект на последнем CRA и через npm попробовать добавить core-components

**Comment by zinoviev** [comment]
олсо @alfalab/icons-glyph не ставится через npm, приходится явно его устаналивать и там тоже конфликт с версией реата

**Comment by dmitrsavk** [comment]
@zinoviev 
а какая версия npm и node?
у меня не воспроизводится на 
node v14.17.0
npm 6.14.14

**Comment by zinoviev** [comment]
Я работаю на маке:
node v16.5.0
npm 7.19.1

У тиммейта винда:
нода нода 16.11.1
npm 8.0

**Comment by dmitrsavk** [comment]
Поправил зависимости в иконках, в следующих версиях должно будет устанавливаться без ошибок

**Comment by zinoviev** [comment]
@dmitrsavk не перепаблишили еще?

**Comment by dmitrsavk** [comment]
нет еще, я сначала думал подождать новых иконок, чтобы оно само обновилось, но лучше руками тогда скоро залью

**Comment by zinoviev** [comment]
@dmitrsavk нам не критично, пинганите тогда кода будет апдейт

**Comment by dmitrsavk** [comment]
@zinoviev 
сегодня релизили `@alfalab/core-components@21.3.1`, по-идее с этой версии все должно быть ок
