### ISSUE TITLE
В какой стандарт компилировать TS?

### ISSUE THREAD

**Issue by 7rulnik** [alfa-laboratory/core-components#88]
# Описание
Т.к. библиотека будует использоваться в абсолютно разных проектах, то нам необходимо определиться как мы будем дистрибьютить библиотеку. На текущий момент таргет компиляции ES5, что является немного устаревшим стандартом. В сайте 2 бандла (modern мы переодически сдвигаем в сторону более новых браузеров):
```js
module.exports = {
    legacy: ['Explorer 11'],
    modern: ['Chrome >= 74', 'Safari >= 12.1', 'iOS >= 12.1', 'Firefox >= 68', 'Opera >= 63']
};
```

Перед тем как распространять либу по проектам нужно будет решить в каком виде мы будем поставлять код. Есть несколько вариантов:

- компилировать в последний ES20** стандарт и транспайлить в проектах через бабель
- 2 точки входа: ES5/ES20** — импортировать в проектах через разные пути `import { Button } from 'core-components/button/es5'`

- компилировать в какой угодно стандарт, устраивающий большинство (например ES5), но так же держать в пакете TS исходники. В проекте, который хочет таргетироваться под современные бандлы импортировать `.ts` файлы

**Comment by stepancar** [comment]
Чтобы распространять выше ES5 - нужно тюнить arui-scripts

**Comment by reme3d2y** [comment]
Исходники вообще не проблема добавить

**Comment by 7rulnik** [comment]
@reme3d2y добавить не проблема, но могут быть сложности с интеграцией. Могут отличаться версии тайпскрипта или в принципе подход к транспайлу. В сайте мы транспайлим тс через бабель например.

**Comment by reme3d2y** [comment]
- Первый пункт пока не подходит из-за arui-scripts.
- Второй сделать не сложно, но норм ли это решение?
- С третьим пунктом могут быть проблемы, если мы что-то новое заюзаем, чего не будет на проекте? Это можно как-то решить?

**Comment by 7rulnik** [comment]
1. В arui-scripts это можно будет сделать с обратной совместимостью
2. Не знаю. У меня нет строгого мнения на этот счёт.
3. Да, всё верно. Мы в сайте транспайлим тс через бабель. Вы только что перешли на тс. Они максимально близки между собой https://babeljs.io/docs/en/babel-preset-typescript. Такой подход будет сдерживать нас от обновления в случае, если вы бампаете тс, недели на 2-4 (обычно в такой промежуток выходит новая версия плагина). Есть ещё воркэраунд: использовать такую же версию тс только для кор-компонентс, но мне этот вариант не оч нравится если честно.

Пока что мне ближе всего 3 вариант.

**Comment by dmitrsavk** [comment]
Пообщались с @7rulnik, закоммитились на том, что мы будет дистрибьютить две версии: es5 и es2020. Дефолтная будет es5

**Comment by etroynov** [comment]
если вопрос закрыть, закройте issue.
