### ISSUE TITLE
Пример с темизацией не отвечает требованиям

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/core-components#89]
https://github.com/alfa-laboratory/core-components#-%D1%82%D0%B5%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F

У нас микросервисная архитектура. Такое предложение темизации использовать можно, но в чем суть?
Во всех проектах будет копипаста с ошибками, нет возможности централизованно изменить  переменные.
Нет возможности обновлять все приложения.
Вот недавно была история с тем что шрифт в chrom 81 не работает. Возможности обновить все проекты нет.

**Comment by SiebenSieben** [comment]
Мы подготовим и будем поддерживать файлы тем.

Вам достаточно будет подключить тему из core-components. Инструкцию обновим.

Первая темя будет для ваших приложений.

Централизованно, без копипасты.

**Comment by SiebenSieben** [comment]
Про шрифт: font-family следует брать из core-components-vars. Вы уже начали на него переходить, но мы пока не форсируем.

**Comment by stepancar** [comment]
@SiebenSieben так проблема то в том что нет в этом плане улучшения относительно того как было раньше. Мы сейчас подрубаем переменные непосредственно в проектах. Как без передеплоя обновить во всем интерфейсе скругления?

**Comment by 7rulnik** [comment]
@stepancar ты хочешь прям в рантайме менять тему получается? А откуда это требование возникло? Да и темы вроде не так часто меняеются.
Если хочется в рантайма, то нужно не транспайлить переменные. Для IE есть такая штука, https://github.com/jhildenbiddle/css-vars-ponyfill и такая https://github.com/nuxodin/ie11CustomProperties. Я не юзал, но смотрел демку. Ну и в целом если возникают такие требования, то я бы пожалуй в сторону css-in-js смотрел.

**Comment by 7rulnik** [comment]
У нас вот другое требование появилось: возможность поддерживать 2 темы одновременно. И css-in-js это решается легко, например.

**Comment by SiebenSieben** [comment]
@stepancar @7rulnik 

Вот вы тут напридумывали: обновлять без передеплоя, разные дизайны…

Встреча по темизации, обоим, вне очереди

**Comment by 7rulnik** [comment]
Это не я придумал, ты сам знаешь мой кейс :)

**Comment by SiebenSieben** [comment]
Да не, я всё понимаю, имеет смысл ещё раз взвесить выбранное решение )

**Comment by reme3d2y** [comment]
Затестил [полифил](https://github.com/nuxodin/ie11CustomProperties) для IE11.
Все, что нужно для наших кейсов - работает. 

- Если нужно просто применить тему ко всем компонентам — делаем вот [так](https://github.com/alfa-laboratory/core-components#-%D1%82%D0%B5%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F)  
- В остальных кейсах — не транспайлим css-переменные и подключаем полифил для IE11

**Comment by SiebenSieben** [comment]
[Док по темизации](https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%8B-%D1%82%D0%B5%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F--page)
