### ISSUE TITLE
Перенести classnames в peerDependencies

### ISSUE THREAD

**Issue by 7rulnik** [alfa-laboratory/core-components#91]
# Опишите проблему
Сейчас classnames лежит в dependencies пакетов. Это достаточно базовая зависимость, которая есть скорей всего в каждом проекте, но версии могут отличаться. Из-за этого могут появиться дубликаты в бандле

# Ожидаемое поведение
classnames должент быть в peerDependencies

> P.S. Проблема будем возникать не только c classnames и кажется, что нужно решить что должно быть в peerDeps, а что в deps.

**Comment by reme3d2y** [comment]
Спасибо, уже тоже заметил это. Открою PR в ближайшее время. 

По списку зависимостей - согласен, стоит обсудить и закрепить, что в каком списке должно быть.
