### ISSUE TITLE
Parse error для компонентов Row и Col

### ISSUE THREAD

**Issue by asmerkulov** [alfa-laboratory/core-components#918]
# Опишите проблему
При использовании компонентов Row и Col при сборке в jenkins происходит исключение
- ./node_modules/@alfalab/core-components/grid/col/index.css
- ParserError: Expected closing parenthesis at line: 1, column 5

```
<Space>
  <Row align="middle">
    <Col>
      <Button view="primary">Команда 1</Button>
    </Col>
    <Col>
      <Button view="primary">Команда 2</Button>
    </Col>
   </Row>
</Space>
```

**Comment by reme3d2y** [comment]
Привет. А можешь чуть больше подробностей? Если еще актуально

**Comment by reme3d2y** [comment]
duplicate #973
