### ISSUE TITLE
FileUploadItem: пропадает имя файла

### ISSUE THREAD

**Issue by MaksimAliakhnovich** [alfa-laboratory/core-components#923]
# Опишите проблему
При срабатывании @media screen and (max-width: 47.9375em) и наличии ошибок пропадает имя файла

# Шаги для воспроизведения
1. применить компонент на странице
2. заполнить параметр error текстом

# Ожидаемое поведение
Имя файла видно на всех разрешениях

# Чек лист
- [ ] Тесты
- [ ] Документация

# Внешний вид

Ожидаемый        | Фактический
:---------------:|:--------------------|
![image](https://user-images.githubusercontent.com/33697594/145821165-9ae11b93-4534-4294-a718-ec18b283537e.png) | ![image](https://user-images.githubusercontent.com/33697594/145821054-a34275e5-fbad-4c7d-996e-3f7cc626a253.png) |

# Тестовый стенд

## Десктоп (если данных нет оставьте блок пустым):
 - OS: win 10
 - Browser: Chrome
 - Version: Версия 96.0.4664.93

## Смартфон (если данных нет оставьте блок пустым):

# Дополнительная информация
Дополнительная информация

**Comment by reme3d2y** [comment]
Привет. Эта проблема относится к компоненту FileUpload из arui-private.
@dmitrbrvsk посмотришь? Там flex-basis: 100% не нужно делать

![Uploading image.png…]()
