### ISSUE TITLE
keepCharPositions - не позволяет удалять символы в начале даты

### ISSUE THREAD

**Issue by andreynovikov95** [alfa-laboratory/core-components#929]
# Опишите проблему
При стирании дней или номера месяца не происходит удаление символов в инпуте при включенном свойстве **keepCharPositions** в CalendarInput

# Ожидаемое поведение
При удалении с позиции дней месяца или номера месяца удаление происходит

## Десктоп (если данных нет оставьте блок пустым):
 - OS: все
 - Browser: все
 - Version: все

**Comment by reme3d2y** [comment]
Скоро возьмем в работу DateInput, который будет лишен этих проблем
