### ISSUE TITLE
Select: сделать параметры в onChange как у других компонентов

### ISSUE THREAD

**Issue by web-arch** [alfa-laboratory/core-components#936]
Сейчас onChange в Select принимает:
`((payload: { selected: OptionShape | null; selectedMultiple: OptionShape[]; name?: string; }) => void)`
Хочу обернуть все компоненты  из core-components в HOC, но из за того что у селекта другие параметры в onChange нужно делать костыли.

Хотелось бы так:
`((event: ChangeEvent<HTMLInputElement>, payload: { value: OptionShape; }) => void)`
или 
`((event: ChangeEvent<HTMLInputElement>, payload:  { selected: OptionShape | null; selectedMultiple: OptionShape[]; name?: string; } ) => void)`

**Comment by reme3d2y** [comment]
Привет. Внутри компонента используется downshift, который не дает никакого события при выборе :( Плюс это будет ломающим изменением.  Так что, к сожалению, сейчас сделать ничего не получится
