### ISSUE TITLE
SliderInput: AmountSliderInput остаётся 0 если всё стереть

### ISSUE THREAD

**Issue by web-arch** [alfa-laboratory/core-components#938]
https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-sliderinput--slider-input
**Сейчас:**
Если ввести сумму и потом всё стереть остаётся 0 и он останется если потом вводить другие числа
**Ожидаемо:**
Сумму можно стереть целиком

**Comment by web-arch** [comment]
Ещё из за https://github.com/alfa-laboratory/core-components/blob/master/packages/slider-input/src/Component.tsx#L187 появляется <img width="777" alt="Анкета на кредит 🔊 2022-01-12 15-20-03" src="https://user-images.githubusercontent.com/15825498/149139260-eec16966-56d4-461c-ba7f-8e3347b3273a.png">

**Comment by web-arch** [comment]
хотя мб не в паттерне дело, но при сабмите почему-то ошибка появляется

**Comment by reme3d2y** [comment]
Привет. Нолик поправил, паттерн тоже поменял на другой
