### ISSUE TITLE
Некорректные пропы у иконок icons-glyph

### ISSUE THREAD

**Issue by mrAnomalyy** [alfa-laboratory/core-components#967]
# Опишите проблему
При использовании ряда иконок, в консоль браузера падают предупреждения о неправильных prop'ах.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/39645529/151563465-535d5da7-612e-4877-958e-8bba9f605f7f.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/39645529/151563491-4e50a350-4248-4c33-8f93-a662bd0b426f.png">

# Шаги для воспроизведения
1. Использовать одну из следующих иконок - в них неправильно заданы пропы (stroke-linejoin - должно быть strokeLineJoin, stroke-width - strokeWidth). Видимо, в старой версии icons была проблема с переводом этих атрибутов в camelCase

<img width="450" alt="image" src="https://user-images.githubusercontent.com/39645529/151563125-a10e1359-72c2-4021-8014-4750b897fe8a.png">

# Ожидаемое поведение
Предупреждений не должно быть, нужно использовать корректные пропы

# Чек лист
- [ ] Обновить зависимость icons-glyph (текущая - 1.9.х, последняя - 2.6.0)

## Десктоп (если данных нет оставьте блок пустым):
 - OS: MacOS
 - Browser: Safari, Chrome

# Дополнительная информация
Пытался локально поднять версию icons-glyph, однако после этого проект не стартовал - какая-то проблема с резолвом компонентов.
P.S. не смотрел, есть ли такая же проблема в других наборах иконок

**Comment by dmitrsavk** [comment]
В свежих версиях иконок нет такой проблемы. Вот, к примеру:
https://github.com/alfa-laboratory/icons/blob/master/packages/glyph/src/SfLinesMIcon.tsx

**Comment by dmitrsavk** [comment]
Надо будет обновить зависимости.
А то у нас старые иконки с неправильными атрибутами могут встречаться)
