### ISSUE TITLE
Неверный line-height в Checkbox с подсказкой

### ISSUE THREAD

**Issue by koretskyhub** [alfa-laboratory/core-components#969]
Сейчас компонент в варианте с подсказкой имеет высоту 46px
На макетах высота 48px

Похоже причина в line-height для подсказки: должно быть 20px вместо 18px

### Ожидаемый результат
![image](https://user-images.githubusercontent.com/28655052/151754453-f265046c-d995-4439-b064-a6d182af198e.png) 

### Фактический результат
![image](https://user-images.githubusercontent.com/28655052/151754472-cc80493f-f944-4ef1-9975-02bc17e8c6fd.png)

**Comment by reme3d2y** [comment]
@koretskyhub привет. Возьмем на след. недел в работу
