### ISSUE TITLE
Подход для пробрасывания classNames

### ISSUE THREAD

**Issue by dmitrsavk** [alfa-laboratory/core-components#97]
Предлагаю использовать следующий подход при пробрасывании classNames
На примере https://github.com/alfa-laboratory/core-components/pull/93

```ts
    /**
     * Дополнительные классы
     */
    classNames?: {
        /**
         * Дополнительный класс для поповера
         */
        popper?: string;

        /**
         * Дополнительный класс для стрелочки
         */
        arrow?: string;
    };
```

**Comment by raylyanway** [comment]
@etroynov предлагает плоскую систему пропсов. Своё мне о берёт не из официальных доков, а из встечаемых им ранее диалогов на эту тему в интернете.

**Comment by raylyanway** [comment]
Я пригласил ребят (фронтов) сюда. Может кто что знает. Женю Тройнова тоже

**Comment by avkvak** [comment]
Насколько я в курсе, при таком подходе, чтобы предотвратить ненужные ре-рендеры, придется каждый компонент, принимающий подобного рода пропсу, оборачивать в memo (или pureComponent), что не очень гуд. Я за плоскую

**Comment by 7rulnik** [comment]
Ре-рендеров не будет, если вынести создание объекта за пределы компонента, но это не всегда возможно сделать

**Comment by etroynov** [comment]
Я против такого подхода по ряду причин:
- пропс объект лови ререндеры;
- classNames очень близко к className, в этом PR ( https://github.com/alfa-laboratory/core-components/pull/63 ) вы были против нативных названий не по назначению, тут я вижу примерно схожую картину;


Зачем доп класс для стрелки?
Почему нельзя передавать класс отдельно?

**Comment by dmitrsavk** [comment]
Всем спасибо за комменты! Решили использовать плоскую структуру.
