### ISSUE TITLE
Добавить возможность тултипу иметь массив детей

### ISSUE THREAD

**Issue by aleksey-ilin** [alfa-laboratory/core-components#974]
# Описание
Компонент tooltip в качестве ребенка не может принимать массив детей.
https://github.com/alfa-laboratory/core-components/blob/master/packages/tooltip/src/Component.tsx#L74
Предлагаю добавить такую возможность.

**Comment by reme3d2y** [comment]
@aleksey-ilin а когда это может быть нужно?
Кажется, нужно только поменять тип и 322 строчку. Принесешь ПР?

**Comment by aleksey-ilin** [comment]
да, принесу.
это надо для таких случаев:
![Excalidraw 2022-02-17 22-37-52](https://user-images.githubusercontent.com/32348899/154557693-7217eff6-03cf-4e42-bbd1-a334957bf528.png)

здесь три кнопки, которые могут быть все задизейблены, а тултип для них один
