### ISSUE TITLE
Notification: скрывается при зажатии левой кнопки мыши и отведению курсора в сторону

### ISSUE THREAD

**Issue by wlatt1991** [alfa-laboratory/core-components#982]
# Опишите проблему
Обнаружил баг в компоненте Notification. Если навести на уведомление курсор, потом зажать ЛКМ и перевести курсор влево за пределы уведомления и отжать ЛКМ, то уведомление скроется, даже если оно должно скрываться только по нажатию на кнопку закрытия.

# Шаги для воспроизведения
1. Навести на уведомление курсор
2. Зажать ЛКМ (левую кнопку мыши) и не отжимая перевести курсор влево за пределы уведомления
3.  Отпустить ЛКМ

# Ожидаемое поведение
Уведомление не должно скрываться

## Десктоп (если данных нет оставьте блок пустым):
 - OS: MacOS
 - Browser: Chrome
 - Version: 97.0.4692.99 (Официальная сборка), (x86_64)

# Дополнительная информация

https://user-images.githubusercontent.com/16727848/152784331-20bb19a8-ba02-45a2-93ff-d2e7d9957028.mov

**Comment by dmitrsavk** [comment]
Это не баг, это фича))
Это у нас так работает свайп - то есть по свайпу он закрывается

**Comment by wlatt1991** [comment]
Хм, тогда может сделать эту фичу опциональной? Пусть она по дефолту включена.

**Comment by wlatt1991** [comment]
Так планируется с этим что-то делать? Или эта фича должна работать на десктопах?

**Comment by reme3d2y** [comment]
@wlatt1991 привет! У нас сейчас мало ресурсов и это улучшение не в приоритете. Поэтому будет круто, если ты принесешь ПР. 

Поведение кажется вполне корректным. В текущей реализации можно проверять, если onClickOutside не установлен, то и по свайпу тоже не закрывать.
