### ISSUE TITLE
PickerButton: доступны не все размеры обычной кнопки

### ISSUE THREAD

**Issue by EugeneFokin** [alfa-laboratory/core-components#986]
На проекте требуется сделать PickerButton размера xxs. В [доке](https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-pickerbutton--picker-button#%D0%B0%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0) написано, что для PickerButton должны быть доступны все размеры обычной кнопки. В демке xxs доступен и кажется работает корректно. Но на практике проп size у PickerButton принимает только `type PickerButtonSize = 'xs' | 's' | 'm'`. Где ошибка - в доке или в коде?

# Ожидаемое поведение
Могу юзать компонент размера xxs

# Дополнительная информация
Исп. core-components версии 23.12.0

**Comment by reme3d2y** [comment]
@EugeneFokin @Rinta01 на след. неделе возьмем в работу
